### ISSUE TITLE
Check the exponent vector length in `push_term!` and friends

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#1016]
https://github.com/Nemocas/AbstractAlgebra.jl/blob/f6413231d246740a0de65c985766b1e0fd3cb909/src/generic/MPoly.jl#L3844-L3845

If the exponent vectors don't have the correct length, this gives garbage (no, it does not use zero for the trailing variables, just garbage). We should check this.

**Comment by wbhart** [comment]
Looks like this was fixed in a recent release. Closing for now. Feel free to reopen if it is not sufficient.
