### ISSUE TITLE
interface examples in docs do not work in oscar

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#1019]
In the section preceding
https://oscar-system.github.io/Oscar.jl/dev/AbstractAlgebra/polynomial/#Iterators
we have 
```
julia> S, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> f = x^3 + 3x + 1
x^3 + 3*x + 1

julia> g = S(BigInt[1, 2, 0, 1, 0, 0, 0]);

julia> n = length(f)
4

julia> c = coeff(f, 1)
3

julia> g = set_length!(g, normalise(g, 7))
x^3 + 2*x + 1

julia> g = setcoeff!(g, 2, BigInt(11))
x^3 + 11*x^2 + 2*x + 1

julia> fit!(g, 8)

julia> g = setcoeff!(g, 7, BigInt(4))
4*x^7 + x^3 + 11*x^2 + 2*x + 1
```

Here
- `normalise` will not work because it is an internal function specific to one polynomial implementation
- `setcoeff!` will not work because the coefficient `BigInt(4)` has the wrong type.

I propose we delete these last 4 julia lines.

**Comment by wbhart** [comment]
Fine by me.

**Comment by tthsqe12** [comment]
I don't think we can remove it as it is listed as required. Therefore, the nemo polynomials are simply not in compliance. https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/docs/src/poly_interface.md#required-functionality-for-univariate-polynomials

The situation is: `setcoeff!` returns illegal polynomials by design. Without, `normalise`, there is no way to turn these back into legal polynomials.

https://github.com/Nemocas/AbstractAlgebra.jl/blob/e2f87ac280c4de3986c699a930a7537ab0ed3faf/src/generic/Poly.jl#L30-L38

**Comment by thofma** [comment]
Did you delete one of your comments @tthsqe12?

**Comment by tthsqe12** [comment]
yes, now I propose it becomes the following. It actually works in oscar.
```
julia> S, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> f = x^3 + 3x + 1
x^3 + 3*x + 1

julia> g = S(BigInt[1, 2, 0, 1, 0, 0, 0]);

julia> n = length(f)
4

julia> c = coeff(f, 1)
3

julia> g = set_coefficient!(g, 2, ZZ(11))
x^3 + 11*x^2 + 2*x + 1

julia> g = set_coefficient!(g, 7, ZZ(4))
4*x^7 + x^3 + 11*x^2 + 2*x + 1
```

**Comment by thofma** [comment]
Yes, perfect!
