### ISSUE TITLE
div for LaurentPolynomialRing

### ISSUE THREAD

**Issue by ulthiel** [Nemocas/AbstractAlgebra.jl#1020]
In AbstractAlgebra v0.21.0 there's no div for Laurent polynomials:

```
julia> R, x = LaurentPolynomialRing(ZZ, "x")
(Univariate Laurent Polynomial Ring in x over Integers, x)

julia> div(x,x)
ERROR: MethodError: no method matching div(::AbstractAlgebra.Generic.LaurentPolyWrap{BigInt, AbstractAlgebra.Generic.Poly{BigInt}}, ::AbstractAlgebra.Generic.LaurentPolyWrap{BigInt, AbstractAlgebra.Generic.Poly{BigInt}}, ::RoundingMode{:ToZero})
Closest candidates are:
  div(::Any, ::Any) at div.jl:37
  div(::T, ::Base.MultiplicativeInverses.SignedMultiplicativeInverse{T}) where T at multinverses.jl:138
  div(::T, ::Base.MultiplicativeInverses.UnsignedMultiplicativeInverse{T}) where T at multinverses.jl:143
  ...
Stacktrace:
 [1] div(a::AbstractAlgebra.Generic.LaurentPolyWrap{BigInt, AbstractAlgebra.Generic.Poly{BigInt}}, b::AbstractAlgebra.Generic.LaurentPolyWrap{BigInt, AbstractAlgebra.Generic.Poly{BigInt}})
   @ Base ./div.jl:37
 [2] top-level scope
   @ REPL[4]:1
```

Could this be added? The Laurent polynomial ring is Euclidean, so all the functions for Euclidean rings should be defined. (I'm not entirely sure how division works algorithmically though.)

**Comment by tthsqe12** [comment]
ZZ[x,x^-1] is Euclidean? If you tell us what Euclidean function you want, we can probably implement it. Same goes for F[x,x^-1] for any field F.

**Comment by fieker** [comment]
On Mon, Sep 20, 2021 at 01:21:04AM -0700, dan wrote:
> ZZ[x,x^-1] is Euclidean? If you tell us what Euclidean function you want, we can probably implement it. Same goes for F[x,x^-1] for any field F.
> 
I am currently working on F[x, x^-1], but ZZ I don't know...

**Comment by ulthiel** [comment]
Sorry, it's Euclidean only if the base ring is a field. What I was interested in when coefficients are general (like the integers) is test for division and exact division. @fieker told me since Laurent polynomials are just shifted polynomials, this should be easy to implement.

**Comment by ulthiel** [comment]
Cheers!

**Comment by tthsqe12** [comment]
Was this divisibility test the *only* issue you had with the Laurent polynomials?
