### ISSUE TITLE
`compose` for maps versus univariate polynomials and power series

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1025]
(This is an offshoot from https://github.com/oscar-system/Oscar.jl/issues/690)

The AA manual [defines](https://nemocas.github.io/AbstractAlgebra.jl/dev/map/#Composition-of-maps) `compose(f,g)` for maps as meaning the function `x -> g(f(x))`, i.e. `g ∘ f`. Fine by me!

However, the [documentation for `compose(a::PolyElem, b::PolyElem)`](https://nemocas.github.io/AbstractAlgebra.jl/dev/polynomial/#AbstractAlgebra.compose-Tuple{PolyElem,%20PolyElem}) claims that it returns `a∘b`. So either the documentation is wrong and should be fixed; or it is correct and the underlying code indeed behaves that way. Then this would be rather unfortunate, as it collides with the definition above for maps.

The same applies to [`compose(a::RelSeriesElem, b::RelSeriesElem)`](https://nemocas.github.io/AbstractAlgebra.jl/dev/series/#AbstractAlgebra.compose-Tuple{RelSeriesElem,%20RelSeriesElem})

I would suggest that we change the two `compose` methods to agree with the definition given for `maps`.  In addition, one could install methods for Julia's `∘` that corresponds to the "old" behavior.

However, this would be a serious breaking change -- serious because it would change behavior in a way that's not caught by e.g. type checking, so it can silently break existing code. Not sure how to deal with this best....

**Comment by thofma** [comment]
I agree that it should be consistent with the map interface. I guess one way to do it would be deprecate, remove and add again, which takes two/three breaking releases.

Any other ideas?

**Comment by fieker** [comment]
On Wed, Sep 22, 2021 at 11:35:34PM -0700, Tommy Hofmann wrote:
> I agree that it should be consistent with the map interface. I guess one way to do it would be deprecate, remove and add again, which takes two/three breaking releases.
> 
> Any other ideas?
> 
Can we afford to spread this over 2-3 breaking releases? At most I'd add
a warning, document it and do this in one release. We also have to
adjust our uses simultanously. I don't see how removing in between would
allow this.

**Comment by fingolfin** [comment]
More convenient for us would be to indeed "just change it" in one release, but that may badly mess up anybody outside of OSCAR who uses `compose`. I don't think that's good PR / advertisement for relying on us...

On the other hand, even with the plan suggested by @thofma, some people may miss it: if we put out the breaking `X` release now, and then N weeks later we release `X+1` which switches behavior, then anybody who doesn't check for AA  updates in the N+1 weeks will miss it. And of course for our own purposes, we'd like to minimize N, ideally to 0 or 1... So if we have a short waiting time between `X` and `X+1` we might as well do it in one go, as @fieker suggests

Independent of that, the concern about @thofma's approach raised by @fieker about migrating our other code simultaneous could be resolved by also adding a new `compose2` or `_compose` or whatever method which has the "correct" behavior, and use that. Once `compose` is redefined to the new "correct" behavior we can then (at any time, no need to hurry) switch code back to it. But of course all that is more work.

Yet another alternative is to simply not add back `compose` for an extended period, and only defining a `\circ` method for polynomials and power series ... or having a name like `compose2` more permanently, as ugly as it is... :-/.

**Comment by thofma** [comment]
We could change those two problematic methods to
```
compose(f::Poly, g::Poly; side)
```
with a required keyword argument (so that the user must specify the keyword argument). We can keep this as long as we want and then at some point (x months/years?) a default.

(And maybe at the same time implement the `_compose/compose_left/compose_right` for our internal use, so we can do the replacements more easily).

**Comment by fingolfin** [comment]
But doesn't that just postpone the problem? People won't use the keyword argument. So this only "helps" if we make it mandatory, at least for a time. Then I'd rather have `compose_left` and `compose_right` (although I am not sure anybody would be able to remember which is which ;-).

**Comment by thofma** [comment]
Hm? `compose(f, g)` will be giving an error `please use a keyword argument`. It is not optional.

**Comment by thofma** [comment]
Let's keep the discussion over at https://github.com/oscar-system/Oscar.jl/issues/690
