### ISSUE TITLE
interface to access exponents and coefficients of multivariate polynomials

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#103]
As @wbhart proposed in #99 there should be an interface (actually two) to access the coefficients and exponents of multivariate polynomials.

> In fact there will be two interfaces, one for polynomials which only define an iterator (because they are implemented as linked lists), and one for polynomials that have random access to terms (because they are implemented as an array).

Such an interface would allow to implement functions such as those in PR #102 more generically.

**Comment by wbhart** [comment]
This has been largely implemented now.
