### ISSUE TITLE
generating set for the trivial group

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#1030]
https://github.com/Nemocas/AbstractAlgebra.jl/blob/5d8d18ac49ea532f6fd536f52d6119bfb9e66cd3/src/generic/PermGroups.jl#L656

for now we return empty "set". should it be kept like this, or rather return `[one(G)]`?
@fingolfin

**Comment by fingolfin** [comment]
Fine as it is (we don't use `PermGroups` from AA in practice)
