### ISSUE TITLE
missing `hash` for `FreeModuleElem`?

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/AbstractAlgebra.jl#1033]
I ran into the following problem with the comparison of `Set`s of `FreeModuleElem` objects.
The reason seems to be that `hash` for `FreeModuleElem` objects is not correct.
```
julia> using AbstractAlgebra

julia> F = GF(2); n = 2; V = AbstractAlgebra.Generic.FreeModule(F, n); v = gen(V, 1)
(1, 0)

julia> w = 1*v
(1, 0)

julia> v == w
true

julia> Set([v]) == Set([w])
false

julia> hash(v)
0xf161660427344d08

julia> hash(w)
0xb5ca569f105efa4f
```

**Comment by fieker** [comment]
On Tue, Oct 05, 2021 at 06:02:40AM -0700, Thomas Breuer wrote:
> I ran into the following problem with the comparison of `Set`s of `FreeModuleElem` objects.
It's "just" not implemented....
