### ISSUE TITLE
julia keyword missing in deploydocs in docs/make.jl

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#104]
Executing `docs/make.jl` leads to the following warning:

WARNING: `julia` keyword to `Documenter.deploydocs()` not specified.
In the future `julia` will be a required keyword argument
instead of defaulting to `"nightly"`.

So I think one should add the julia keyword there. I am not sure which one to use. "nightly"? "0.6"?

**Comment by thofma** [comment]
It should be "0.6".

**Comment by heiderich** [comment]
I added this in pull request #105.
