### ISSUE TITLE
promote also for -?

### ISSUE THREAD

**Issue by fieker** [Nemocas/AbstractAlgebra.jl#1050]
`+(x::MatrixElem, y::MatrixElem) = +(promote(x, y)...)`
(and for `==`), but not for `-`:

```
julia> m1 = matrix(cyclotomic_field(4, cached = false)[1], 1, 1, [2])
julia> m2 = matrix(QQ, 1, 1, [2])
julia> m1 + m2
julia> m1 - m2
```
`+` works, `-` not. Is this intended?

**Comment by thofma** [comment]
I overlooked it. Will make a PR.
