### ISSUE TITLE
CompositeMap prob

### ISSUE THREAD

**Issue by fieker** [Nemocas/AbstractAlgebra.jl#1052]
I have
```
julia> w
Module homomorphism with
Domain: Subspace over Rational Field with 4 generators and no relations

Codomain: Vector space of dimension 16 over Rational Field

julia> e
Map from
Vector space of dimension 16 over Rational Field to Set of all homomorphisms from Vector space of dimension 4 over Rational Field to Vector space of dimension 4 over Rational Field defined by a julia-function with inverse
```
(they are complicated), but now the fun bit:
```
julia> codomain(w) == domain(e)
true
```
so composition *should* work? But
```ulia> typeof(e)
MapFromFunc{AbstractAlgebra.Generic.FreeModule{fmpq}, Hecke.MapParent}

julia> typeof(w)
AbstractAlgebra.Generic.ModuleHomomorphism{fmpq}
julia> supertype(typeof(w))
Map{AbstractAlgebra.FPModule{fmpq}, AbstractAlgebra.FPModuleHomomorphism, AbstractAlgebra.Generic.ModuleHomomorphism}

julia> supertype(typeof(e))
Map{AbstractAlgebra.Generic.FreeModule{fmpq}, Hecke.MapParent, Hecke.HeckeMap, MapFromFunc}
```
and composition does not work as the signature is `(::Map{A, B}, ::Map{B, C})```
and `AbstractAlgebra.FPModule{fmpq}` is not the same as `AbstractAlgebra.Generic.FreeModule{fmpq}`...

**Comment by thofma** [comment]
The type of `w` is missing the type of the codomain. I think this is violating the map interface? See https://nemocas.github.io/AbstractAlgebra.jl/latest/map/. Also I don't understand how this can work since `super(typeof(w))` does *not* contain the type of the domain, but just some abstract supertype (so it will never match the `compose` signature, since the domain/codomain types of `supertype(typeof(e))` is concrete). This also violates the map interface. Not sure how this is supposed to work.

**Comment by fieker** [comment]
well... it was written by the author of the interface. But as for "all" endomorphism types, s.th. like `End{C} <: Map{C, C}` would possibly satisfy the idea of the interface, but, as here, if C is also part of some larger type D, it seems to break. Don't know if this is a julia prob, that all possible supertypes should have been tried or not...

**Comment by thofma** [comment]
Since `Map{C, C}` is not a subtype of `Map{D, D}` given that `C <: D`, this cannot work as it is implemented now.

**Comment by fieker** [comment]
On Thu, Nov 11, 2021 at 04:40:21AM -0800, Tommy Hofmann wrote:
> Since `Map{C, C}` is not a subtype of `Map{D, D}` given that `C <: D`, this cannot work as it is implemented now.
> 
.... indeed....
