### ISSUE TITLE
Can't add constants to multivariate power series

### ISSUE THREAD

**Issue by joschmitt** [Nemocas/AbstractAlgebra.jl#1071]
I'm not sure whether I am reporting this at the right place because it does not happen with AbstractAlgebra on it's own. Anyways:
```
julia> using Nemo

Welcome to Nemo version 0.27.3

Nemo comes with absolutely no warranty whatsoever


julia> Qt, t = PowerSeriesRing(QQ, 10, ["t1", "t2"])
(Multivariate power series ring in t1, t2 over Rational Field, AbstractAlgebra.Generic.AbsMSeries{fmpq, fmpq_mpoly}[t1 + O(t2^10) + O(t1^10), t2 + O(t2^10) + O(t1^10)])

julia> t[1] + QQ(1)
ERROR: Cannot promote to common type
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] promote(x::AbstractAlgebra.Generic.AbsMSeries{fmpq, fmpq_mpoly}, y::fmpq)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/yXuIT/src/Rings.jl:56
 [3] +(x::AbstractAlgebra.Generic.AbsMSeries{fmpq, fmpq_mpoly}, y::fmpq)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/yXuIT/src/Rings.jl:66
 [4] top-level scope
   @ REPL[2]:1

```
If one does `using AbstractAlgebra` it works.

**Comment by wbhart** [comment]
This problem is not confined to multivariate power series:

```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring, x)

julia> S, y = PowerSeriesRing(R, 10, "y")
(Univariate power series ring in y over Univariate Polynomial Ring in x over Integer Ring, y + O(y^11))

julia> y + QQ(1)
ERROR: Cannot promote to common type
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] promote(x::AbstractAlgebra.Generic.RelSeries{fmpz_poly}, y::fmpq)
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Rings.jl:58
 [3] +(x::AbstractAlgebra.Generic.RelSeries{fmpz_poly}, y::fmpq)
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Rings.jl:68
 [4] top-level scope
   @ REPL[4]:1
```

The problem is that adding the necessary functions in AbstractAlgebra causes ambiguity warnings. Without them, this happens.

I don't know a solution that everyone is happy with.

**Comment by wbhart** [comment]
Actually, I had a typo in what I just wrote. This does work for generic univariate power series over some ring containing QQ, so I guess we can copy whatever worked there.

**Comment by thofma** [comment]
Probably missing a promote rule or something like that.

**Comment by wbhart** [comment]
It has this:

```
function promote_rule(::Type{AbsMSeries{T}}, ::Type{U}) where
                                           {T <: RingElement, U <: RingElement}
   promote_rule(T, U) == T ? AbsMSeries{T} : Union{}
end
```

Is this no longer sufficient?

**Comment by thofma** [comment]
I don't think it ever worked. It needs to be `AbsMSeriesElem` and the first argument must be `Type{ <:AbsMSeriesElem{T}}` (or `Type{U} ... where {U <: AbsMSeriesElem{T}}`, since once needs the `U` in the return type).

**Comment by wbhart** [comment]
Why AbsMSeriesElem? What other AbsMSeries types do we define?

But I think you are right on the other point. AbsMSeries is parameterised by two types and so it doesn't satisfy this signature. That's probably the issue.
