### ISSUE TITLE
Very serious bug

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#1077]
This is with Julia 1.6.2:

```
julia> using AbstractAlgebra

julia> S, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rationals, x)

julia> f = S(1//2)
1//2

julia> c = coeff(f, 0)
1//2

julia> d = -c
-1//2

julia> mul!(d, d, d)
1//4

julia> c
1//4
```

I have no idea what is going on here. It seems to only happen when I pull the rational value from the polynomial.

This is the cause of the first issue in #1075

**Comment by tthsqe12** [comment]
possibly the `d=-c`  makes a copy of the numerator but not the denominator? This is just the beginning of the ownership problems in julia...

**Comment by wbhart** [comment]
Looks to be the issue, yes.

**Comment by thofma** [comment]
It does not copy the denominator, so `Rational{BigInt}` is breaking all our assumptions :-(

**Comment by wbhart** [comment]
But it only seems to be a problem if c is pulled from the polynomial. If we just make a new Rational{BigInt} it works fine. So I still suspect the problem is ours, somehow.

**Comment by tthsqe12** [comment]
Huh? It is this:
```julia
julia> c = big(1)//big(2)
1//2

julia> d = -c
-1//2

julia> pointer_from_objref(d.den)
Ptr{Nothing} @0x00007f4b394c4630

julia> pointer_from_objref(c.den)
Ptr{Nothing} @0x00007f4b394c4630
```

**Comment by thofma** [comment]
```
julia> c = Rational{BigInt}(1, 2)
1//2

julia> d = -c
-1//2

julia> mul!(d, d, d)
1//4

julia> c
1//4
```

**Comment by wbhart** [comment]
Oh no, this is really not our fault, it is only a problem for Rational{BigInt}, not for Int:

```
julia> c = BigInt(1)//2
1//2

julia> d = -c
-1//2

julia> mul!(d, d, d)
1//4

julia> c
1//4
```

**Comment by wbhart** [comment]
Yeah this is VERY bad!!

**Comment by thofma** [comment]
It is in principle our fault, since we make assumptions about types that are not ours.

**Comment by tthsqe12** [comment]
I think we have to ban types that are not our own. Merge AA and Nemo and use fmpq for AA?

**Comment by wbhart** [comment]
I think to fix this, we have to rewrite all out mutating functions for QQ to not make assumptions about our ownership of the compnents of rational BigInts. That's going to be a big performance hit for AbstractAlgebra!

**Comment by wbhart** [comment]
The problem with ditching AbstractAlgebra for Julia types is that we'd have to rewrite a majority of our test code. We currently test all our generic code using Julia types only. If we merge AA and Nemo then our current test code for all the generic code would end up using the specialised Flint arithmetic and wouldn't actually test the generic code at all, e.g. a test of generic polynomials that current uses ZZ[x] would instead test Flint fmpz_poly's instead of Generic.Poly, leaving the latter untested.

So your approach, although not a bad one, would be a LOT of work @tthsqe12

**Comment by wbhart** [comment]
I wonder if we could demonstrate a bug in Julia itself using one of their mutating functions and then get them to accept it as a bug!?

**Comment by thofma** [comment]
The standpoint of the julia developers is that `BigInt` and co are immutable and the mutable bit is an implementation detail. Use at your own risk. There are some issues and comments on this (but I am lazy to find it).

**Comment by wbhart** [comment]
Yeah, there are no unsafe functions defined on Rational anything so that strategy isn't going to work either way. We have to fix this ourselves. And I only see the two approaches, neither of which is very much fun.

**Comment by wbhart** [comment]
And continuing to make assumptions about even BigInt is probably just sticking our head in the sand. Maybe merging AbstractAlgebra and Nemo is the only sensible long term option.

**Comment by thofma** [comment]
We can just do `mul!(c, a, b) = a * b` and be done with it. I don't think anyone will miss the performance.

**Comment by tthsqe12** [comment]
I think it safe to say no one using AA cares about the performance of Rational{Integer} (within a factor of 2 or 3), so just delete the unsafe methods and use generic `mul!(a,b,c)=b*c` and be done with it.

**Comment by wbhart** [comment]
I think the factor is dramatically more than 2 or 3 in the worst case. In fact, some of our existing test code might not actually finish in a reasonable time. But I'm willing to give it a go to see.

**Comment by tthsqe12** [comment]
How are we going to test out the fancy garbage collection if we are not creating and destroying objects every 100 cpu cycles?

**Comment by wbhart** [comment]
I will make a PR and we'll see how long the test code takes to FAIL ... err I mean PASS.

**Comment by wbhart** [comment]
I don't think any fancy GC gets used for GMP allocations.

**Comment by tthsqe12** [comment]
huh? A Rational{BigInt} is two pointers to mpz_structs, both of which are gc allocated.

**Comment by wbhart** [comment]
The structs are, yes. The internal GMP allocations are not.
