### ISSUE TITLE
Move parts of Integer.jl to an external library. 

### ISSUE THREAD

**Issue by oscardssmith** [Nemocas/AbstractAlgebra.jl#1097]
I'm not 100% sure if this is a good place to post this, but I was wondering what people's opinions are on moving part of this file to an external library. The theory is that some of the functions (mainly `iroot`, `ispower`, and `isprobable_prime`) are useful outside the Nemo ecosystem, so it would be nice if other libraries (like Primes.jl) didn't have to reimpliment them (`AbstractAlgebra` is a pretty heavy library to import for 3 relatively simple functions). If people like this idea, I would be happy to create the repository to host these (either under JuliaMath or Nemocas).

**Comment by thofma** [comment]
I don't think there is much interest in doing this on the maintainers part. It just adds another package with which updates/changes/renaming/documentation have to be coordinated etc. Feel free to copy the source in accordance with whatever rules the license impose :)

**Comment by fieker** [comment]
On Sat, Jan 08, 2022 at 04:53:25AM -0800, Tommy Hofmann wrote:
> I don't think there is much interest in doing this on the maintainers part. It just adds another package with which updates/changes/renaming/documentation have to be coordinated etc. Feel free to copy the source in accordance with whatever rules the license impose :)
> 
Just to mention: the functions are written in C, thus cannot ripped
out...
