### ISSUE TITLE
isunit for univariate and multivariate polynomials is incorrect over Z/nZ

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#11]
It's not true that a polynomial is a unit in its polynomial ring iff its constant coefficient is a unit. This has been assumed in the current implementation. For example, it isn't true over Z/nZ.

As it is actually quite expensive in general to compute this, we should look carefully where isunit has been used in generic code and remove references to it where this is not precisely what is required.

**Comment by thofma** [comment]
This is just https://github.com/Nemocas/Nemo.jl/issues/323, right?

**Comment by wbhart** [comment]
Yes. We'll need to copy all the relevant ones over to here eventually. This one just stands out as being a major error that should be corrected sooner rather than later. So I'm listing it here so that it doesn't get forgotten.

**Comment by fieker** [comment]
Specifically for Z/nZ we have much more in Hecke.jl - it might have to
move across the divide...

**Comment by wbhart** [comment]
We should implement an isunit_constant function to replace the existing isunit function that is used often in library code (where we only care if we have a constant polynomial that is a unit for example, instead of actually needing a unit).

**Comment by fingolfin** [comment]
Nemo actually defines a method `is_unit(f::T) where {T<:Union{ZZModPolyRingElem,zzModPolyRingElem}}` to fix this. See https://github.com/Nemocas/Nemo.jl/issues/323 for some thoughts on how to address this more generally.
