### ISSUE TITLE
number of variables involved in MPoly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#110]
Is there an easy way to obtain the number of variables actually involved in a multivariate polynomial of type `MPoly`? The function `nvars` reported the number of variables of the polynomial ring the polynome belongs to.

**Comment by wbhart** [comment]
No, but this should/will be changed. I think we already accepted a pull
request to only allow nvars to apply to the ring (or one was proposed).

**Comment by heiderich** [comment]
Actually I think it might also be helpful to have a function that returns all variables appearing in a polynomial. I thought about returning it as a Set rather than an Array. While testing this, I encountered #111.

**Comment by wbhart** [comment]
I am not super keen to use sets for this. Whilst it makes for a nice syntax
for checking whether something is in the set, a more programmatically
relevant problem might be to iterate over those variables. Sets aren't the
best structure for that.

**Comment by heiderich** [comment]
If returning them as an Array, I think we should specify the order of its elements. How can the generators be compared? I guess one could use the monomial_isless functions, but they do not take MPolys as arguments. Is there already a way to easily compare monomials (the actual MPoly objects)?

**Comment by wbhart** [comment]
No, there is no interface for dealing with this yet, as there is no
interface for dealing with monomials, as currently, things are not
implemented correctly (terms and monomials are both stored in the wrong
order compared to the way it is done in Flint).

But in general, I agree they should be returned in an order that doesn't
surprise the user, e.g. the order the user originally specified.

**Comment by heiderich** [comment]
I could return them as an array in arbitrary order for the moment and we could change the order once we can compare monomials. What do you think about that?

**Comment by wbhart** [comment]
It should be possible to return them in the order they are currently stored
in exponents, and then check this is the same as the order returned by the
gens function (rather than the reverse order).

**Comment by heiderich** [comment]
See PR #114. I however do not check whether the order is the same as the one returned by the gens function. What should happen if this is not the case?

**Comment by wbhart** [comment]
I don't mean the code should check this. I just mean that the user is
likely going to expect that, and it shouldn't be hard for us to try a few
examples and check that this is actually the case.

But let me look at your code first. Things are slightly hectic at the
moment, so it may take me a few days.
