### ISSUE TITLE
missing `ordering` function causes trouble

### ISSUE THREAD

**Issue by HechtiDerLachs** [Nemocas/AbstractAlgebra.jl#1105]
```julia
R, (x,y) = QQ["x", "y"]
R_ext, _ = PolynomialRing(R, ["u", "v"])
S, (u,v) = grade(R_ext, [1,1])
ordering(S)
```
throws an error. This is a problem, because the function is required to be there in order to fill in the default argument in https://github.com/Nemocas/AbstractAlgebra.jl/blob/307d12a5e1d52253bed3891f8f373ee2570cc918/src/MPoly.jl#L1040
and this is called when I try to evaluate a polynomial/map its coefficients.

**Comment by thofma** [comment]
I guess there is a `ordering(R::MPolyRing_dec) = ordering(R.R)` missing.

**Comment by HechtiDerLachs** [comment]
> I guess there is a `ordering(R::MPolyRing_dec) = ordering(R.R)` missing.

Probably. I can use a manual `ordering(S::MPolyRing_dec) = :lex` as a dirty workaround at it seems to work fine. But the developers should look into this. Can't we just mention them here, or do I really have to carry over this issue to Oscar?

**Comment by thofma** [comment]
Who is them? My suggestion amounts to replacing `:lex` by `ordering(R.R)` in your code.

**Comment by HechtiDerLachs** [comment]
> Who is them? My suggestion amounts to replacing `:lex` by `ordering(S.R)` in your code.

Yes, that was my question: Who implemented the graded rings and knows how to solve this correctly. Of course, I could add that line of code in one of my files, but I guess it would be better if it was in the correct place.

**Comment by wbhart** [comment]
Graded rings are an Oscar.jl thing I think, not an AbstractAlgebra one. Perhaps @thofma ends up looking at it either way, but maybe the author of graded rings is more likely to see it over there?

**Comment by fieker** [comment]
This is pure Oscar and should be there. Thus I am closing this issue.
