### ISSUE TITLE
total degree of an object of type MPoly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#112]
I would like to have a function that computes the total degree of an MPoly. Would you welcome such an addition?

**Comment by wbhart** [comment]
Yes, certainly.

>

**Comment by heiderich** [comment]
See pull request #113. Note that again I had to make sure to get the right subset of f.exps. This gives me an opportunity to remind you #103. A function that would return the exponents in a well-defined form could save us from re-implementing it everywhere.
