### ISSUE TITLE
Test failure in Generic.Mat.Nullspace

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#1120]
Max Horn reports:

Huh, test failure:

```
Generic.Mat.nullspace: Error During Test at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/test/generic/Matrix-test.jl:2490
  Got exception outside of a @test
  9626734 is not invertible in Residue ring of Integers modulo 200250077
  Stacktrace:
    [1] inv(a::AbstractAlgebra.Generic.Res{BigInt})
      @ AbstractAlgebra ~/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Residue.jl:309
    [2] inv
      @ ~/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/AbstractAlgebra.jl:90 [inlined]
    [3] fflu!(P::Perm{Int64}, A::AbstractAlgebra.Generic.MatSpaceElem{AbstractAlgebra.Generic.Res{BigInt}})
      @ AbstractAlgebra ~/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Matrix.jl:1509
    [4] rank(M::AbstractAlgebra.Generic.MatSpaceElem{AbstractAlgebra.Generic.Res{BigInt}})
      @ AbstractAlgebra ~/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Matrix.jl:2275
...
```

Indeed, gcd(200250077, 9626734) == 10007. I am guessing this is a randomized failure and will go away when restarting the tests, but there seems to be an underlying bug here.

Indeed fflu! calls inv(A[r, c]) without any check whether that element is invertible, the code seems to just assume that all non-zero elements are invertible. This is of course wrong for a general ResElem...

**Comment by wbhart** [comment]
The test is allowed to fail (very rarely) as it is testing that the algorithm works for composite moduli. This will almost always succeed in practice for sufficiently large factors and will error when it cannot succeed and not give an incorrect answer.

Given it has been years without seeing such a failure, I think this is not urgent for now.

**Comment by fingolfin** [comment]
I think we resolved this some time ago.
