### ISSUE TITLE
print plus sign before a negative coefficient in Nemo.ArbField that is printed using brackets

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#116]
After

```
using Nemo; using AbstractAlgebra
R,varsR = PolynomialRing(Nemo.ArbField(64),["x","y"]); x,y=varsR

```
the output of 

`x + Nemo.ArbField(64)(-sqrt(2)) * y`

is

`x[-1.4142135623730951455 +/- 2.54e-20]*y`

I think a plus should be printed between `x` and the coefficient of `y`, because I would interpret the current output to be a monomial.

**Comment by wbhart** [comment]
This could just be because of an incorrectly defined isnegative(::arb)  or
show_minus_one(::arb) function.

**Comment by heiderich** [comment]
If I modify `isnegative(x::arb)` to return `false`, a plus sign is printed, as it should be. However this is not what the name of the function suggests. @sebasguts suggested in https://github.com/oscar-system/Singular.jl/issues/50 that this function should be renamed to something like `displayedwithminusinfront`. Is this the only intention of this function? Then I would agree.

Should we still hard-code

`isnegative(::Type{Nemo.arb}) = false`

for the time being?

**Comment by wbhart** [comment]
On Thu, 19 Jul 2018 at 16:58, Florian Heiderich <notifications@github.com>
wrote:

> If I modify isnegative(x::arb) to return false, a plus sign is printed,
> as it should be. However this is not what the name of the function
> suggests. @sebasguts <https://github.com/sebasguts> suggested in
> oscar-system/Singular.jl#50
> <https://github.com/oscar-system/Singular.jl/issues/50> that this
> function should be renamed to something like displayedwithminusinfront.
> Is this the only intention of this function?
>

Yes, absolutely. It has no other purpose.


> Then I would agree.
>
> Should we still hard-code
>
> isnegative(::Type{Nemo.arb}) = false
>
> for the time being?
>
I assume you are asking whether the function should be called isnegative,
for now. Yes, until we change it globally, it has to be called that.

We will always need this function defined, and it was a bug that it wasn't
defined for Nemo.arb. The name the function should have is unrelated. It
was a poor choice on my part and should be changed.

**Comment by heiderich** [comment]
No. The function already exists:

```
function isnegative(x::arb)
   return Bool(ccall((:arb_is_negative, :libarb), Cint, (Ref{arb},), x))                                                                
end

```

The question was whether we want it to change it in order to always return `false`. I think this would be an improvement over the current situation. In general I think one should also take into account whether the number will be printed with square brackets or not.

**Comment by thofma** [comment]
No, that is not a good idea. There should be a separate function for printing. The `isnegative` methods for arb is something mathematical.

**Comment by heiderich** [comment]
As I understood @wbhart in his last comment, the function `isnegative` should rather be called something like `displayedwithminusinfront` and that its only purpose is what this new name suggests. The last comment of @thofma seems to be in contradiction to this.

**Comment by wbhart** [comment]
@thofma might be right here.

When talking about printing, there is a function "isnegative" used all
through AbstractAlgebra, Nemo, etc., that is used for printing. It is
poorly named, and has no other reason for existence. If it is not there,
printing breaks.

But in Arb (the C library), there probably is a function "isnegative" which
determines whether a given arb is negative (i.e. whether the entire ball
lies below zero). In that sense, it is doing something mathematical and
should be retained for that purpose. It has nothing to do with printing.
It's a coincidence that the name is the same as a function we already had
for another purpose.

I was simply unaware of this conflict, and it probably explains your
original troubles with printing arbs.

I haven't checked all this out, but it should be easy enough to determine
if this is what has happened and to make adjustments accordingly.

**Comment by heiderich** [comment]
I see. Would the following be a suitable solution?

1. Rename `isnegative` to `displayedwithminusinfront` (or something similar) everywhere (in AbstractAlgebra, Nemo, Singular) expect the one in Nemo.arb.
2. Introduce a function `displayedwithminusinfront` in Nemo.arb that returns `false` for the moment being. (Should later on depend on whether the output is printed with brackets or not and probably also on the result of `isnegative`).

How about the name `displayedwithminusinfront`? This was the suggestion of @sebasguts. I got the impression that the affected packages often use underlines so separate words. (Is there any agreement on the coding style?) How about `displayed_with_minus_in_front`?

**Comment by thofma** [comment]
When I wrapped `arb`, I forgot about the purpose of `isnegative` to help with printing.

The solution of @heiderich sounds fine to me. I would go with `displayed_with_minus_in_front`.

**Comment by heiderich** [comment]
See PR #127 and https://github.com/Nemocas/Nemo.jl/pull/448.
