### ISSUE TITLE
`gcd` for vectors of elements 

### ISSUE THREAD

**Issue by lgoe-ac** [Nemocas/AbstractAlgebra.jl#1165]
Similarly to the implementations in `Base` for vectors, e.g. `gcd(abc::AbstractArray{<:Integer}) in Base at intfuncs.jl:135`, I would like the euclidean Ring interface to be extended by a method `gcd(::AbstractArray{<:T}) where T <: RingElem` with a generic implementation using `reduce` and `gcd(f::T, g::T) where T <: RingElem`.

This is not a large effort for this package but allows for some convenience and readability in downstream code.

If my request gets approved, I can do the needed changes to the interface.

**Comment by thofma** [comment]
I would be in favour of it. We already have it for `fmpz`, so it makes only sense to add it for `RingElem`. I would also add the `gcd(x::T, y::T, z::T...)` vararg version.

**Comment by wbhart** [comment]
I don't see any problem with the suggestion. I'd say go ahead, and thanks for volunteering to make the changes!
