### ISSUE TITLE
Calculate rank of matrix over GF(2)

### ISSUE THREAD

**Issue by jisutich** [Nemocas/AbstractAlgebra.jl#1168]
Hi,

I am new to this package. I want to calculate the rank of a matrix defined over field GF(2) = {0,1}. How to construct such a matrix and get the rank?

Thanks.

**Comment by fieker** [comment]
On Sat, May 14, 2022 at 06:49:31PM -0700, Xiaozhou Feng wrote:
> Hi,
> 
> I am new to this package. I want to calculate the rank of a matrix defined over field GF(2) = {0,1}. How to construct such a matrix and get the rank?
> 
> Thanks.

julia> using AbstractAlgebra

julia> m = matrix(GF(2), 2, 2, [1,2,3,4])
[1   0]
[1   0]

julia> rank(ans)
1

However, for (much) larger matrices you're better off using Nemo

**Comment by jisutich** [comment]
Thank you. I will try Nemo for large matrix.
