### ISSUE TITLE
Inconsistent behaviour of double slash operator (//)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#1170]
The following appears to be inconsistent:

```
julia> using Nemo

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> typeof(x//1)
AbstractAlgebra.Generic.Frac{fmpq_poly}

julia> R, (x, ) = PolynomialRing(QQ, ["x"])
(Multivariate Polynomial Ring in x over Rational Field, fmpq_mpoly[x])

julia> typeof(x//1)
fmpq_mpoly
```

Did we recently decide that we want the double slash operator to not be for creating fractions? It now seems slightly inconvenient to me to not be able to use it for such given that using the `Frac` inner constructor will result in an object without a parent, which means there is no easy way to construct such a fraction.

**Comment by wbhart** [comment]
Which one? The second is a bug?

**Comment by thofma** [comment]
Yeah, it is surprising to me.

**Comment by wbhart** [comment]
Ah, I knew we had discussed this recently, but couldn't remember the decision we reached.

But I have now found the ticket (where we decided overwhelmingly in favour of precisely what we have decided here):

https://github.com/Nemocas/Nemo.jl/issues/1281
