### ISSUE TITLE
submatrices with respect to given lists of row and column indices

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#120]
I would like to propose a second form of the function `AbstractAlgebra.Generic.sub` that takes as input a matrix `A`, a list of row indices `I` (integers) and column indices `J` and returns the submatrix B of A given by B_{i,j} = A_{I[i], J[j]}.

The currently existing function `sub(M::AbstractAlgebra.MatElem, r1::Int, c1::Int, r2::Int, c2::Int)` would be the special case where I=[i for i=r1:r2] and J=[j for j=c1:c2].

**Comment by wbhart** [comment]
That would not be possible without copying the data. I am not sure if that
is the current behaviour of sub. @thofma might have some insight into this.

**Comment by wbhart** [comment]
Actually, I might have spoken too hastily here. If there was a new type for
such submatrices, it could overload its own setindex! and getindex to look
up which entry in the original matrix to modify.

>
There are limitations on what we can do, however, due to the fact that our
matrices are (necessarily) different to Julia matrices.

**Comment by wbhart** [comment]
By the way, you can do the following:

N = matrix(ZZ, 3, 3, [1, 2, 3, 4, 5, 6, 7, 8, 9])

P = matrix(ZZ, 2, 2, [N[i, j] for i in [1, 3] for j in [2, 3]])

>

**Comment by heiderich** [comment]
Yes, of course. This is merely a convenience function. 

The function `sub(M::AbstractAlgebra.MatElem, rows::UnitRange{Int}, cols::UnitRange{Int})`, which is called by `sub(M::AbstractAlgebra.MatElem, r1::Int, c1::Int, r2::Int, c2::Int)` uses deepcopy for the coefficients. I thought about doing just the same.

**Comment by wbhart** [comment]
Ok, I wasn't aware of that. If Tommy is ok with it, then sure, go ahead.

**Comment by thofma** [comment]
Makes sense to add it (in AbstractAlgebra).

One minor downside is that we won't have a corresponding version for `view` but this should not stop us.

**Comment by heiderich** [comment]
See #121.
