### ISSUE TITLE
minors of a matrix

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#122]
I would like to suggest a function that takes a matrix as input and returns its minors. In fact, I have an implementation, but for convenience I used the function `subsets` from `IterTools.jl`.

Is such a function welcome? Is a dependency of `IterTools.jl` acceptable?

**Comment by thofma** [comment]
Such a function is welcome, but we try to have no dependency on external packages.

But maybe we can throw something together with the things @kalmarek did.

**Comment by heiderich** [comment]
Could you be more specific? Maybe one could use `AllParts`. Unfortunately it seems not to be documented.

**Comment by thofma** [comment]
I don't know myself. I was hoping that @kalmarek would tell us if it is possible.

**Comment by heiderich** [comment]
Forget my last comment concerning `AllParts`. See pull request #123 instead. It is self-contained.

**Comment by kalmarek** [comment]
The documentation of `AllParts` (and much more) is just around the corner (already written, but not yet committed)
```julia
doc"""
    AllParts(n::Int)
> Return an iterator over all integer `Partition`s of `n`.
> Partitions are produced in ascending order according to RuleAsc (Algorithm 3.1) from
>
> Jerome Kelleher and Barry O’Sullivan,
> *Generating All Partitions: A Comparison Of Two Encodings*
> ArXiv:0909.2331
>
> See also `Combinatorics.partitions(1:n)`.

# Examples
``jldoctest
julia> ap = AllParts(5);

julia> collect(ap)
7-element Array{AbstractAlgebra.Generic.Partition,1}:
 1₅
 2₁1₃
 3₁1₂
 2₂1₁
 4₁1₁
 3₁2₁
 5₁
``
"""
struct AllParts
    n::Int
    part::Vector{Int}
    AllParts(n::Integer) = new(n, zeros(Int,n))
end
```
