### ISSUE TITLE
order of parts of `Generic.Partition`

### ISSUE THREAD

**Issue by lgoe-ac** [Nemocas/AbstractAlgebra.jl#1235]
When first starting to use the generic implementation of partitions `Generic.Partition`, I was very confused about when the constructor reorders the parts and when not.
Currently, it checks if its input is increasing and if not sorts it decreasingly. This behavior seems quite unintuitive to me.

The line in question is
[src/generic/GenericTypes.jl#L98](https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/GenericTypes.jl#L98)

Since the parts should be sorted decreasingly as said by the documentation, I would suggest replacing the line by
```julia        
all(i-> part[i-1] >= part[i], 2:length(part)) || sort!(part, rev=true)
```

**Comment by thofma** [comment]
@kalmarek do you remember the reasoning?

**Comment by kalmarek** [comment]
not really; but here it seems that I put `all` when I meant `any` :P

I actually suggest
```julia
issorted(part, rev=true) || sort!(part, rev=true)
```
I think this does convey the intention clearly ;)

**Comment by kalmarek** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1236
