### ISSUE TITLE
Vectors are (sometimes) treated as Row vectors

### ISSUE THREAD

**Issue by SyxP** [Nemocas/AbstractAlgebra.jl#1237]
Observe the following code.

```julia
R, x = FiniteField(7, 3,  "x")
R.([1, 2])*R[1 2;3 4]
[1, 2]*[1 2;3 4] # Dimension Mismatch
```

The cause is here:
https://github.com/Nemocas/AbstractAlgebra.jl/blob/d67e47a37688b69772880292a1f28e63ec870660/src/Matrix.jl#L946

with a fairly simple fix. However, I am unsure how much of the functionality this depends on and it is a breaking change. Moreover, to properly support this might need a support of adjoint types.

**Comment by thofma** [comment]
Yes, this is on purpose. If `x isa Vector`, for convenience we allow `x * A` and `A * x` if the dimensions fit.

**Comment by tthsqe12** [comment]
Everyone knows how to dot `vector . matrix` to get a `vector` but julia chokes here because it considers vectors as n-by-1 matrices, whereas the 'proper' view views vectors as rank 1 tensors and matrices as rank 2 tensors. Here, tensor = multidimensional array.

**Comment by thofma** [comment]
I will close this issue for now.
