### ISSUE TITLE
Ring not exported

### ISSUE THREAD

**Issue by lgoettgens** [Nemocas/AbstractAlgebra.jl#1309]
In `src/AbstractAlgebra.jl`, for almost all types, both the type and its element type get exported.
Is there a good reason, why this is not done for `Ring`? In this case, only the element type gets exported [here](https://github.com/Nemocas/AbstractAlgebra.jl/blob/9b6e7e10894df8ad55d6c7cea99f24d0a92a031e/src/AbstractAlgebra.jl#L269).

**Comment by thofma** [comment]
Not, feel free to add it.
