### ISSUE TITLE
*(::MatElem, p::perm)

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#135]
I finally updated my old code to Nemo/AbstractAlgebra split and found that for `p::perm`, `A::MatElem` the standard action `p*A*inv(p)` no longer works, i.e. the method in the title is not (no longer?) available

```julia
doc"""
    *(x::AbstractAlgebra.MatElem, P::Generic.perm)
> Apply the pemutation $P$ to the columns of the matrix $x$ and return the result.
"""
function *(x::AbstractAlgebra.MatElem, P::Generic.perm)
   z = similar(x)
   m = rows(x)
   n = cols(x)
   for i = 1:m
      for j = 1:n
         z[i, j] = x[i, P[j]]
      end
   end
   return z
end
```
should I open pull, or there were some reasons for removal?

**Comment by wbhart** [comment]
I believe it was removed deliberately, as permutations are applied on the left only.

**Comment by thofma** [comment]
Indeed, we removed it. With the definition above we have `(A * p) * q != A * (p * q)`, which is quite confusing. In particular when writing `A * p * q`.

**Comment by kalmarek** [comment]
yeah, with the above definition `A*(p*q)` is `(A*q)*p`, which is what one should expect, but only after spending a moment to think about it ;)

One way to make it an action (i.e. associative) is to act via `inv(p)`, i.e. `z[i, P[j]] = x[i, j]`, but then the conjugation action looks somewhat strange: `p*A*p`, 

I will leave it to my own code/
