### ISSUE TITLE
More renaming

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#138]
Base changed the following names:
`lufact` is now `lu` and similar for `lufact!`. And `trace` is now called `tr`. Should we follow?

**Comment by wbhart** [comment]
I guess so, but I have no burning desire to change too many more of these names in seemingly arbitrary ways. I think if this keeps up after 1.0 we just ignore further changes. None of them make any sense.

**Comment by thofma** [comment]
Agree with what you say.

**Comment by kalmarek** [comment]
I think that the idea is that 1.0 brings a lot of changes (including renames), but all 1.* should be backward compatible to 1.0, so I wouldn't expect any changes in names until 2.0

**Comment by wbhart** [comment]
I honestly doubt that renaming of functions will remain off-limits. As soon as people discovered they've named things badly, exceptions will be made. But we will see.
