### ISSUE TITLE
`number_field(a::Poly, s::Symbol, t="\$") ` constructor ignores both `s` and `t`

### ISSUE THREAD

**Issue by mgkurtz** [Nemocas/AbstractAlgebra.jl#1485]
This function seems strange. The `t` seems especially strange.

https://github.com/Nemocas/AbstractAlgebra.jl/blob/93be9a0352dfa30c3400b9cb1391f36942034452/src/generic/NumberField.jl#L33-L44

**Comment by fieker** [comment]
On Thu, Nov 02, 2023 at 02:51:47AM -0700, Markus Kurtz wrote:
> This function seems strange. The `t` seems especially strange.
> 
> https://github.com/Nemocas/AbstractAlgebra.jl/blob/93be9a0352dfa30c3400b9cb1391f36942034452/src/generic/NumberField.jl#L33-L44
> 
You can forget about almost nay strange pattern in AA number fields:
they are not used at all by Hecke/ Oscar and are there to provide rings/
fields for testing in AA internally. Similar to the finite fields in
there....

**Comment by thofma** [comment]
They should be purged

**Comment by mgkurtz** [comment]
> They should be purged

If “they” means the argument `t` and the variable name `s` this is part of the cleanup in #1487.

**Comment by fieker** [comment]
On Thu, Nov 02, 2023 at 06:16:32PM -0700, Markus Kurtz wrote:
> > They should be purged
> 
> If “they” means the argument `t` and the variable name `s` this is part of the cleanup in #1487.
> 
They means the entire data type, and all functions and every meaning.
The only reason for them to exist is to have test rings.
