### ISSUE TITLE
identity_matrix and matrix are ambiguous

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#149]
I'm currently creating a MatrixAlgebra type, but identity_matrix and matrix are now ambiguous. Should they create the element of the MatrixAlgebra or the element of the MatrixSpace.

I actually don't see an easy fix for this.

**Comment by thofma** [comment]
I suggest keeping things as they are. Use one and zero on the algebra if you want elements of the algebra.

**Comment by thofma** [comment]
Sorry, I forgot to mention the matrix function, which is the more interesting. Even in this case I would argue that the default matrix constructor should yield elements of MatrixSpace. If you want algebra elements use A([...]) where A is the parent.

**Comment by wbhart** [comment]
Won't fix.
