### ISSUE TITLE
Missing `evaluate` for matrix

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/AbstractAlgebra.jl#1497]
I think I should be able to do this:
```julia
julia> P, x = PolynomialRing(QQ, 2)
(Multivariate polynomial ring in 2 variables over QQ, QQMPolyRingElem[x1, x2])

julia> F = FractionField(P)
Fraction field
  of multivariate polynomial ring in 2 variables over QQ

julia> M = MatrixSpace(F, 2, 2)
Matrix space of 2 rows and 2 columns
  over fraction field of multivariate polynomial ring

julia> m = M()
[0   0]
[0   0]

julia> m[1, 1] = x[1]^2 + x[2]
x1^2 + x2

julia> m
[x1^2 + x2   0]
[        0   0]

julia> evaluate(m, [1; 2])
```
However, no method `evaluate` exists for this.

**Comment by thofma** [comment]
```julia
julia> map(p -> evaluate(p, [1, 2]), m)
[3   0]
[0   0]
```
I am a bit reluctant to add it, since we usually don't add extra methods, if it is just a (simple) application of `map`.

**Comment by fieker** [comment]
I agree with Tommy - as this is yet another example of induced actions...what about a univariate polynomial ring  over your bivariate one: should evaluate then work as well and apply to the coeffs?

**Comment by albinahlback** [comment]
Alright, sounds reasonable!
