### ISSUE TITLE
How to convert an univariate polynomial to a multivariate polynomial?

### ISSUE THREAD

**Issue by nsajko** [Nemocas/AbstractAlgebra.jl#1503]
Basically the opposite of #220. I've got a univariate polynomial over a multivariate polynomial ring, and I'd like to convert it into a multivariate polynomial ring with one more variable. How to do this? The use case is that `minpoly` and `charpoly` return univariate polynomials, but I want a multivariate polynomial.

Example, in case it's not clear what I'm talking about:

```julia-repl
julia> using AbstractAlgebra

julia> xy_ring, (x, y) = QQ["x", "y"]
(Multivariate polynomial ring in 2 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y])

julia> _, z = polynomial_ring(xy_ring, :z)
(Univariate polynomial ring in z over multivariate polynomial ring, z)

julia> x*z
x*z

julia> typeof(ans)
AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.MPoly{Rational{BigInt}}}
```

So `x*z` is actually a univariate polynomial, according to AA's type system, and my question is **how to convert it into a multivariate polynomial**?

**Comment by nsajko** [comment]
Figured it out:

```julia-repl
julia> using AbstractAlgebra

julia> xyz_ring, (x, y, z) = QQ["x", "y", "z"]
(Multivariate polynomial ring in 3 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y, z])

julia> _, z_ = polynomial_ring(xyz_ring, :z)
(Univariate polynomial ring in z over multivariate polynomial ring, z)

julia> (x*z_)(z)
x*z

julia> typeof(ans)
AbstractAlgebra.Generic.MPoly{Rational{BigInt}}
```

Maybe there should be an example like this in the docs?

**Comment by thofma** [comment]
Where would you put in the docs?
