### ISSUE TITLE
`vars` for fractions of multivariate polynomials

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/AbstractAlgebra.jl#1515]
Currently, `vars` returns the variables present in a given multivariate polynomial. It will be useful for us if `vars` also worked in a similar way for rational functions. This originally came up here: https://github.com/SciML/StructuralIdentifiability.jl/pull/253

If you consider this functionality worth adding, then I can make a PR.

**Comment by fingolfin** [comment]
Sure, go ahead with that PR
