### ISSUE TITLE
ishessenberg does not check for square matrix

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#152]
Currently, we can only put a matrix in Hessenberg form if it is square. But we allow non-square matrices in ishessenberg. I'm just wondering if it was intentional, and whether we should return false or an exception if it is not square.

**Comment by wbhart** [comment]
Same question applies to similarity!, which applies a similarity transform. The code seems to only work for square matrices, and the docs seem to suggest we assume that. I'm wondering if there is a reason we don't test for squareness there, or whether I should just add that in.

**Comment by thofma** [comment]
I think returning `false` in `ishessenberg` sounds like a good option.

Regarding `similarity!`, I don't know what it is doing, but usually we don't check arguments for unsafe functions (exception is `setindex!`).

**Comment by wbhart** [comment]
Ok, thanks.
