### ISSUE TITLE
[Bug] `view` only likes `UnitRange` even though it accepts other arguments

### ISSUE THREAD

**Issue by StevellM** [Nemocas/AbstractAlgebra.jl#1524]
I wanted to use `view` to compute some minors of my matrices. However, it seems that the implementation for `AbstractAlgebra` matrices does only work for unit range

```
julia> M = identity_matrix(QQ, 3)
[1   0   0]
[0   1   0]
[0   0   1]

julia> view(M, 1:3, 1:3)
[1   0   0]
[0   1   0]
[0   0   1]

julia> view(M, 1:3, [1,2,3])
ERROR: StackOverflowError:
Stacktrace:
 [1] view(M::QQMatrix, rows::UnitRange{Int64}, cols::Vector{Int64}) (repeats 79984 times)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:410

julia> view(M, [1,2,3], [1,2,3])
ERROR: StackOverflowError:
Stacktrace:
 [1] view(M::QQMatrix, rows::Vector{Int64}, cols::Vector{Int64})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:407
 [2] view(M::QQMatrix, rows::Vector{Int64}, cols::Vector{Int64}) (repeats 79983 times)
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:410
``` 
On the other side, the initial julia implementation seems to work for any kind of arguments
```
julia> collect(M)
3×3 Matrix{QQFieldElem}:
 1  0  0
 0  1  0
 0  0  1

julia> view(ans, 1:3, [1,2,3])
3×3 view(::Matrix{QQFieldElem}, 1:3, [1, 2, 3]) with eltype QQFieldElem:
 1  0  0
 0  1  0
 0  0  1
```

**Comment by fieker** [comment]
The data modell for Nemo would allow random row ranges, but cannot deal
with disjoint columns

**Comment by fieker** [comment]
On Sat, Dec 09, 2023 at 06:06:00AM -0800, Stevell Muller wrote:
> I wanted to use `view` to compute some minors of my matrices. However, it seems that the implementation for `AbstractAlgebra` matrices does only work for unit range
> 
> ```
> julia> M = identity_matrix(QQ, 3)
> [1   0   0]
> [0   1   0]
> [0   0   1]
> 
> julia> view(M, 1:3, 1:3)
> [1   0   0]
> [0   1   0]
> [0   0   1]
> 
> julia> view(M, 1:3, [1,2,3])
> ERROR: StackOverflowError:
> Stacktrace:
>  [1] view(M::QQMatrix, rows::UnitRange{Int64}, cols::Vector{Int64}) (repeats 79984 times)
>    @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:410
> 
> julia> view(M, [1,2,3], [1,2,3])
> ERROR: StackOverflowError:
> Stacktrace:
>  [1] view(M::QQMatrix, rows::Vector{Int64}, cols::Vector{Int64})
>    @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:407
>  [2] view(M::QQMatrix, rows::Vector{Int64}, cols::Vector{Int64}) (repeats 79983 times)
>    @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/dsta0/src/Matrix.jl:410
> ``` 
> On the other side, the initial julia implementation seems to work for any kind of arguments
> ```
> julia> collect(M)
> 3×3 Matrix{QQFieldElem}:
>  1  0  0
>  0  1  0
>  0  0  1
> 
> julia> view(ans, 1:3, [1,2,3])
> 3×3 view(::Matrix{QQFieldElem}, 1:3, [1, 2, 3]) with eltype QQFieldElem:
>  1  0  0
>  0  1  0
>  0  0  1
> ```
> 
the underlying data structure does not support unconnected column randes
for any matrix type on flint, unconnected row ranges can/ could be
supported.

Generic matrices could also support this, however for ZZMatrix and
QQMatrix this is not an option, thus view cannot be used...

If you switch to Matrix{QQFieldElem} you're also using julia's built-in
linear algebra which will be much slower for larger input (let alone
crashing in ZZRingElem)

Sorry.

**Comment by StevellM** [comment]
Ok so in the end this is just not possible for design decision ? I could solve my issue by re-creating a proper matrix instead of using `view`. So if it is not a bug and we cannot do anything about it, we can close the issue.

**Comment by fieker** [comment]
View does not work, but slices do: A[a,b] for a and b random vectors does
work

**Comment by fieker** [comment]
On Mon, Dec 11, 2023 at 11:37:04AM -0800, Stevell Muller wrote:
> Ok so in the end this is just not possible for design decision ? I could solve my issue by re-creating a proper matrix instead of using `view`. So if it is not a bug and we cannot do anything about it, we can close the issue.
> 
Its, from your perspective, even more entertaining.
 creating slices does work: A[[1,3,4,9], [4, 6, 8]] does work, but
copies the entries.
Depending on the ring, det(A) will
 - copy A
 - do an inplace LU, destroying the copy 
 - read off the det
So by bypassing the copy and not doing a view, you're not loosing anything.

The matrix model in FLINT/Nemo
 - a flat array with all entries in a 1-dim list of length n*m
 - an array of pointers to the 1st entry in each row (so pointer into
   the flat array from above)
Thus
 - A[i,j] -> A.rows[i] + j to get the address and then read the entry
 - swapping of rows is trivial: just swap the pointers
 - a view has the entries pointer == 0
  - the rows array points to the selection of the rows plus the offset
    for the columns:
    B = view(A, 3:5, 2:5)
    then B.entries == 0
    B.rows[1] = A.rows[3] + 2
    ...
    to make it gc safe in julia, we agment the matrix struct by a
    view_parent entry that points to the original matrix
Thus the rows range can be arbitrary, while the columns have to be
consecutive.

**Comment by StevellM** [comment]
Thanks for all these very nice explanations. The matrix for which I need some 3-minors is actually 3x6, so I am not necessarily trying to optimize the computations. But I see that if I want to use view, I should rather consider its transpose... but since `det` will copy the entries anyway according to you, there is no point of making such a change (my ring is a multivariate polynomial ring).
