### ISSUE TITLE
snf doesn't take all kinds of matrices

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#153]
I noticed that hnf take MatElem{T}, which I think is any old matrix, but snf only takes Mat{T}, which is only generic matrices. I'm wondering if that is really what we want.

**Comment by thofma** [comment]
What is an old matrix?

**Comment by wbhart** [comment]
Sorry, it's an English expression. "any old blah" means an "arbitrary blah".

**Comment by thofma** [comment]
`snf` should also take `MatElem{T}`. Can you change this in your matrix algebra branch?

**Comment by wbhart** [comment]
Yes, I can.

**Comment by wbhart** [comment]
Done.
