### ISSUE TITLE
The use of polynomial rings in multi-threaded programs

### ISSUE THREAD

**Issue by sumiya11** [Nemocas/AbstractAlgebra.jl#1542]
Hi!

Can you please clarify when the use of univariate/multivariate polynomial ring functionality over QQ, ZZ, or GF(p) is safe in multi-threaded programs? For example, when used inside `Base.Threads.@threads`.

To be more specific, I have a narrow list of functions that are of interest to me, such as basic getters and constructors, presumably no polynomial arithmetic:

- `base_ring`, `nvars`, `gens`, `ordering`, `characteristic`, for polynomial rings
- `parent`, `iszero`, `length`, `coeff`, `coefficients`, etc, for polynomials
- `poly_ring()`, `poly_ring(coeffs, exps)`, etc, for creating polynomials

For context, I have the package [Groebner.jl](https://github.com/sumiya11/Groebner.jl) that uses AbstractAlgebra.jl and Nemo.jl polynomial types for communicating with the user. It takes `Poly`s/`MPoly`s as its input and extracts the parent and monomials/coefficients from them. When constructing the output result, it also creates `Poly`s/`MPoly`s from monomials/coefficients. I would like to ensure that these conversions are OK to run in parallel.

What prompted the question is that I discovered (the hard way :^)) that `AbstractAlgebra.GF(p)` is not safe.

Thanks,
Alex

**Comment by thofma** [comment]
They should be all fine for now. I don't know if we can guarantee anything but the future. At least I don't know of any plans to make those functions not threadsafe anymore.

**Comment by sumiya11** [comment]
Thank you for the clarification.

Can we expect that changes to this behavior will be fenced by a breaking release?

**Comment by thofma** [comment]
Yes, I would say so.
