### ISSUE TITLE
Documentation of aliases seems to fail on nightly?

### ISSUE THREAD

**Issue by joschmitt** [Nemocas/AbstractAlgebra.jl#1608]
The CI breaks on nightly e.g. here: https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/7900676059/job/21562690303?pr=1597#step:6:105 .
Apparently there is a problem with the automatic documentation of an alias.

**Comment by lgoettgens** [comment]
I'll try to bisect this to a julia nightly commit tomorrow

**Comment by lgoettgens** [comment]
First learning of the bisect: This error does not occur when only including the test file into the REPL, only when `] test`. I'll keep you posted once the bisect is done.
