### ISSUE TITLE
`@polynomial_ring` is broken for coefficient rings not in `AbstractAlgebra`.

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1630]
The following is with Julia 1.9.4 and 1.10.1 in case it makes a difference.

Observe:
```
julia> K = QQ
Rational field

julia> @polynomial_ring(K,["x", "y"])
ERROR: UndefVarError: `K` not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/AbstractAlgebra/KwfqS/src/misc/VarNames.jl:322 [inlined]
 [2] top-level scope
   @ REPL[49]:1
```

Reason gets clear here:
```
julia> @macroexpand(@polynomial_ring(K,["x", "y"]))
quote
    #= ~/.julia/packages/AbstractAlgebra/KwfqS/src/misc/VarNames.jl:322 =#
    (var"#41#X", (x, y)) = (AbstractAlgebra.polynomial_ring)(AbstractAlgebra.K, [:x, :y])
    #= ~/.julia/packages/AbstractAlgebra/KwfqS/src/misc/VarNames.jl:323 =#
    var"#41#X"
end
```
So it evaluates `K` inside module `AbstractAlgebra`, instead of the current scope. I actually did run into this for the `@alias` macro.

I believe the fix involved using `QuoteNode`. But it's not easy to understand the code with all 

CC @mgkurtz

**Comment by mgkurtz** [comment]
As I see it, we need an `esc` to evaluate the arguments in the correct scope. I provided a quickfix in #1633. Though, for a proper fix the keyword arguments should be escaped as well. I will also need to write some tests before I introduce some new bugs then. If you need this to work right now, #1633 should do the trick.
