### ISSUE TITLE
Switching Rings.jl and NCRings.jl causes test failure (serious bug!!)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#164]
If Rings.jl is included at the end of NCRings.jl instead of at the beginning, the rel_series ad hoc operators fail when multiplying by the Int 0. This is because instead of calling the special function for this operation, it first coerces zero into the ring, which means it gets truncated to the default precision. This causes the identity tested in the test code to fail.

N.B: the failure is not in the rel_series code but is either a bug in Julia or in the NCRings module.

**Comment by rfourquet** [comment]
@wbhart do you still see the test failure? I just ran the test suite and didn't get it (but I might have tested the wrong thing).

**Comment by wbhart** [comment]
If it's gone, it's gone.

I did report the bug to the Julia folks with a minimum example.
