### ISSUE TITLE
Methods for finding factors and roots of a polynomial in AbstractAlgebra.jl

### ISSUE THREAD

**Issue by shubh-b** [Nemocas/AbstractAlgebra.jl#1644]
At present using `Nemo.jl` we can see

```
julia> using Nemo

julia> R, x = polynomial_ring(ZZ, :x)
(Univariate polynomial ring in x over ZZ, x)

julia> p = x^3 - 13*x^2 - 6*x + 78        # A polynomial defined in R in variable x over Integers
x^3 - 13*x^2 - 6*x + 78

julia> factor(p)                          # We can factorise this polynomial
1 * (x - 13) * (x^2 - 6)

julia> roots(p)                           # We can find roots over Integers only as p is defined in ring R over integers
1-element Vector{ZZRingElem}:
 13
```

So, finding factors and roots of a polynomial possible using `Nemo.jl`, although roots we get only in Integers here. In `AbstractAlgebra.jl` module are there methods to do the same!?!

Could you please include methods in `AbstractAlgebra.jl` module for finding factors and all roots (not only integers and rationals) of a polynomial the way we see in `SymPy` module in Python?

Thank you.

**Comment by fieker** [comment]
On Tue, Apr 02, 2024 at 05:51:46AM -0700, SUBHABRATA wrote:
> At present using `Nemo.jl` we can see
> 
> ```
> julia> using Nemo
> 
> julia> R, x = polynomial_ring(ZZ, :x)
> (Univariate polynomial ring in x over ZZ, x)
> 
> julia> p = x^3 - 13*x^2 - 6*x + 78        # A polynomial defined in R in variable x over Integers
> x^3 - 13*x^2 - 6*x + 78
> 
> julia> factor(p)                          # We can factorise this polynomial
> 1 * (x - 13) * (x^2 - 6)
> 
> julia> roots(p)                           # We can find roots over Integers only as p is defined in ring R over integers
> 1-element Vector{ZZRingElem}:
>  13
> ```
> 
> So, finding factors and roots of a polynomial possible using `Nemo.jl`, although roots we get only in Integers here. In `AbstractAlgebra.jl` module are there methods to do the same!?!
> 
> Could you please include methods in `AbstractAlgebra.jl` module for finding factors and all roots (not only integers and rationals) of a polynomial the way we see in `SymPy` module in Python?
> 
Unfortunately: no.
 In Nemo, roots and factorisation will not extend the coefficient ring.
This is deliberate and neccessary for many algebraic operations.
Furthermore, the factorisation is actually (for Z/Q) done in flint, in C
and is hightly non-trivial, read thousands of lines of code. 
Rebuilding this in AA is out of reach (for us. If s.o. wants to do it...)

If you want all roots, in Nemo you'll have to create the polynomial
over the reals (or complexes it you want all roots) and then ask for the
roots. Again, this are very sophisticated numerical algorithms...

In Hecke or Oscar, you can do 
 factor(ComplexField(), f)
to combine this, but this is mainly sugar, the underlying method is the
same.

Sorry
 Claus

**Comment by shubh-b** [comment]
I was wondering and curious a bit, why don't you make these two functions `factor()` and `roots()` available in `AbstractAlgebra.jl `module?
