### ISSUE TITLE
Bugs in `ispower_moduli`?

### ISSUE THREAD

**Issue by lgoettgens** [Nemocas/AbstractAlgebra.jl#1750]
> I was curious what these vectors are used for. Turns put the code is buggy: the code in line 391 below checks for divisibility by 3 instead of 7... oops.

_Originally posted by @fingolfin in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1749#discussion_r1678272125_

**Comment by fingolfin** [comment]
I suspect the code is still correct but perhaps less efficient.

The lack of any comments explaining what's going on (which admittedly is not that hard to guess) or more importantly, why those specific numbers have been chosen, doesn't help :-(
