### ISSUE TITLE
`@varnames_interface`: warn or even reject duplicate variable names?

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1761]
It probably isn't a good idea to use the same variable names multiple times, like here:
```
julia> polynomial_ring(QQ, :x=>1:2, :x=>1:3)
(Multivariate polynomial ring in 5 variables over QQ, QQMPolyRingElem[x[1], x[2]], QQMPolyRingElem[x[1], x[2], x[3]])
```

Should we catch this and either print a warning, or outright error? My guess is that this mostly happens due to user error (e.g. a typo changing `y` to `x`)

It would be easy enough to do by inserting an `allunique` call in a suitable spot. Of course that in turn slows down things.

If we decide against it, perhaps we should at least insert a warning comment in the `polynomial_ring` docstring that this is not checked for?

**Comment by lgoettgens** [comment]
I am in favor of adding an `allunique` check. This shouldn't be the bottleneck for any of the use cases.

**Comment by fingolfin** [comment]
We talked about this during triage, and it was determined that this would break some stuff (and indeed #1850 triggers CI errors). Later Wolfram showed me some concrete cases where this is problematic.

E.g. when forming products of varieties, we need to form a "product" of the underlying polynomial rings, which basically means creating a new polynomial ring which has as variables the union of the variables of the initial two rings. 

For various reasons (e.g. to help users track variables, for debugging, etc.) it is useful to keep the names of the input rings. The user may not care, but when they do, this can be super helpful. But obviously it easily leads to a situation with duplicate variable names. Multiple ways to deal with this:
1. just don't, i.e. leave things as they are (I propose that's what we do for the time being)
2. one could provide a function which tries to "fix up" a list of varnames, e.g.: if a variable name occurs a second time, say, `:x`, replace the second instances by, say `:(x')` or :x1`. But of course that could lead to a new collision, so this needs to keep trying new names until it finds one without a collision. But I fear this may make things more confusing for users, not less
3. we could introduce a kwarg which control this, say `allow_duplicate_varnames::Bool=false` (or `forbid_duplicates=true` or whatever). Then code which constructs such products can pass `allow_duplicate_varnames=true`. However all calling code needs to be adjusted, so if we were to go this way, then we would need to first roll it out with the duplicates check *off* by default; then code in Hecke, Oscar etc. could be adjusted to pass that kwarg; and once that is complete, we could switch the default.


But options 2 and 3 involve quite a bit of work, and I am not sure it's really worth it?

**Comment by lgoettgens** [comment]
2 indeed seems very bad.
3 would need someone to work in the macro-bell, and I am not convinced that this kwarg would be used consistently downstream.

So let's go with 1.
