### ISSUE TITLE
`@varnames_interface`: support variant with number of variables, e.g. `@polynomial_ring(QQ, 2)` ?

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1762]
Currently `polynomial_ring(QQ, 2)` works but `@polynomial_ring(QQ, 2)` throws an error:
```
julia> @polynomial_ring(QQ, 2)
ERROR: LoadError: MethodError: no method matching _varnames_macro(::Int64)

Closest candidates are:
  _varnames_macro(::Union{AbstractArray{<:Union{Char, AbstractString, Symbol}}, Pair{<:Union{Char, AbstractString, Symbol}}}...)
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/misc/VarNames.jl:339
  _varnames_macro(::Union{Char, AbstractString, Symbol})
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/misc/VarNames.jl:338

Stacktrace:
 [1] top-level scope
   @ none:1
 [2] eval
   @ ./boot.jl:385 [inlined]
 [3] eval
   @ ./Base.jl:88 [inlined]
 [4] _eval(m::Module, e::Expr)
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/misc/VarNames.jl:242
 [5] var"@polynomial_ring"(__source__::LineNumberNode, __module__::Module, args::Vararg{Any})
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/misc/VarNames.jl:483
in expression starting at REPL[29]:1
```

Should we attempt to support this, for symmetry?

Pinging @mgkurtz just for the off-chance that he has time and is interested in looking into this ;-).

**Comment by mgkurtz** [comment]
Seems to work as documented, right now 😄 Though adding symmetry would be nice. I will work on this later today.

**Comment by fingolfin** [comment]
Oh yeah, this is definitely not a bug (it works as documented) more a feature request :-).

**Comment by mgkurtz** [comment]
> It is not clear to me what `@polynomial_ring(QQ, 2)` is supposed to do semantically?
So, your interpretation is that `polynomial_ring(QQ, 2)` creates anonymous variables which just happen to be printed as `x1` and `x2`? From that point of view, `@polynomial_ring(QQ, 2)` really makes no sense. When you view `polynomial_ring(QQ, 2)` as short form of `polynomial_ring(QQ, 2, :x)` instead, a macro version does make sense.
> Should it create a multivariate polynomial ring and put the two generators into some randomly named variables?
Yes, if you call `x1` and `x2` random. The names are as in `polynomial_ring(QQ, 2)`.
> Or as a 2-tuple into one variable?
No, the `@polynomial_ring` macro never creates tuples.
