### ISSUE TITLE
Prevent negative dimension matrix rings

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1851]
I am tempted to say 0x0 matrix rings should just be not supported. For quotient rings we can't easily / cheaply check for them being trivial (as it may involve a Gröbner basis calculation or worse). But here it would be trivial.

For that matter, we definitely should prevent -1x-1 matrix rings 🤡 
```
julia> matrix_ring(ZZ, -1)
Matrix ring of degree -1
  over integers
```

_Originally posted by @fingolfin in https://github.com/Nemocas/AbstractAlgebra.jl/issues/1848#issuecomment-2400734119_

**Comment by thofma** [comment]
Hm, I would not want to remove it.

**Comment by fingolfin** [comment]
@thofma says that these pop up naturally for him, so that's a good argument for me to keep supporting them.
