### ISSUE TITLE
most or all occurences of `x == 0` could be improved by replacing with `iszero(x)`

### ISSUE THREAD

**Issue by nsajko** [Nemocas/AbstractAlgebra.jl#1868]
The function `iszero` serves to compare a value against zero. In particular, it's more performant for `Rational`, `BigInt` and `BigFloat`:

https://github.com/JuliaLang/julia/blob/f1990e2e3d8d31087b23288f640ba16909f7ec7b/base/gmp.jl#L722-L722

https://github.com/JuliaLang/julia/blob/f1990e2e3d8d31087b23288f640ba16909f7ec7b/base/mpfr.jl#L1130-L1130

https://github.com/JuliaLang/julia/blob/f1990e2e3d8d31087b23288f640ba16909f7ec7b/base/rational.jl#L551-L551

**Comment by fingolfin** [comment]
That largely depends on the underlying implementation.

**Comment by fingolfin** [comment]
I agree that this is sensible were `x` may be a `BigInt`, `BigFloat` or `NCRingElem`

But for code comparing against a bit integer, like `ngens(V) == 0` or `length(f) == 0`, there is no benefit and arguably in many cases the code is more readable with the `== 0`.

So I disagree with the claim that "most or all occurences [sic]" should be changed. In fact it seems you already tweaks most places were this is relevant. If you spot further, a PR is welcome, but I don't think this is an issue we want to work on.
