### ISSUE TITLE
Constructors for power series

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#19]
It would be theoretically possible to allow ZZ[["x"]], say, by overloading

```
getindex(::AbstractAlgebra.Integers{BigInt}, ::Array{String,1})
```

**Comment by fieker** [comment]
On Wed, Feb 07, 2018 at 05:05:27AM -0800, wbhart wrote:
> It would be theoretically possible to allow ZZ[["x"]], say, by overloading
> 
> ```
> getindex(::AbstractAlgebra.Integers{BigInt}, ::Array{String,1})
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/AbstractAlgebra.jl/issues/19

I would be VERY careful with those kinds of "syntactic sugar" hacks....
They come back to bite you!
I think I probably also like to do
  Ring[i] -> gens(Ring)[i]
for i an Int, a range, ...
One can argue what's easier.

The problem with Z["x"] and similar is that the help system is not able
to offer any help there. I can do ?PolynomialRing or similar and expect
to get s.th..
I cannot do this for FlintZZ...

All those things are extremely cool to start with, but I am not
convinced about the long term sustainability.

Claus

**Comment by wbhart** [comment]
I think this is not feasible because there's no way to specify a precision with this. So closing for now.
