### ISSUE TITLE
Print functions need precedence

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#198]
According to Daniel, who has volunteered to fix this, printing functions should take a right and a left precedence to determine what to print with parentheses. This will also need to be fixed in Nemo/Hecke/Singular/Oscar.jl.

**Comment by tthsqe12** [comment]
As far as I can see the printing functions are called show. No? And a parent is the one who determines if its child needs to be printed with parentheses (not the child itself). If you want precedence correct printing with manageable code, it has to be the other way around. There should be a top level `show(x)`, that calls a recursive `_show` as `_show(x, left=lowest_precedence, right=lowest_precedence)`. Then, every time someone makes a new object type T, they are responsible for implementing `_show(T x, Precedence left, Precedence right)`, Approximately how many objects are currently implemented with incorrect printing?

**Comment by tthsqe12** [comment]
I think there two main problems to avoid in printing:
1) make your string precedence correct, i.e. don't print `(a+b)/(c*d)` as `(a+b)/c*d` 🙁
2) don't mash tokens, i.e. don't print `factorial(a)=b` as `a!=b`, which would get confused with `notequal(a,b)`.
If Sachin is up for some good fun, I'm sure it could be done. For 1) you would have to compile a list of the precedences of the operators of the target language (assuming that is how it works) and for 2) you would have to compile a list of unmashable operators and have your printer remember the token printed. Then, of course, you would have to re-implement the tons of printing functions. 🙁

**Comment by tthsqe12** [comment]
This can be done write away:
Make a test function that creates random objects from all over the system. Print them and then compare the parsed result with the original object. This is probably enough to get started. We can found out just how many of the printing function are indeed wrong.

**Comment by wbhart** [comment]
It's hard to do such a comparison because the printed result need not agree with the parsed result, e.g. consider Z/nZ. The output might just print 3 instead of 3 mod 7, so 3 + 4 might correspond to 0, but you do the computation 3 + 4 and Julia returns 0.

I started with a project to print some things by hand and look at the output and see if it made sense, but this project seems to have been too hard.

**Comment by fieker** [comment]
I think the start of this issue is missing. What problem, with example, are we trying to solve?

**Comment by wbhart** [comment]
In summary, whether the parentheses should be there depends on the associativity of the operator.

**Comment by tthsqe12** [comment]
@fieker The problem is exactly as @wbhart says. Then, when I go to try to fix it around
https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/Fraction.jl#L154 ,
I see that the print function is lacking precedence info in its signature. Similarly, the `needs_parentheses` function without precedence info is not sufficient unless you want to start printing parentheses around everything.

**Comment by thofma** [comment]
We now have the best printing.
