### ISSUE TITLE
Serialization of AbstractAlgebra.Generic.MPolyRing and AbstractAlgebra.Generic.MPoly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#206]
I have seen that there is an attempt to realize serialization for certain Nemo objects (https://github.com/Nemocas/Nemo.jl/pull/489). Is there a plan for serialization of objects of type AbstractAlgebra.Generic.MPolyRing and AbstractAlgebra.Generic.MPoly?

**Comment by wbhart** [comment]
The attempt to serialise Nemo object was not successful (complicated reasons, requires beer).

It's my understanding that there is no need to serialise AbstractAlgebra objects, as they are pure Julia objects and the usual serialisation works just fine.
