### ISSUE TITLE
evaluate(::AbstractAlgebra.Generic.MPoly{fmpz}, ::Array{fmpz,1}) bug?

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#210]
Is the following supposed to work?

```
using AbstractAlgebra; using Nemo
R,(x1,x2) = AbstractAlgebra.Generic.PolynomialRing(Nemo.ZZ, ["x1","x2"])
AbstractAlgebra.Generic.evaluate(x1, Array{Nemo.fmpz,1}([0,0]))
```

I am getting this error:

`ERROR: BoundsError: attempt to access 2×1 Array{UInt64,2} at index [0, 1]`

**Comment by wbhart** [comment]
Yes, apparently it should work. It's a shame that whoever wrote the adhoc.jl file didn't write test code for it, so that I had no idea that there were functions in there that needed changing after the recent update (there may be more, I didn't check).

I will submit a patch for this issue.

**Comment by wbhart** [comment]
By the way, your example can be better written as follows:

```
using Nemo

R, (x1, x2) = Generic.PolynomialRing(ZZ, ["x1", "x2"])
Generic.evaluate(x1, fmpz[0, 0])
```

**Comment by wbhart** [comment]
Fixed by Nemo PR 519.
