### ISSUE TITLE
det is broken

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#226]
Since we merged #211 the determinant is broken for `nf_elem`:
```julia
julia> Qx, x = FlintQQ["x"]
K, (Univariate Polynomial Ring in x over Rational Field, x)

julia> K, a = Nemo.NumberField(x^2 - 10, "a")
(Number field over Rational Field with defining polynomial x^2-10, a)

julia> z = matrix(K, 2, 2, [2*a+2, -2*a+2, a+1, -2*a-1])
[2*a+2 -2*a+2]
[a+1 -2*a-1]

julia> det(z)
-6*a+16
```
The correct answer is `-6*a - 24`. @wbhart

**Comment by wbhart** [comment]
I'll look into it. I thought I wrote test code for all the delayed reduction code. Not sure what I missed.

**Comment by thofma** [comment]
Thanks. I forgot to mention that this is with the latest master version of Nemo.

**Comment by wbhart** [comment]
I can only get it to fail for quadratic fields. The bug is almost certainly in the mul or add or reduce function in the antic library (the versions that don't reduce, or course).

**Comment by thofma** [comment]
Oh no, not again.

**Comment by wbhart** [comment]
I guess we've never used those before, since this is the first time we've turned on delayed reduction.

**Comment by wbhart** [comment]
At the very least, the addition function (nf_elem_add.c for the qf case) is broken. It only adds three coefficients, but should add 5.

**Comment by wbhart** [comment]
Wait, no, sorry. Three is correct. If the defining polynomial is degree 2, the elements have degree 1, which means their products have degree 2, which is length 3.

**Comment by wbhart** [comment]
The bug is in swap (in nf_elem.h). In the quadratic case it must have fmpz_swap(anum + 2, bnum + 2); The swap function is used to handle aliasing in the mul code.

**Comment by thofma** [comment]
Can you push a fix to antic? Then I can built new binaries.

**Comment by wbhart** [comment]
Done. Once again, if you build new binaries, could you take the latest Flint.
