### ISSUE TITLE
Laurent series inplace mul incorrect

### ISSUE THREAD

**Issue by martinra** [Nemocas/AbstractAlgebra.jl#229]
I was correcting a typo in add! and to catch it in the future added tests for inplace operations. You can check the test code I added at https://github.com/martinra/AbstractAlgebra.jl/tree/laurent_series_add . What I found was this (the results differ in the coefficient for x^-5).

`Generic.LaurentSeries.inplace_binary_ops...`
`Test Failed at ***/AbstractAlgebra.jl/test/generic/LaurentSeries-test.jl:270`
`  Expression: isequal(r, f * g)`
`  Evaluated: isequal(3*x^-12+2*x^-9+3*x^-8+2*x^-7+4*x^-6+4*x^-5+O(x^-4), 3*x^-12+2*x^-9+3*x^-8+2*x^-7+2*x^-6+2*x^-5+O(x^-4))`

When I run other instances, the error shows up for integral domains as coefficient field, so it has probably nothing to do with that.

Perhaps somebody who knows the code better than me can investigate the cause.

**Comment by wbhart** [comment]
Thanks for reporting. I will investigate when I get a chance. This code probably has zero applications, since the functions mainly exist for matrices and polynomials over Laurent series rings. But of course it makes sense to fix the functions anyway.
