### ISSUE TITLE
Evaluation of univariates at integers other than BigInt and Int is wrong

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#236]
```
R, x = PolynomialRing(ZZ, "x")
f = x^55

f(200)
f(Cint(200))
f(Cint(200)//Cint(1))
```

**Comment by thofma** [comment]
I don't know what you mean by wrong. I don't think we can guarantee much for rings with overflow/overflow checks.

**Comment by thofma** [comment]
OK, I know what you mean by wrong, but still I don't think that we can guarantee much.

**Comment by fieker** [comment]
On Mon, Jan 21, 2019 at 02:45:43PM +0000, thofma wrote:
> OK, I know what you mean by wrong, but still I don't think that we can guarantee much.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/AbstractAlgebra.jl/issues/236#issuecomment-456097509

What's wrong is easy I'd guess: Uint is actually ResidueRing(FlintZZ, 2^64)
and similar. Int, Uint, ... are not char zero. I don't know to what
extend this is fixable/ should be fixed.

What is the desired/ correct result?

**Comment by wbhart** [comment]
I don't think it makes any sense for evaluation of a polynomial over ZZ at
integers to return the wrong answer.

Doing something like f(12) is a very natural thing for people to do, and I
think it should work. It does work. But then why doesn't it work for other
types of integers and rationals.

**Comment by thofma** [comment]
If you have a polynomial `f` over a ring `R` and an element `a` from a ring `S`, then at the moment the result of `f(a)` (should have) the same parent as `zero(R) + zero(S)` or `zero(R) * zero(S)`. This works quite well, but in `subst` the `powers` function is called and he computes powers of `a`. For `Cint` they are wrong if the result is supposed to be an element of `BigInt` and for `Rational{Cint}` it will overflow.

**Comment by thofma** [comment]
It is also wrong for `f(200)`, but you have to make the power large enough:
```julia
julia> f = x^155
x^155
julia> f(200)
22227703261241243782516858339252189849130254013892154313748619951840568876037102086429478987067201746163129691236554281081870631458570755963441557873233444042867045076111448823896202892071280713269107096856893935897838354432000000000000

julia> f(BigInt(200))
456719261665907161938651510223838443642478919680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by wbhart** [comment]
Yeah, there should be a separate version of the evaluation that works for
Integer, and coerces the integers into the base_ring of the polynomial ring
first.

That's what I've done for multivariates.

**Comment by wbhart** [comment]
In the case of the rationals, that doesn't work of course. The best one can
do is coerce into Rational{BigInt} and then apply the generic code.

**Comment by wbhart** [comment]
Actually, what I've now done in the case of the multivariates is to check
of the type of the value being substituted belongs to Integer and if so,
coercing it to a BigInt. The same for rationals to Rational{BigInt}.

Technically this means that if you defined a polynomial over Int and
evaluated it at a small Int, you'd get a BigInt as the result. But I'm not
sure there is a better way.

If we don't do this, I think people are going to too often do f(0) and
expect the result to be useful.

**Comment by thofma** [comment]
If you define a polynomial over `zz` instead of `ZZ`, that is, `Int` instead of `BigInt`, then I see also no reason why the result should be a `BigInt`. Evaluation should do the same as all the operations with `zz` do, that is, don't promote to `ZZ`.

**Comment by wbhart** [comment]
I came up with a better strategy which addresses your concerns.

If we are evaluating at a value of type V <: Integer or Rational, I compute
c = zero(R)*zero(V) where R is the coefficient ring of the poly. I then
coerce the value into parent(c). This is the best compromise, since it will
always result in values belonging to the ring that c belongs to, which is
what you really want.

It's not optimal if R happens to be a much bigger ring than V, but it also
shouldn't be terrible.
