### ISSUE TITLE
fflu! works over a field or residue ring but not polynomials over a residue ring

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#247]
There are two versions of fflu!. One of them relies on the existence of inv and appears to work for residue rings, even if they are not integral domains.

The other version is the fallback for rings that are not fields or residue rings. It uses divexact instead of inv.

For some reason, it seems to give incorrect answers, even if an impossible inverse error is raised when the pivot or other nonzero entries below a pivot are zero divisors. Similarly, checking that the determinant that is returned is not a zero divisor doesn't help.

One strategy I haven't tried is to coerce into the fraction "field" and call the other version, then clear denominators, checking for multiplication by zero divisors in doing so. But this is probably best delayed until we implement change_base_ring for matrices.

**Comment by a-kulkarn** [comment]
Do you have a test input where this behaviour is observed?

**Comment by wbhart** [comment]
Not any longer. But probably I just used random matrices with entries in Z/(p1*p2)Z for some small primes p1 and p2 and fiddled until I got an example as described.

**Comment by wbhart** [comment]
Of course, this may only affect AbstractAlgebra and not Nemo. I don't know for sure.

**Comment by wbhart** [comment]
fflu can only work in a domain where the elements can be inverted in the fraction field since the definition of fflu depends on inverting the elements in a given matrix U (see definition of fflu in the AbstractAlgebra docs). Polynomials over a domain might conceivably be thought to be invertible in the fraction field of the domain, but polynomials over a non-integral domain are difficult mathematically.

At present the fflu! code excludes rings types that are not domain_type and this seems to be correct (it works over the integers if one works in the fraction field when constructing D).

The original issue here may have been for matrices over constant polynomials over a residue ring which is not an integral domain. But I can find no failing cases here, so if there was an issue, it appears to have been fixed since then.
