### ISSUE TITLE
We do not have a Project.toml file

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#250]
Julia no longer uses a REQUIRE file (since Julia 0.7), but all dependencies are in the Project.toml file, which has to be generated by Julia.

Apparently the Project.toml file can also specify all the dependencies that should be available when a given "environment" is active. That way, if someone is in that environment and they do "using AbstractAlgebra" it will load the one specified in that environment.

This is probably why we've been having these package resolution issues.

**Comment by thofma** [comment]
See for example https://discourse.julialang.org/t/registering-a-new-package-in-general/13900/2

**Comment by wbhart** [comment]
The Project.toml file is mentioned in the Pkg documentation. I was reading it to see how to set dependencies and then started looking for forum posts about how to do it. I found a person complaining about how REQUIRE used to Just Work TM and now they have to go through a complicated process.

**Comment by wbhart** [comment]
It looks like the whole getting rid of REQUIRE thing stalled somehow. I'm just not clear on whether Julia actually does anything with it.

**Comment by kalmarek** [comment]
producing Project.toml is easy enough:
```
shell> cd /tmp
pkg> activate AbstractAlgebra
pkg> add ... #(all that is in the REQUIRE)
```
You have Your first version in `/tmp/AbstractAlgebra` then
 * fix version
 * add authors
 * `[compat]` section which is waaay more natural than versioning in REQUIRE
 * maybe `Test` under `[extra]`

**Comment by wbhart** [comment]
I did something like this for Nemo, but then didn't know what all the numbers meant, what should be in the sections, etc. I didn't find any useful documentation and the tools are also obscured in mystery.

Furthermore, I didn't know what effect this would have on our development. Will it still use the dev version of AbstractAlgebra in Nemo and so on, if there is one? Or will it always check out a version according to the .toml file, complicating development?

**Comment by kalmarek** [comment]
this Project.toml should not put any restrictions on the versions Nemo uses, unless Nemo's Project.toml `[compat]` section specifies it. This is your Manifest.toml that may mix-up Your flow (e.g. editing files and wondering why the changes in a package are not reflected at runtime). But if You have the packages devd there shouldn't be any problem.

(the documentation to Pkg is a joke, You need to grab bits and pieces from discourse)

**Comment by rfourquet** [comment]
This can be closed.
