### ISSUE TITLE
f.(A) for a matrix A and a function f?

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#259]
It is possible to apply a function f to every entry of a 2-dimensional Julia array A using the notation `f.(A)`.
How about a similar syntax of AbstractAlgebra matrices?

**Comment by wbhart** [comment]
It probably would be possible if we defined length(M) = nrows(A)*nrows(B) and then defined indexing of AbstractAlgebra matrices with a single index.

The possible confusion here is that AbstractAlgebra uses row major, whereas Julia uses column major, so there is going to be a mismatch between what the two single indexing modes do.

I'm not completely opposed to doing this, but I'm not super clear on whether it is a good idea.

**Comment by kalmarek** [comment]
have a look how it is defined in `Polymake.jl`, agnostic of the internal storage (which is row-major, by coincidence)

**Comment by fingolfin** [comment]
This has been supported for quite some time now.
