### ISSUE TITLE
Error with 0.4.1

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/AbstractAlgebra.jl#261]
using Nemo (0.11.1)
    function V000045(n)
       F = ZZ[1 1; 1 0]
       Fn = F^n
       Fn[2, 1]
    end
    println(V000045(30))

Works with AbstractAlgebra version "0.3.3" (on Windows). 
After upgrading to version 0.4.1 an error occurs.

**Comment by thofma** [comment]
Should be fixed.
