### ISSUE TITLE
change_base_ring does not work for external packages

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#273]
Because change_base_ring uses the PolynomialRing constructor, it always generates a generic polynomial instead of creating a polynomial belonging to the module in use (e.g. Singular.jl).

I have no idea whatsoever how to fix this problem. Ideas are welcome.

**Comment by wbhart** [comment]
The only solution seems to be to pass the polynomial ring to change_base_ring. I don't see any other way around it.

**Comment by heiderich** [comment]
My suggestion in https://github.com/Nemocas/AbstractAlgebra.jl/issues/106#issuecomment-399395006 was to hand over an algebra morphism, which should in particular specify the target ring. I suggested a pair (S, f), where S is the target ring and f the ring homomorphism from the base ring of the polynomial to S. Whether one needs a type for ring homomorphism, I am not sure. Maybe one could just add the target as an additional parameter.

**Comment by wbhart** [comment]
Now see the more comprehensive ticket https://github.com/Nemocas/AbstractAlgebra.jl/issues/490
