### ISSUE TITLE
Should we define matrix_type(R) for a ring R?

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#302]
Suppose I do the following in Nemo/AbstractAlgebra:

```
A = [matrix(ZZ, 1, 1, [ZZ(1)]) for i in 1:n]
```

If n is 0 then A will have type `Array{T, 1} where T[]` or something like that.

If n > 0 and we use AbstractAlgebra, it will also have a different type than if we use Nemo.

This makes it really hard to store A somewhere, because you don't know what type it is.

If we implement a function matrix_type(R) which returns the type of matrices over the ring R, e.g. for R = ZZ and using Nemo it would return fmpz_mat, in AbstractAlgebra it would return Generic.Mat{BigInt}, and so on. Then we could construct the array above with a consistent type.

I'm actually hitting this in practice as module generators and relations are stored as Julia vectors of AbstractAlgebra/Nemo matrices, and I want to store the resulting Julia vectors in the corresponding modules when they are created.

The other option is just to declare what I am doing to be dumb, and make me define a specialised type for a list of generators/relations in a module.

Even if we do the above, the type for a module where we store the generators/relations will have entries of type Vector{<:AbstractAlgebra.MatElem} which is the same as Any. So perhaps the matrix_elem function doesn't really fully solve the problem I need to solve. But I'm betting this issue occurs elsewhere commonly enough.

**Comment by fieker** [comment]
On Mon, May 06, 2019 at 08:34:15AM -0700, wbhart wrote:
> Suppose I do the following in Nemo/AbstractAlgebra:
> 
> ```
> A = [matrix(ZZ, 1, 1, [ZZ(1)]) for i in 1:n]
> ```
> 
> If n is 0 then A will have type `Array{T, 1} where T[]` or something like that.
> 
> If n > 0 and we use AbstractAlgebra, it will also have a different type than if we use Nemo.
> 
> This makes it really hard to store A somewhere, because you don't know what type it is.
> 
> If we implement a function matrix_type(R) which returns the type of matrices over the ring R, e.g. for R = ZZ and using Nemo it would return fmpz_mat, in AbstractAlgebra it would return Generic.Mat{BigInt}, and so on. Then we could construct the array above with a consistent type.
> 
> I'm actually hitting this in practice as module generators and relations are stored as Julia vectors of AbstractAlgebra/Nemo matrices, and I want to store the resulting Julia vectors in the corresponding modules when they are created.
> 
> The other option is just to declare what I am doing to be dumb, and make me define a specialised type for a list of generators/relations in a module.
> 
> Even if we do the above, the type for a module where we store the generators/relations will have entries of type Vector{<:AbstractAlgebra.MatElem} which is the same as Any. So perhaps the matrix_elem function doesn't really fully solve the problem I need to solve. But I'm betting this issue occurs elsewhere commonly enough.

you could do a single matrix (ie. vcat, hcat), then the type is well
defined (well still depends on the ring). This I'd say is a property of
julia/Nemo: we have abstract types, but arrays over them are difficult.
In particular in view of specialisation....
I guess matrix_type could work - but it probably need to be parametrized
by the elem_type and not the ring itself....

**Comment by thofma** [comment]
You mean something like this: https://github.com/thofma/Hecke.jl/blob/master/src/Misc/Matrix.jl#L13-L29?

**Comment by fieker** [comment]
On Mon, May 06, 2019 at 03:47:26PM +0000, thofma wrote:
> You mean something like this: https://github.com/thofma/Hecke.jl/blob/master/src/Misc/Matrix.jl#L13-L29?
> 

... not at all!

but Yes!

apart from relations possibly being elements of a free module (module
elements) and not matrices...

**Comment by wbhart** [comment]
@thofma Something like that would work. I was thinking that I'd have to do matrix_type(ZZ), since I don't know if I'm using Nemo, AbstractAlgebra or something else to create matrices over ZZ. But your way would work because the version for fmpz would only be defined for Nemo, and I can get elem_type(R) no problems. I think this would actually solve both of the problems I mentioned, so I am liking it more.

@fieker I've just changed the module code from a single matrix to a vector of Nemo matrices, so I don't want to rewrite it again. Having said that, I currently have one nontrivial function which has to be defined for matrices and for vectors of Nemo matrices because of this choice. I will have to revisit how generators and relations are stored. But yeah, storing generators as a vector of module elements is also problematic for modules with no generators. But perhaps we just disallow those. Not sure yet.

**Comment by thofma** [comment]
Yeah, we should define it on the ring side by doing `matrix_type(R::Ring) = matrix_type(elem_type(R))`.

**Comment by wbhart** [comment]
I just had a genius idea. Instead of defining dense_matrix_type(fmpz), why don't we define Mat(fmpz), Mat(Generic), Mat(Abstract)

This way we could also write things like:

function myfun1(a::Mat(fmpz), b::Mat(fmpz))

function myfun2(a::Mat(Generic), b::Mat(Generic))

function myfun3(a::Mat(Abstract), b::Mat(Abstract))

which would mean we'd never have to remember which was the generic type, which was the abstract one and which was the type for fmpz or whatever.

We could do the same for Poly and MPoly.

**Comment by wbhart** [comment]
Note this would just be an extension of what we already do for Map.

**Comment by thofma** [comment]
Using this approach, how do I get the type for all abstract matrices with element type `fmpz`, that is, the current `MatElem{fmpz}`? Or all `MatElem{T} where T <: FieldElem`?

**Comment by wbhart** [comment]
Mat(Abstract){fmpz} and Mat(Abstract){T} where T <: FieldElem. This works the same way as for Map.

**Comment by thofma** [comment]
I think it is quite confusing to mix functions and types in the signatures. In particular it is not intuitive that there is `Mat(fmpz)` and `Mat(Abstract){fmpz}`. Sometimes the element type is an argument and sometimes a parameter.

I don't understand how this improves upon the status quo. We now have `MatElem{fmpz}` for any matrix with element types `fmpz` and `MatElem{<: FieldElem}` for any matrix with field elements.

**Comment by thofma** [comment]
Sorry, maybe I sounded too negative. I just want to make sure that it is as easy to use as it is now. At the moment you just have to know about `MatElem`.
