### ISSUE TITLE
Other colon notations for views and submatrices

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#307]
Julia allows M[:, [1, 3]] to give columns 1 and 3, and M[:, 1:2:3].

**Comment by thofma** [comment]
Do we want to allow this? This will be tricky if want to make the view version of this work for flint matrices, right?

**Comment by wbhart** [comment]
Yes, there's no possible way to make it work for Flint matrices directly. But we could allow it to work generically by defining an indexing into existing matrices, as Julia surely does. Anyhow, Andreas complained that it isn't available.

**Comment by thofma** [comment]
I would also like to have it. Can you be a bit more specific about the approach you propose (for the view variant and flint matrices).

**Comment by wbhart** [comment]
I haven't thought it through, but I imagine it would be a lot like how Julia does it, with a type for views that contains enough info to have all these different possibilities. It would do it in some cases by simply looking up specific indices in the original matrix, i.e. overloading get/setindex for the view type. For example, to get just columns 1, 2, 5 you would write M[:, [1, 2, 5]] and this would store the matrix [1, 2, 5] in the view object, and use it as a lookup when doing get/setindex to know what actual column to be accessing in the original matrix.

**Comment by wbhart** [comment]
Yeah for views this obviously doesn't work, since the Flint functions require genuine Flint matrices. But I guess we should implement it for submatrices.

**Comment by wbhart** [comment]
What is missing now is to just take M[:, 2:3] without the @view. I'll leave this ticket open, to implement that, which is certainly supportable by Flint matrices. Julia makes a copy in this case, rather than a view.

**Comment by wbhart** [comment]
This seems to exist now, so I'm closing this issue.

I don't currently think we should support the submatrix and view notations that don't involve consecutive rows and columns (since we cannnot support it in Nemo). This is also a good argument against making our matrix types belong to AbstractMatrix.

I know @kalmarek suggested there was a way to support this, even in Nemo. But I don't recall what it is. If he remembers what he had in mind and it seems like it ought to work, then I'll reopen the ticket, in case someone wants to implement it.

But for now, I think we are done with what we can actually meaningfully support.

**Comment by kalmarek** [comment]
What I suggested was "accepting" any `AbstractMatrix` in our constructors (and functions) and not "supporting views in the most efficient manner possible", which is clearly a hard in finite time; With clearly defined separation between julia and external library this should be a meta-programming exercise, which (I remember) @wbhart doesn't like.

And as I previously mentioned, supporting views is totally orthogonal to subtyping `AbstractMatrix`

**Comment by wbhart** [comment]
Ah yes, this indeed makes sense. Thanks for clarifying.

I'm in favour of doing this.

**Comment by wbhart** [comment]
I will probably implement this today.

**Comment by wbhart** [comment]
Ok, I completely forgot that our constructors accept anything from AbstractMatrix now. We fixed this the other day. So I'm going to close this issue. Any specific functionality that is still missing can be requested on other tickets.
