### ISSUE TITLE
HNF still not reducing mod n correctly

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#311]
Here is an example that seems to indicate it is a divrem problem as before. But I can't find any cases of div, divrem that haven't been switched to AbstractAlgebra.divrem that could be causing it.

```
julia> M = matrix(ZZ, 2, 2, BigInt[0, 3, -7, -1])
[0 3]
[-7 -1]

julia> hnf(M)
[7 -2]
[0 3]
```

It seems to happen when swapping rows and changing signs of one of the rows is required.

**Comment by wbhart** [comment]
Note that there is a divrem in ishnf that I implemented that doesn't have AbstractAlgebra.divrem. But this is not relevant to the hnf code itself, and I've also fixed it in my local repo that I'm testing with anyway.

**Comment by thofma** [comment]
Do you have your changes in a branch? I would like to try it out.

**Comment by wbhart** [comment]
Yes, but this is independent of my changes. The example above is straight hnf, which I have not touched.

Anyhow, I'll commit and push my changes in a minute.

**Comment by wbhart** [comment]
I've pushed my changes to my branch modules_kernel.

**Comment by thofma** [comment]
Which repository? I can't find it.

**Comment by thofma** [comment]
Sorry, my bad. I found it.

**Comment by thofma** [comment]
I think it is a problem in the algorithm. I am looking into it.

**Comment by thofma** [comment]
The example is working correctly on the master branch, but is failing on your `modules_kernel` branch. Here is the result on the master branch:
```julia
julia> using Revise, AbstractAlgebra

julia> M = matrix(ZZ, 2, 2, BigInt[0, 3, -7, -1])
[0 3]
[-7 -1]

julia> hnf(M)
[7 1]
[0 3]
```
Now I am not sure it is a problem with the algorithm.

**Comment by wbhart** [comment]
I think this is from before we discussed it. Just to confirm, it fails in the official master.
