### ISSUE TITLE
multiplication of Puiseux series modifies inplace

### ISSUE THREAD

**Issue by martinra** [Nemocas/AbstractAlgebra.jl#319]
Here is an example:

```
using Nemo
CC = ComplexField(200);
R,x = PuiseuxSeriesRing(CC, 4, "x");
cs = [one(CC), zero(CC), one(CC), zero(CC)];
f = R(R.laurent_ring(cs, 4, 4, 0, 1, false), 2);
f
ff = f*f;
f
```

The reason for this is that inflate calls the constructor for Laurent series with rescale = true, and that one modifies in place via rescale! . The conceptual problem is that the constructor assumes that the coefficient vector is owned by noone else, but in the case of multiplication of Puiseux series it is. Since inflate (as opposed to inflate!) should not modify the vector, I think inflate should be adjusted. Alternatively, rename inflate to inflate! and send in a copy of the coefficient vector? Or inflate calls the constructor with rescale = false.

**Comment by wbhart** [comment]
I think you are right. Let's hope I can fix it without breaking anything else.
