### ISSUE TITLE
Implement functionality for getting exponents of a multivariate poly

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#32]
The interface for multivariate polys describes functions exponent and exponent! for sparse distributed formats with random access terms. We should implement these functions for generic polynomials, as they are already available for Singular polynomials.

In addition, we should implement functions for getting the coefficient and exponent vector of a term specified by its monomial (rather than its index in the array), and for setting the coefficient of such. This should be documented in the main, required interface for multivariate polynomials.

We should also decide how indexing of terms in a sparse distributed, random access polynomial should work. At present, the first term is given index 0, but this seems inconsistent with Julia's convention on array indices. On the other hand, it is consistent with the indexing of terms of a univariate, except that they are numbered from the least significant, rather than most significant term (for performance reasons in both cases). Also, the i-th term there is the degree i term, whereas there is no such meaning for multivariates.

**Comment by fieker** [comment]
On Tue, Feb 13, 2018 at 01:33:10PM +0000, wbhart wrote:
> The interface for multivariate polys describes functions exponent and exponent! for sparse distributed formats with random access terms. We should implement these functions for generic polynomials, as they are already available for Singular polynomials.

Not really... in Singular, you cannot really have random access as this
is a linked list. For convenience, an iterator is definitely good idea.
> 
> In addition, we should implement functions for getting the coefficient and exponent vector of a term specified by its monomial (rather than its index in the array), and for setting the coefficient of such. This should be documented in the main, required interface for multivariate polynomials.
> 
Agreed.
> We should also decide how indexing of terms in a sparse distributed, random access polynomial should work. At present, the first term is given index 0, but this seems inconsistent with Julia's convention on array indices. On the other hand, it is consistent with the indexing of terms of a univariate, except that they are numbered from the least significant, rather than most significant term (for performance reasons in both cases). Also, the i-th term there is the degree i term, whereas there is no such meaning for multivariates.
> 
With sparse stuff, direct indexing is always suboptimal and artificial.
For sparse matrices e.g. we obviously support A[i,j] for all i and j -
and it's mostly zero...
I think iterators are more natural here. With any indexing added
possibly for efficiency in some implementations.

My 2 pennies.
  Claus

**Comment by wbhart** [comment]
On 13 February 2018 at 16:03, Claus Fieker <notifications@github.com> wrote:

> On Tue, Feb 13, 2018 at 01:33:10PM +0000, wbhart wrote:
> > The interface for multivariate polys describes functions exponent and
> exponent! for sparse distributed formats with random access terms. We
> should implement these functions for generic polynomials, as they are
> already available for Singular polynomials.
>
> Not really... in Singular, you cannot really have random access as this
> is a linked list. For convenience, an iterator is definitely good idea.
>

You misread. It says " for sparse distributed formats **with random access
terms**" (emphasis added).

Take a look at the AbstractAlgebra.jl Multivariate Polynomial interface in
the documentation. This function is only required to be implemented for
specific kinds of multivariates, and certainly not Singular polynomials.

>
> > In addition, we should implement functions for getting the coefficient
> and exponent vector of a term specified by its monomial (rather than its
> index in the array), and for setting the coefficient of such. This should
> be documented in the main, required interface for multivariate polynomials.
> >
> Agreed.
> > We should also decide how indexing of terms in a sparse distributed,
> random access polynomial should work. At present, the first term is given
> index 0, but this seems inconsistent with Julia's convention on array
> indices. On the other hand, it is consistent with the indexing of terms of
> a univariate, except that they are numbered from the least significant,
> rather than most significant term (for performance reasons in both cases).
> Also, the i-th term there is the degree i term, whereas there is no such
> meaning for multivariates.
> >
> With sparse stuff, direct indexing is always suboptimal and artificial.
>

That's not correct. It is often required for performance. For some formats,
access via monomial is logarithmic time, instead of constant time, and
algorithmically, one can't use iterators in every situation. No one way of
accessing polynomials can be standard. There can be a standard way for
users, but it will be hopelessly inefficient for some representations.

There are representations, that we will use, that have linear time access
for the exponent vector by monomial accessor, for example. In some cases,
it's n log n access time. I'm pretty sure you would not put up with that
for long!


> For sparse matrices e.g. we obviously support A[i,j] for all i and j -
> and it's mostly zero...
> I think iterators are more natural here. With any indexing added
> possibly for efficiency in some implementations.
>

That's precisely what the current interface spells out, and what I'm
proposing here!

**Comment by wbhart** [comment]
Largely done.
