### ISSUE TITLE
Difference between F[X][Y] and F[X, Y]

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/AbstractAlgebra.jl#356]
Suppose i have a field F (or ring, etc..).
I can construct multivariate polynomials in several ways:
In two steps using `F["X"]["Y"]`
In one step using `PolynomialRing(F, ["X", "Y"])`

I thought this is essentially the same (they are obviously isomorphic). What is the reason that obtained objects are not the same? Is there any way to "standardize" the polynomial ring representation and/or check for isomorphism?

The same is true for number fields in Hecke. For example, 
`Q(i + sqrt(2)) != Q(sqrt(2))(i)` in Hecke. Is there any way to find primitive element in the field and represent the field as Q(alpha)?

**Comment by thofma** [comment]
Sometimes you want multivariates and sometimes you want univariate over univariate.


In Hecke you can do the following:
```julia
julia> K, (a1, a2) = NumberField([x^2 - 2, x^2 + 1], "a")
(Non-simple number field with defining polynomials fmpq_mpoly[a1^2 - 2, a2^2 + 1], NfAbsNSElem[a1, a2])

julia> a1^2
2

julia> L, mL = simple_extension(K)
(Number field over Rational Field with defining polynomial x^4-2*x^2+9, Map with following data
Domain:
=======
Number field over Rational Field with defining polynomial x^4-2*x^2+9
Codomain:
=========
K
)

julia> mL(gen(L))
a1 + a2

julia> mL\(a1)
-1//6*_a^3 + 5//6*_a

julia> ans^2
2
```

**Comment by kirtsar** [comment]
Nice, thanks!

**Comment by thofma** [comment]
Minor caveat, if you do it directly with multiple univariate polynomials, they must intersect trivially. So `NumberField([x^2 - 2, x^2 - 2])` won't work.

One can circumvent this by just stacking the number fields and then making it a simple extension of the rationals:
```julia
julia> Qx, x  = PolynomialRing(FlintQQ, "x");
K
julia> K, a = NumberField(x^4 - x^2 + 1, "a")
(Number field over Rational Field with defining polynomial x^4-x^2+1, a)

julia> Ky, y = K["y"]
(Univariate Polynomial Ring in y over Number field over Rational Field with defining polynomial x^4-x^2+1, y)

julia> L, b = NumberField(y^2 + 3, "b")
(Relative number field over
Number field over Rational Field with defining polynomial x^4-x^2+1
 with defining polynomial y^2+(3), b)

julia> Labs, mL = absolute_field(L);

julia> Labs
Number field over Rational Field with defining polynomial x^8+10*x^6+51*x^4+94*x^2+169

julia> mL
Morphism between Number field over Rational Field with defining polynomial x^8+10*x^6+51*x^4+94*x^2+169
and Relative number field over
Number field over Rational Field with defining polynomial x^4-x^2+1
 with defining polynomial y^2+(3)
```
