### ISSUE TITLE
docstring of function evaluate(a::MPoly{T}, A::Vector{T}) does not coincide with its signature

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#358]
in https://github.com/Nemocas/AbstractAlgebra.jl/blob/893bd917c67860753e60d9998c7b93978c61c4e5/src/generic/MPoly.jl#L3317

**Comment by thofma** [comment]
Do you mean `Vector{T}` versus `Array{T, 1}`?

**Comment by heiderich** [comment]
Yes.
