### ISSUE TITLE
Tricky matrix manipulations

### ISSUE THREAD

**Issue by kirtsar** [Nemocas/AbstractAlgebra.jl#367]
It is really tricky to obtain the row or the column of a matrix. 
```
using SpecialMatrices
using AbstractAlgebra

Zq = ResidueRing(ZZ, 17)
x = Zq.([1,2,3])
C = Circulant(x)
Mat = MatrixSpace(Zq, 3, 3)
Cq = Mat(C)          # not working
Cq = Mat(Matrix(C))  # works fine
Cq^(-1)              # not working
Cinv = inv(Cq)       # works fine, gives circulant matrix
# now I want to extract the first column from Cinv, this is the trickiest part
Cinv[:, 1]           # NOT WORKING??
Cinv[:, 1 : 1]       # works, but can't convert this thing into usual vector
```

**Comment by wbhart** [comment]
```
using SpecialMatrices
using AbstractAlgebra

Zq = ResidueRing(ZZ, 17)
x = Zq.([1,2,3])
C = Circulant(x)
Mat = MatrixSpace(Zq, 3, 3)
Cq = Mat(C)          # not working
Cq = Mat(Matrix(C))  # works fine
```

This suggests it wasn't an ordinary Julia multidimensional array, which our code currently requires. I don't think it would be difficult to fix this though. Perhaps we even only need to accept AbstractArray or something like that, and the existing code might Just Work TM.

```
Cq^(-1)              # not working
```

That definitely seems like a bug. We will investigate.

```
Cinv = inv(Cq)       # works fine, gives circulant matrix
# now I want to extract the first column from Cinv, this is the trickiest part
Cinv[:, 1]           # NOT WORKING??
```
We can't support all Julia row/column operations, unfortunately. We could probably do so in AbstractAlgebra, but then when people upgrade to Nemo, it would stop working. It's not possible to pass arbitrary slices of matrices to C functions in C libraries that don't support it. The Julia slicing operators are designed with only Julia arrays in mind, essentially assuming all matrices are going to use generic Julia code. So there's not a lot we can do about this, sorry.

```
Cinv[:, 1 : 1]       # works, but can't convert this thing into usual vector
```

**Comment by wbhart** [comment]
Having said that, we probably could support the Cinv[:, 1] syntax. Up until now, I was not even aware it existed.

**Comment by thofma** [comment]
Will be fixed in the next release.

**Comment by wbhart** [comment]
Just to summarise:

* Cinv[:, 1] will be fixed in the next release.

* Cq = Mat(C) will be fixed in the next release.

* Cq^-1 will be fixed in the next release

* Cinv[: 1, 1] could you give an example of what you would expect to work here. It wasn't completely clear what you meant. Even in Julia this syntax would return a 2 dimensional array.

**Comment by wbhart** [comment]
By next release we mean the one after the one we just did. Sorry.
