### ISSUE TITLE
Make MatrixElem belong to AbstractArray{T, 2}

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#417]
As our matrix types now no longer belong to Module (this turned out to be a bad idea), we could in theory make them members of Julia's AbstractArray class. This might be useful for various purposes.

Of course, some Julia functionality probably won't work because of zero and one not being defined for the (entry) element types, but it might make some things easier for both us and the Julia folks.

**Comment by rfourquet** [comment]
Sorry for this newbie question, but currently `MatElem <: GroupElem`, so do you mean to break that to inherit instead from `AbtractMatrix` ?

Also is there a specific reason we can't support `zero` and `one`? I just ran into this missing methods today.

**Comment by thofma** [comment]
Julia expects at various places to have `zero` working on the type. This does not work for us.

**Comment by thofma** [comment]
On our case the type does not determine the return value. Think of `GF(2)` and `GF(3)`.

**Comment by rfourquet** [comment]
> Julia expects at various places to have zero working on the type. This does not work for us.

Ah of course, thanks! My example was `zero(fmpz)` where this problem doesn't exist.

**Comment by wbhart** [comment]
Sure, but I'm wondering if it is worth doing anyway, as most Julia people are coming to our system to use matrices over ZZ and QQ. I guess it could also be a motivation for them to clean up base so that it does zero(A[1, 1]) instead of zero(T), as we previously discussed with them.

**Comment by wbhart** [comment]
Another thing we could do is define zero and one for the types. E.g. for Z/nZ we could return 0 in Z/1Z. This would provide further motivation for them to sort this out.

**Comment by fieker** [comment]
On Wed, Sep 25, 2019 at 05:45:29AM -0700, wbhart wrote:
> Sure, but I'm wondering if it is worth doing anyway, as most Julia people are coming to our system to use matrices over ZZ and QQ. I guess it could also be a motivation for them to clean up base so that it does zero(A[1, 1]) instead of zero(T), as we previously discussed with them.
> 
Does not work on empty matrices/ arrays...

**Comment by fieker** [comment]
On Wed, Sep 25, 2019 at 05:47:19AM -0700, wbhart wrote:
> Another thing we could do is define zero and one for the types. E.g. for Z/nZ we could return 0 in Z/1Z. This would provide further motivation for them to sort this out.
> 
> -- 
Do you really want "universal" zero and one for all types?
AnticNumberField?

any operation then needs to checl if one/both/some input is zero or one
and hope it makes sense. What is the trace of the universal 1? The
degree of the parent?

**Comment by thofma** [comment]
Don't think they care. Base is full of `zero(T)` and its usage is increasing.

**Comment by thofma** [comment]
I am happy to add it for `fmpq` and `fmpz` and all element types with unique parents and throw errors for everything else :)

**Comment by wbhart** [comment]
@thofma That's an even better idea.

@fieker The idea is they deal with that case separately, i.e. they should not need to create zero or one in such cases.

**Comment by wbhart** [comment]
I'm adding the JuliaCommunity tag because this is an improvement that may be useful to the wider community, but not something that is high priority for us right now.

**Comment by fingolfin** [comment]
`MatElem` is a subtype of `ModuleElem` so we can't do this without breaking this chain..

I think at this point we have really settled on the idea that it is better to not provide a partial (and partially broken) implementation of Julia abstract "interfaces" like `AbstractMatrix` -- better to make it crystal clear that it works different.

As such I'd say we should close this.

**Comment by lgoettgens** [comment]
Agreed
