### ISSUE TITLE
Error in new map function

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#423]
Seen at: https://ci.appveyor.com/project/thofma/abstractalgebra-jl/builds/27665733/job/9l3a4wvaetci1ncb

@rfourquet

**Comment by rfourquet** [comment]
That's a quite tricky test failure.
I have a kinda minimal repro:
```julia
julia> m = rand(Int, 0, 0)
       for R = [ZZ]
           f = x -> one(R)
           @show map(f, m)
       end
map(f, m) = Array{BigInt}(undef,0,0)

julia> m = rand(Int, 0, 0)
       R = ZZ
       f = x -> one(R)
       @show map(f, m)

map(f, m) = Array{Any}(undef,0,0)
0×0 Array{Any,2}
```
So basically the loop helps inference (at least this is how I understand it), but what is unclear is that in the tests, there is a loop, so I don't understand why they fail nor why they would pass in other CI runs.
Anyway, I will fix the tests to guard against this failure.
