### ISSUE TITLE
Implement identity_matrix(::Ring, Int, Int)

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#435]
I don't see any reason to not implement it. I just spent some time trying to remember the name of this function, only to realise it only takes one Int argument.

**Comment by thofma** [comment]
Could you elaborate on what it should do?

**Comment by rfourquet** [comment]
Presumably like what `eye` does with non-square matrices. Related: https://github.com/Nemocas/AbstractAlgebra.jl/issues/258.

**Comment by wbhart** [comment]
I don't really mind if it raises an error for non-square matrices. But for square matrices, it would be nice if it just matched the zero_matrix syntax. 

I see why people might be reluctant to accept non-square matrices, and I don't care about that much. Though it would be nice if the error message told people how to get a matrix with 1's down the "diagaonal" (starting at the upper left), which is presumably what they would want if they were calling this function for nonsquare matrix.

**Comment by wbhart** [comment]
First see if there is support for the idea, otherwise we drop it.

**Comment by thofma** [comment]
I am supporting the idea of making `identity_matrix(R, n, m)` return a rectangular matrix with 1's down the "diagonal".

(Apparently in Sage one has `identity_matrix(R, n, m) = identity_matrix(R, max(n, m))`. Magma only has the "one integer" version.)

P.S.: We should use this chance to also get rid of `eye` (Base already removed it).

**Comment by wbhart** [comment]
Gosh, is eye still there! I thought I killed it more than once by now!

**Comment by wbhart** [comment]
What does @fieker think of @thofma's suggestion?

**Comment by wbhart** [comment]
We currently have eye(M) where M is a matrix. Should we implement identity_matrix(M)? Or should we implement identity_matrix(S) where S is the matrix space? Or both?

**Comment by rfourquet** [comment]
What about following `LinearAlgebra`'s way, with `I`?
```julia
julia> using LinearAlgebra: I

julia> Array{Int}(I, 2, 3)
2×3 Array{Int64,2}:
 1  0  0
 0  1  0

julia> matrix(ZZ, 2, 3, I) # possible API
[1  0  0]
[0  1  0]
```

**Comment by thofma** [comment]
For creating something filled with zeros we have `zero(M)` or `zero(M, r, c)`. Don't how bad the mismatch with `identity_matrix(M)` would be.

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 05:36:40AM -0700, wbhart wrote:
> What does @fieker think of @thofma's suggestion?

a: I don't mind
b: I can't see any reason for a non-square identity...
   as long as the one-int version also works.

**Comment by thofma** [comment]
What is the one-int version?

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 06:33:25AM -0700, thofma wrote:
> What is the one-int version?
identity_matrix(ZZ, 2)
to get a 2x2 matrix
