### ISSUE TITLE
(New) Bug in HNF

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#438]
```
julia> using AbstractAlgebra
julia> M = matrix(ZZ, BigInt[4 6 2; 0 0 10; 0 5 3])
[4  6   2]
[0  0  10]
[0  5   3]

julia> hnf(M)
[4  1  -1]
[0  5   3]
[0  0  10]
```

It's possible I misunderstand something, but this (the -1) doesn't look right to me.

```
julia> AbstractAlgebra.divrem(-1, 10)
(-1, 9)
```

**Comment by thofma** [comment]
@joschmitt Could you have a look?

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 05:33:18AM -0700, wbhart wrote:
> ```
> julia> using AbstractAlgebra
> julia> M = matrix(ZZ, BigInt[4 6 2; 0 0 10; 0 5 3])
> [4  6   2]
> [0  0  10]
> [0  5   3]
> 
> julia> hnf(M)
> [4  1  -1]
> [0  5   3]
> [0  0  10]
> ```
> 
> It's possible I misunderstand something, but this (the -1) doesn't look right to me.
it is "a" "legal" hnf. 
If the normalisation actually promised and documented? or just assumed?

**Comment by wbhart** [comment]
It's promised but not documented. In fact, nothing is documented for hnf, other than it is upper right row.

Clearly we can and should support unicity where possible as it is much more useful.

**Comment by wbhart** [comment]
Especially since it likely indicates a bug in the code as currently intended.

**Comment by joschmitt** [comment]
I think the function was not supposed to compute this normalized form when I wrote it some years ago.
Anyway, I guess I know what the problem is. I will look at it tomorrow in more detail.
