### ISSUE TITLE
Problem with hnf_with_transform() ?

### ISSUE THREAD

**Issue by arbenede** [Nemocas/AbstractAlgebra.jl#440]
I am trying to compute the HNF of a rational matrix as follows:
```julia
R = MatrixSpace(QQ, 4, 4)
lambda = Matrix([2//1 3//1 5//1 7//1])
lambda_bar = 1 .// lambda
plambda_bar = lambda_bar' .// dot(lambda_bar,lambda_bar)
A = Matrix{Rational}(I, 4, 4) - plambda_bar*lambda_bar
RA = R(A)

H, U = hnf_with_transform(RA)
```
however I am getting this error:
```
MethodError: no method matching gcdx(::Rational{BigInt}, ::Rational{BigInt})

Stacktrace:
 [1] hnf_kb!(::AbstractAlgebra.Generic.MatSpaceElem{Rational{BigInt}}, ::AbstractAlgebra.Generic.MatSpaceElem{Rational{BigInt}}, ::Bool, ::Int64) at C:\Users\arbenede\.julia\packages\AbstractAlgebra\y3sVP\src\generic\Matrix.jl:3660
 [2] hnf_kb! at C:\Users\arbenede\.julia\packages\AbstractAlgebra\y3sVP\src\generic\Matrix.jl:3632 [inlined]
 [3] _hnf_kb at C:\Users\arbenede\.julia\packages\AbstractAlgebra\y3sVP\src\generic\Matrix.jl:3514 [inlined]
 [4] hnf_kb_with_transform at C:\Users\arbenede\.julia\packages\AbstractAlgebra\y3sVP\src\generic\Matrix.jl:3506 [inlined]
 [5] hnf_with_transform(::AbstractAlgebra.Generic.MatSpaceElem{Rational{BigInt}}) at C:\Users\arbenede\.julia\packages\AbstractAlgebra\y3sVP\src\generic\Matrix.jl:3724
 [6] top-level scope at In[18]:1
```

Any ideas?

**Comment by thofma** [comment]
This should not error.

Note that since this is over a field, the result will be the same as `rref`.

**Comment by wbhart** [comment]
It's weird because gcdx is defined by Julia itself.

I wonder if they took it out of Base? Or maybe we are exporting ours by mistake somewhere?

**Comment by wbhart** [comment]
@arbenede Can you tell me what the definition of dot is? The code example you gave doesn't work without it.

Sorry if this is a dumb question, but I am not a numerical person, so I don't know where this would be coming from.

**Comment by thofma** [comment]
You get it after doing `using LinearAlgebra`.

**Comment by wbhart** [comment]
I simply don't understand why this happens. The function gcdx is defined by Julia for BigInt and we import that function in both Generic (where it is being used here) and in AbstractAlgebra.

I think this is a Julia bug, as far as I can see.

I do note that we import gcdx from Generic after importing it from Base. But given that it was imported from Base in Generic, this surely isn't an issue.

I can try exporting it from Generic maybe? But otherwise I don't see how to fix this.

**Comment by wbhart** [comment]
Nope, that doesn't help.

I don't have a clue what is behind this bug.

**Comment by wbhart** [comment]
Unfortunately I cannot fix this issue as I cannot dev AbstractAlgebra at the moment. Julia simply doesn't allow you to dev a package if you have other packages that depend on it without a compatible version.

Someone else who is only working on AbstractAlgebra and not Oscar or Singular will have to look at this (which I find remarkable and annoying, but that is how it is).

**Comment by thofma** [comment]
I will have a look.
