### ISSUE TITLE
Evaluate MPoly with map of coefficients

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#453]
Here is something I stumbled upon when cleaning up `change_base_ring/map`.

We have some methods that allow for example:
```julia
julia> Zx, (x1,x2) = PolynomialRing(ZZ, ["x1", "x2"]);

julia> evaluate(x1 + x2, [1, 2], [1//2, 1//3], QQ)
5//6
```
The last argument is applied to all coefficients via `map_coeffs` and then it is evaluated. Do we really need this? This leads to some weird looking errors:
```julia
julia> evaluate(x1 + x2, [1, 2], [1, x1])
ERROR: MethodError: objects of type Array{Any,1} are not callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] map_coeffs(::Array{Any,1}, ::AbstractAlgebra.Generic.MPoly{BigInt}) at /tmp/new/dev/AbstractAlgebra/src/generic/MPoly.jl:4675
 [2] evaluate(::AbstractAlgebra.Generic.MPoly{BigInt}, ::Array{Int64,1}, ::Array{Any,1}) at /tmp/new/dev/AbstractAlgebra/src/generic/MPoly.jl:3508
 [3] top-level scope at REPL[4]:1
```
This is because there is no method with `Array{Any}` (the type of `[1, x1]`) as the last argument, so it falls back to the "apply last argument to the coefficients" version.

I personally think that writing `evaluate(change_base_ring(QQ, x1 + x2), [1, 2], [1//2, 1//3]))` is much clearer than `evaluate(x1 + x2, [1, 2], [1//2, 1//3])`, but I don't have strong feelings about this.

I am also happy to keep it, but should we then make the "function" argument the first argument?

**Comment by wbhart** [comment]
I don't mind if you remove this. It will potentially be a performance drag to remove it, but we can't go supplying every function the user might think they need. Unless it is really performance critical, I favour orthogonal behaviour.

I actually don't recall why I implemented it that way. There must have been a reason, but it is likely just that we didn't have change_base_ring back then and I didn't see a good way to implement that.

**Comment by thofma** [comment]
I also favour orthogonal behaviour. Concerning the performance. It actually is (and was) defined to be
```julia
evaluate(f, vars, vals, g) = evaluate(map_coeffs(g, f), vars, vals)
```
so there is no performance drag (it was `change_base_ring` instead of `map_coeffs` before).

I think it also predates the more complex evaluation functionality that you implemented. With this mind, I read from your post that you would also be in favor of remove it.

I will then go ahead and remove it if no one speaks up.
