### ISSUE TITLE
Docstring oddities

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#467]
I've noticed the appearance of docstrings in AbstractAlgebra (primarily in Matrix.jl) which give the return values in the prototype for the docstring. Is this actually supported by the Documenter?

In any event, I think we need uniformity, and a handful of such cases is a bad idea given that none of the other docstrings have this. We went to quite some trouble to check that the docstring matched the function prototype as much as possible (so that this could be checked automatically).

Also I note that some docstrings introduce an empty line after the prototype but before the actual docstring itself. Again, I'm not in favour of this on the grounds of uniformity.

**Comment by thofma** [comment]
What does "supported by Documenter" mean? You can put anything in the docstrings.

**Comment by rfourquet** [comment]
> I've noticed the appearance of docstrings in AbstractAlgebra (primarily in Matrix.jl) which give the return values in the prototype for the docstring

This is a pattern in Julia `Base`.

> In any event, I think we need uniformity, and a handful of such cases is a bad idea given that none of the other docstrings have this.

This happens also in `Base`. Personally, I prefer having this information only sometimes than never. 

> Also I note that some docstrings introduce an empty line after the prototype but before the actual docstring itself

I agree that uniformity on this point would be good. But, is there any reason we don't use the "usual" format for dosctrings?
```julia
"""
    foo(x)

Here comes `foo` docstring which takes an `x`.
"""
foo(x) = 1
```

**Comment by wbhart** [comment]
By all means go through and change our docstrings to the "usual" format, even though apparently the docstrings can contain "anything".

I see all this code churn as being entirely counterproductive. When I contribute to someone's project, I try to follow every possible convention that I observe. I do not try to impose conventions from other projects. I even go to the extent of trying to mimic their style of coding, down to the syntax, the naming of functions and variables, formatting, the insane levels of minutiae that they attend to, both algorithmically and in coding style, how functions are broken up, etc. Isn't this just part of being a good Open Source contributor?

**Comment by wbhart** [comment]
Do we wish to follow the Julia Base conventions of:

1. Blank line after prototype
2. Omit > character
3. Including the return type of functions in the docstring

**Comment by thofma** [comment]
Fine with me. I think we tried to do this in Hecke.

**Comment by rfourquet** [comment]
> Do we wish to follow the Julia Base conventions of:

Yes!

> Omit > character

The `>` character is occasionally annoying when you reword a docstring which changes line-breaks, you have to manually add or delete `>`, and some spurious `>` can appear in docstrings in the middle of a line as a result.

This will help also for a more consistent docstring among Oscar packages, as `>` means that a vertical line is printed. For example, the docstring of `divexact` contains:
```julia
divexact(x::fmpz_laurent_series, y::T) where {T <: RingElem}

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

   divexact(a::LocElem{T}, b::LocElem{T}, checked::Bool = true)  where {T <: RingElem}

  Returns element [...]
```
I'm happy to (try to) write a regex to do this change automatically.

> Including the return type of functions in the docstring

Even in Julia Base, the convention is not fully consistent. Sometimes `-> Int` at the end of the prototype indicates the return type, sometime `-> A` indicates that an object named `A` will be returned (`A` can be an argument, or defined in the docstring itself). At least this is my impression.

**Comment by wbhart** [comment]
> I'm happy to (try to) write a regex to do this change automatically.

Great! Do you want to take over this ticket? I'm ok with the changes, so long as they are uniformly applied.

**Comment by rfourquet** [comment]
Yes I will do.

**Comment by wbhart** [comment]
I assume this ticket can be closed?
