### ISSUE TITLE
MatrixAlgebra-test.jl tests zero_matrix/identity_matrix even though no MatrixAlgebra is created

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#470]
(Leaving aside the fact that I prefer not to document return types anyway....) The docs for these functions currently say the return type is MatrixElem. But these functions can only return MatSpaceElem's.

This is compounded by the fact that MatrixAlgebra-test.jl now tests these functions, which is useless, since there is no way to create a MatAlgElem with these functions. So it's just duplicated test code.

**Comment by thofma** [comment]
After using Nemo, these functions will not return MatSpaceElem. I personally think that writing something like
```
    zero_matrix(R::Ring, n::Int, r::Int) -> MatrixElem
```
is perfectly fine and not wrong. In all cases you get something which is a MatrixElem.

I don't know how one would do it otherwise when writing the docstring for generic implementations that work for input of type MatrixElem.

Almost all docstrings should be free of MatSpaceElem, since almost all methods are generic.

**Comment by fieker** [comment]
On Mon, Oct 07, 2019 at 05:01:35AM -0700, wbhart wrote:
> (Leaving aside the fact that I prefer not to document return types anyway....) The docs for these functions currently say the return type is MatrixElem. But these functions can only return MatSpaceElem's.

I actually prefer to see the types - it shows what to expect, in
particular, how many arguments are returned.
If the information is correct, its a bonus...

(e.g. does it return an Int, BigInt, fmpz?)

**Comment by wbhart** [comment]
> On Mon, Oct 07, 2019 at 05:01:35AM -0700, wbhart wrote: (Leaving aside the fact that I prefer not to document return types anyway....) The docs for these functions currently say the return type is MatrixElem. But these functions can only return MatSpaceElem's.
> I actually prefer to see the types - it shows what to expect, in particular, how many arguments are returned. If the information is correct, its a bonus... (e.g. does it return an Int, BigInt, fmpz?)

Fine. But then we need to undertake a project to change them all. Just changing a few here or there is just going to cause confusion for our users.

Of course my personal approbation of such an undertaking is dependent on it actually being supported by the Documenter!

**Comment by rfourquet** [comment]
> The docs for these functions currently say the return type is MatrixElem

It's actually `MatElem` in the docstring, which excludes matrix algebras. So `MatElem` seems to be the correct abstract type.

**Comment by thofma** [comment]
Sorry, I am having a hard time following the "supported by Documenter". Could you elaborate on this?

**Comment by wbhart** [comment]
@rfourquet Thanks. I apparently got this wrong.

@thofma According to what you just wrote, it doesn't matter, as anything can go in the docstrings. I find that hard to believe, as Documenter has to have some kind of format. But perhaps I should have asked this more directly as a question, as I don't know what restrictions Documenter may impose. I thought we were more or less using the only possible syntax. But I'll take it from your response elsewhere that this is not the case.

**Comment by wbhart** [comment]
I'll leave the ticket open to deal with my second issue which I think is real.
