### ISSUE TITLE
divexact_left and divexact_right implemented in the wrong place

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#473]
Does anyone know why divexact_left and divexact_right are implemented for MatrixElem in MatrixAlgebra.jl instead of Matrix.jl?

It's probably me that did this, but I want to check someone else didn't do it for a specific reason, before I move the implementation over to the other file (or change it to only apply to MatAlgElem's).

**Comment by fieker** [comment]
On Mon, Oct 07, 2019 at 05:38:30AM -0700, wbhart wrote:
> Does anyone know why divexact_left and divexact_right are implemented for MatrixElem in MatrixAlgebra.jl instead of Matrix.jl?
> 
> It's probably me that did this, but I want to check someone else didn't do it for a specific reason, before I move the implementation over to the other file (or change it to only apply to MatAlgElem's).
> 

Matrices are no ring, thus division does not apply.

**Comment by wbhart** [comment]
Ok, but then why implement them for MatrixElem and not MatAlgElem?

**Comment by fieker** [comment]
On Mon, Oct 07, 2019 at 01:24:19PM -0700, wbhart wrote:
> Ok, but then why implement them for MatrixElem and not MatAlgElem?
I don't know who and when this was added.
Possible they predate MatAlgElem?

**Comment by wbhart** [comment]
If I understand Git blame correctly, I implemented it that way de nuovo
and @thofma merged it.

So I'll change it to only work with matrix algebras and see if the test
code passes. If not, I'll move it to Matrix.jl, assuming we had some kind
of reason for it at the time.
