### ISSUE TITLE
Move map for Poly into Poly.jl

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#479]
We have it for MPoly and Matrix, so why not?

**Comment by thofma** [comment]
Oops, it was on my list but I overlooked it.

*map_coeffs :)

**Comment by thofma** [comment]
Wait, I actually did it. It is there.

**Comment by wbhart** [comment]
Where? I looked in Poly.jl and map and change_base_ring don't appear.

Are you sure you didn't do it in Hecke or something?

**Comment by rfourquet** [comment]
It's in Rings.jl. You can find that out with `methods(map_coeffs)`.

**Comment by wbhart** [comment]
Thanks @rfourquet 

Does anyone object if I move it into Poly.jl? @thofma ?

**Comment by thofma** [comment]
No, I did not put it here. I just updated it.

**Comment by wbhart** [comment]
Ok, PR incoming.
