### ISSUE TITLE
Symbols instead of Strings when constructing polynomial rings

### ISSUE THREAD

**Issue by daviddelaat** [Nemocas/AbstractAlgebra.jl#48]
Since the names of the variables of polynomials are stored and retrieved (using the vars function) as Symbols, would it be better for the constructors of polynomial rings to also use Symbols instead of Strings? I think it is more consistent.

**Comment by wbhart** [comment]
You aren't the only one to suggest this. It would mean changing a lot of
code if we change it. So we haven't decided yet.

We could of course just support both, but we are planning on massively
increasing the number of constructors for MPoly's, so this might end up
being overkill.

**Comment by fieker** [comment]
On Fri, Feb 16, 2018 at 12:21:33PM -0800, David de Laat wrote:
> Since the names of the variables of polynomials are stored and retrieved (using the vars function) as Symbols, would it be better for the constructors of polynomial rings to also use Symbols instead of Strings? I think it is more consistent.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/AbstractAlgebra.jl/issues/48


I'd suggest to also to

gens
ngens on the ring

gens ad ngens can easily be supported to al structures that are fin. gen
 - vector spaces
 - modules
 - groups
 - ...

vars and nvars does not make sense here.
Also rank comes to mind for multivariate function fields and poly
rings...


Symbols vs. Strings:
 - ultimately both
 - and, most importantly: NONE. I think there need to be constructors
   that choose some sensible/unique/bizarre names.
   Too frequently, in the applications, no-one is interested in names,
   (or printing) having to name them explicitly is then work one is not
   interested in...
   Of course, printing is sub-optimal then.

Claus

**Comment by wbhart** [comment]
This could be implemented by making the main version accept symbols and then just wrapping it with one that accepts strings/chars.
