### ISSUE TITLE
Laurent series addition yields alised coefficients

### ISSUE THREAD

**Issue by martinra** [Nemocas/AbstractAlgebra.jl#484]
The differences at the end should be zero:

```
R,x = LaurentSeriesRing(QQ,20,"x")
a = sum(n*x^n for n in 1:17)
b = 83 + 43*x^10 + O(x^20)
c = a + b
ccp = deepcopy(c)
addeq!(a,b)
c-a
c-ccp
```
The origin seems to be l. 1455 of LaurentSeries.jl where coefficients of a and b are alised with those of c. As a consequence, computing a+b makes it incorrect to later employ a or b in inplace arithmetics.

**Comment by wbhart** [comment]
Yes, this looks like a bug. Arithmetic operations such as + shouldn't return results that are in any way aliased with inputs.

I'll try to fix this tomorrow.

**Comment by wbhart** [comment]
By the way, you should always write a = addeq!(a, b), otherwise immutable things can't be supported. However, that isn't relevant to the failure.

**Comment by wbhart** [comment]
... where, by tomorrow, I meant mañana
