### ISSUE TITLE
Converting an AbstractAlgebra.jl matrix into a Julia array

### ISSUE THREAD

**Issue by arbenede** [Nemocas/AbstractAlgebra.jl#485]
How does one convert an AbstractAlgebra.jl matrix into a Julia array? I have not found any hints about this in the documentation.

Thanks

**Comment by wbhart** [comment]
If M is such a matrix, you can get at the underlying Julia array with A.entries.

Of course there's no guarantee that will continue to be supported, but you can just generate the result, which should always word:

A = [M[i, j] for i in 1:nrows(M), j in 1:ncols(M)]

**Comment by fieker** [comment]
On Tue, Oct 08, 2019 at 03:29:48PM -0700, arbenede wrote:
> How does one convert an AbstractAlgebra.jl matrix into a Julia array? I have not found any hints about this in the documentation.
> 

Sorry, in Hecke:
julia> Array(matrix(FlintZZ, 2, 3, [1,2,3,4,5,6]))
2×3 Array{fmpz,2}:
 1  2  3
 4  5  6

julia> @which Array(matrix(FlintZZ, 2, 3, [1,2,3,4,5,6]))
 (::Type{Array})(a::fmpz_mat) in Hecke at
/home/fieker/.julia/dev/Hecke/src/Misc/Matrix.jl:160

**Comment by thofma** [comment]
Could candidate for a move to AbstractAlgebra. We should probably support both the `Matrix(A)` and `Array(A)` syntax.

**Comment by wbhart** [comment]
Certainly ok. Maybe we should make a ticket with a list of items to be moved each time one comes up, then they can be handled as people have Spare Time TM.
