### ISSUE TITLE
vars and nvars for MPolyElem{T}

### ISSUE THREAD

**Issue by daviddelaat** [Nemocas/AbstractAlgebra.jl#49]
For elements of type `MPolyElem{T}` the method `nvars` is implemented, but `vars` is not, so one has to use `vars(parent(p))`. I think either both or neither should be implemented. (I think it would be nice to have `vars` available.)

**Comment by wbhart** [comment]
Should it return the number of variable of the ring, or the actual number of variables used in that particular polynomial?

**Comment by wbhart** [comment]
Sorry I mean, should it return the variables for the ring or the poly.

**Comment by daviddelaat** [comment]
I was thinking the number of variables in the ring, but I hadn't thought about this ambiguity. So maybe it's better to only implement these functions for the ring?

**Comment by wbhart** [comment]
At the moment I'm leaning towards that, at least until we decide what to do
exactly.

**Comment by wbhart** [comment]
Yes, I think that's the only reasonable thing here. We'll have to add some more methods for substitution of only certain variables, since that is also a reasonable use case.

**Comment by wbhart** [comment]
By the way, there is already:

evaluate(f, [1, 2, 3])

Obviously we should fix it so that f(1, 2, 3) works!

**Comment by thofma** [comment]
I agree. `vars` and `nvars` are too ambiguous for elements. They should be defined for the parent.
