### ISSUE TITLE
lc for multivariates but lead for univariates

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#508]
We should unify these names, as it is not helpful for users.

See e.g. issue https://github.com/Nemocas/Nemo.jl/issues/662

**Comment by fieker** [comment]
On Wed, Oct 16, 2019 at 12:24:04PM -0700, wbhart wrote:
> We should unify these names, as it is not helpful for users.
> 
> See e.g. issue https://github.com/Nemocas/Nemo.jl/issues/662
Definitely - and please not lc. lc is one of the precious 2-letter
combinations that I would rather reserve for users and not the system.
leading_coefficient would be my favourite, any user is welcome to say
lc = leading_coefficient
but lead_coeff or similar would be fine as well.

**Comment by wbhart** [comment]
You'll have to argue the toss with the Singular people. It's called lc because that's what they wanted. There's a whole series of these, lc, lm, lt, etc.

**Comment by fieker** [comment]
On Thu, Oct 17, 2019 at 01:36:22AM -0700, wbhart wrote:
> You'll have to argue the toss with the Singular people. It's called lc because that's what they wanted. There's a whole series of these, lc, lm, lt, etc.

I know - and I'll talk to them. IN particular lt "less than" is not a
good abbreviation if you want to be more general

**Comment by rfourquet** [comment]
Not that I believe that my opinion matters, but I find that names like `lc` and `lt` is a no-go here in a quite general system. And it's not in line with many other names which limit abbrevations and are rather self descriptive, `lead_coeff` or `leading_coefficient` or `leading_coeff` (`coeff` is already a function) would fit better. If I'm not mistaken, even in Singular there is `leadcoef` instead of `lc` etc.

**Comment by wbhart** [comment]
Ok, I agree with the changes here, but what was the response from the Singular people? Do we have permission to make this change? It removes what was essentially a feature request from Singular.jl (they explicitly wanted these names because they are used so often).

We need a final decision on this and I'll handle the PR's.

**Comment by wbhart** [comment]
Note that in Nemo we currently have lead and trail:

```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring, x)

julia> lead(2x^2 + 3x + 1)
2

julia> trail(2x^2 + 3x + 1)
1
```

so the changes will be more invasive if we go for lead_coeff and trail_coeff.

**Comment by wbhart** [comment]
By the way, when there is an iterator, one can always do first(coeffs(f)) instead of lead_coeffs(f).

But note that univariates have terms in the reverse order to multivariates in a single variable (for lex ordering).

**Comment by fieker** [comment]
The Singular people (ie, THE BOSS) decided that leading_coefficient is fine and lc can become history
