### ISSUE TITLE
Documentation of YoungTableaux and Characters is missing

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#51]
I had a feeling we had documentation for these somewhere, but I don't even see them in Nemo.jl.

Perhaps @kalmarek knows what has happened here.

I also noticed that eye(::perm) was documented, but didn't exist. The PermGroups documentation also says there's lots of ways to construct permutations, then doesn't give any. I added an obvious one to the docs, but there are surely more.

**Comment by kalmarek** [comment]
I don't think I touched `docs/src/perm.md`. I will try to update it in the comming weeks (new semester, less teaching)

**Comment by wbhart** [comment]
That would be great. You might like to think about whether there should
also be a Groups interface like we have for Rings [1].

The pull request should be against AbstractAlgebra,jl by the way.

[1] https://nemocas.github.io/AbstractAlgebra.jl/rings.html

**Comment by kalmarek** [comment]
Can I/should I use doctests? `@ref`s?

**Comment by wbhart** [comment]
You can if you want. They are probably only run when I build the
documentation (it's not automated any more). But I guess we'll end up with
doctests eventually.

**Comment by kalmarek** [comment]
Well, I have to admit, `Documenter` is increadibly slow, and fragile as hell. 
I've already spent more time tracking spaces, which throw it off-balance, than writing the actual text... ;/

**Comment by kalmarek** [comment]
please have a look at https://github.com/kalmarek/AbstractAlgebra.jl/tree/enh/perm_docs

I have troubles with `Documenter` not finding `::PermGroup`. Any ideas?

**Comment by wbhart** [comment]
Looks good so far. I would be inclined to put "Characters" on a different
page rather than at the end of the permgroups. But I leave it up to you
what you prefer.

Documenter does sometimes require some hints to find things, e.g.
Generic.PermGroup might work. You might be able to figure out what is
missing by looking for examples elsewhere in the docs where I've hit this
problem. There are still some cases I haven't figured out, and it picks up
the docs for functions in Base instead of the functions in Nemo or
AbstractAlgebra.

However, I'm sure you noticed in other docs that some of the stuff is
filled in by hand. E.g. the parent call overload isn't picked up by
Documenter, and there's a few other things that just don't make sense to
document the way Documenter does it, so I do it by hand. This is fine.

Some comments:

* vector is probably a Julia concept, but is "list" a term that is defined
in the Julia docs (relates to description of perms being a vector or list)
*  singleton parent object ->  singleton parent objects ??
*  It's slightly confusing to describe perms as being provided by "native".
I'm not sure we need this in AbstractAlgebra.jl, since all types are
provided by AbstractAlgebra itself. There are no external libraries used,
so they don't need describing. Feel free to add a note that the code is in
the Generic submodule though.
*  if You are sure that Your ->  if you are sure that your (this typo
occurs often throughout)
*  paramtrizing -> parameterizing
* In the version on GitHub there is a block with

setpermstyle

in it. I assume this is ok in the Documenter version.
*  directly call to permconstructor ->  directly call to the perm (inner)
constructor (also occurs once later in the page)
*   The Generic.perm constructor doesn't look like a function, and doesn't
have a description of its args, same for PermGroup. I assume this is just
because it isn't rendered by Documenter here.
*  permuation -> permutation
*   The Warning is a bit scary. Is there some other way we can handle this?
I admit I don't see how we can handle it, other than invalidating the cycle
structure.
*  overflowd ->  overflowed
*   explicitely  ->  explicitly
*   Note be careful ->  Note: be careful (by the way, I think this note is
unclear; I actually don't know what you mean)
*   structue ->  structure
*  julia ->  Julia (at least, I think we have capitalised it elsewhere in
the docs)
*  method performs ->  methods perform
*  vector od ->  vector of
*   I did notice that all your docstrings in the coercion section don't
seem to have capital letters at the start. I think I used capital letters
as the start of every docstring, so maybe it will be better for uniformity
to do this. Simply make the first plural word a singular and capitalize it,
in most cases.

(It is possible that some of my comments about capital letters may not make
sense. I have some kind of Chrome or extension bug that randomly swaps
numbers and letters and swaps capital and lower case letters, which is
really convenient when paying bills online, since it makes sure a random
person gets the money.)

Also, sorry about the varying text sizes. This is another "extra
programmer's feature" in my email client.

Of course the comparison and misc sections seem to be incomplete, but I
presume you haven't done these yet.

**Comment by kalmarek** [comment]
thanks for the extensive list of corrections! I will look into them today or tomorrow

**Comment by wbhart** [comment]
Looks good. Do you want to make a pull request and I'll merge it.

**Comment by kalmarek** [comment]
I'm in the middle of writing docs for YoungTabs, I will make a pull request once I'm finished, ok?
(not sure if this will happen over the weekend though)

**Comment by wbhart** [comment]
Of course, no problem.

**Comment by kalmarek** [comment]
I had to reconsider, more changes are piling up for Young tabelaux

**Comment by kalmarek** [comment]
closed by https://github.com/Nemocas/AbstractAlgebra.jl/pull/128
