### ISSUE TITLE
Problem with BigInt conversion in "Constructing mathematical objects in AbstractAlgebra.jl"

### ISSUE THREAD

**Issue by KZiemian** [Nemocas/AbstractAlgebra.jl#577]
In the documentation section [Constructing mathematical objects in AbstractAlgebra.jl](https://nemocas.github.io/AbstractAlgebra.jl/latest/constructors/) there is a command
```julia
n = BigInt("1234567898765434567898765434567876543456787654567890")
```
When I run it in my Julia 1.3.1 I get error "MethodError: no method matching BigInt(::String)". For the same reason
```julia
n = ZZ("12345678765456787654567890987654567898765678909876567890")
```
few lines below also doesn't work.

Is this code outdated or am I doing something wrong?

**Comment by wbhart** [comment]
It's out of date. You can omit the inverted commas.

**Comment by KZiemian** [comment]
@wbhart Thank you for information. I now have problems with a Git and GitHub, so I can't make Pull Request with corrected version.
