### ISSUE TITLE
gens vs nvars

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#596]
Seems inconsistent. We seem to have decided that the function vars returns the variables actually occurring in a given poly, whilst gens returns the variables for a given ring. But then I'd expect the function to be called ngens, not nvars.

**Comment by fieker** [comment]
context is muissing to comment on this. But if we have vars and gens, we can have nvars and ngens as length(...)
I'd actually never applied this to a poly, only to rings so far. Although applying this to polys makes sense every now and then (mostly, for me so far: isunivariate and in what variable)

**Comment by fieker** [comment]
wasn't actively trying to close, but clicked wrongly

**Comment by wbhart** [comment]
What I mean is this:

```
julia> using AbstractAlgebra

julia> R, (x, y) = PolynomialRing(ZZ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Integers, AbstractAlgebra.Generic.MPoly{BigInt}[x, y])

julia> vars(x)
1-element Array{AbstractAlgebra.Generic.MPoly{BigInt},1}:
 x

julia> gens(R)
2-element Array{AbstractAlgebra.Generic.MPoly{BigInt},1}:
 x
 y

julia> nvars(R)
2

julia> ngens(x)
ERROR: MethodError: no method matching ngens(::AbstractAlgebra.Generic.MPoly{BigInt})
Closest candidates are:
  ngens(::AbstractAlgebra.Generic.FreeModule{T}) where T<:Union{NCRingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/FreeModule.jl:48
  ngens(::AbstractAlgebra.Generic.Submodule{T}) where T<:Union{RingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/Submodule.jl:25
  ngens(::AbstractAlgebra.Generic.QuotientModule{T}) where T<:Union{RingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/QuotientModule.jl:25
  ...
Stacktrace:
 [1] top-level scope at REPL[15]:1
```

The function for getting the number of variables in a ring is nvars. But to return a list of them we use gens not vars.

The function for getting the variables actually occurring in a polynomial is vars. There is no way to return the number of them without actually creating the objects.

**Comment by fieker** [comment]
On Wed, May 19, 2021 at 02:55:07PM -0700, wbhart wrote:
> What I mean is this:
> 
> ```
> julia> using AbstractAlgebra
> 
> julia> R, (x, y) = PolynomialRing(ZZ, ["x", "y"])
> (Multivariate Polynomial Ring in x, y over Integers, AbstractAlgebra.Generic.MPoly{BigInt}[x, y])
> 
> julia> vars(x)
> 1-element Array{AbstractAlgebra.Generic.MPoly{BigInt},1}:
>  x
> 
> julia> gens(R)
> 2-element Array{AbstractAlgebra.Generic.MPoly{BigInt},1}:
>  x
>  y
> 
> julia> nvars(R)
> 2
> 
> julia> ngens(x)
> ERROR: MethodError: no method matching ngens(::AbstractAlgebra.Generic.MPoly{BigInt})
> Closest candidates are:
>   ngens(::AbstractAlgebra.Generic.FreeModule{T}) where T<:Union{NCRingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/FreeModule.jl:48
>   ngens(::AbstractAlgebra.Generic.Submodule{T}) where T<:Union{RingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/Submodule.jl:25
>   ngens(::AbstractAlgebra.Generic.QuotientModule{T}) where T<:Union{RingElem, AbstractFloat, Integer, Rational} at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/QuotientModule.jl:25
>   ...
> Stacktrace:
>  [1] top-level scope at REPL[15]:1
> ```
> 
> The function for getting the number of variables in a ring is nvars. But to return a list of them we use gens not vars.
> 
> The function for getting the variables actually occurring in a polynomial is vars. There is no way to return the number of them without actually creating the objects.

Generically, any fin. gen. structure should always support
gens, ngens, gen( , i), R[i] (possibly)

vars, nvars for polynomials and poly rings is, to me, an addition, but
the desrired generic interface for the ring is gens, ngens

**Comment by fingolfin** [comment]
We have `ngens(R)`. Yes also `nvars(R)` but that's a bonus extra.

I see no issue here?
