### ISSUE TITLE
sqrt fallback based on factoring

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#607]
@simonbrandhorst wanted to do something in Oscar/Nemo and ran into the following problem:
```julia
julia> P, t = PowerSeriesRing(GF(29), 12, "t")
(Univariate power series ring in t over Galois field with characteristic 29, t+O(t^13))

julia> sqrt(1 + t)
ERROR: MethodError: no method matching sqrt(::Nemo.gfp_elem)
Closest candidates are:
  sqrt(::Float16) at math.jl:1018
  sqrt(::Complex{Float16}) at math.jl:1019
  sqrt(::Missing) at math.jl:1070
  ...
Stacktrace:
 [1] sqrt(::Nemo.gfp_elem) at /home/thofmann/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:61
 [2] sqrt(::AbstractAlgebra.Generic.RelSeries{Nemo.gfp_elem}) at /home/thofmann/.julia/dev/AbstractAlgebra/src/generic/RelSeries.jl:987
 [3] top-level scope at none:0
 [4] eval(::Module, ::Any) at ./boot.jl:328
 [5] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
 [6] run_backend(::REPL.REPLBackend) at
```
This is with #606. Otherwise it complains that the base ring is not a domain.

The `sqrt` function tries to call `sqrt` on the constant coefficien, but we don't have `sqrt` for all things. I suggest that we implement a `sqrt` fallback based on factorization of univariate polynomials. This will not be super efficient, but you know, it is supposed to be a fallback.

**Comment by wbhart** [comment]
Can you explain what you mean. I'm not sure I understand how factorisation of univariate polys helps taking sqrt of power series.

**Comment by fieker** [comment]
That was Bill's decision, I'd say if the constant coeff is 1, the power
series has a sqrt..
(You can trigger the "same" for exp and log:
exp(a+t) requires exp(a), so in general exp needs valuation > 0
log(a+t) requires log(a), so again, only log(1+t) makes sense.

I propose two (or more) changes:
 - for sqrt, exp, log (and pos. sin, cos, ...) in power series, try to
   see if we are in the obvious case, then proceed
 - implement sqrt, ispower, ... for all finite fields
 - have the generic fall back via factorisation

**Comment by thofma** [comment]
I am just suggesting having
```julia
function sqrt(a::FieldElem)
  R, x = PolynomialRing(parent(x), "$")
  f = factor(x^2 - a)
  if length(f) < 2
    error
  else
    return coeff(blabla)
  end
end
```

**Comment by wbhart** [comment]
Oh I see. I had temporarily forgotten we even had factorisation of polynomials over general finite fields.

**Comment by thofma** [comment]
So I suggest adding the fallback as I wrote above and adding special implementations for the finite fields in Nemo (we should probably wait until we bumped the flint version and use Dan's new root finding code).

If this sounds OK for you, I will start with adding the fallback.

**Comment by wbhart** [comment]
Why not just do a quick and dirty 10 line implementation of Tonelli-Shanks. It'd be just about the same amount of code, but actually fast.

**Comment by fieker** [comment]
On Fri, Jun 26, 2020 at 04:32:44AM -0700, wbhart wrote:
> Why not just do a quick and dirty 10 line implementation of Tonelli-Shanks. It'd be just about the same amount of code, but actually fast.
> 
The fallback catches all rings/ fields where we can factor, not "just"
finite fields. Of course, for finite fields we can do better - and
should actually implement n-th roots.

**Comment by thofma** [comment]
Because I want it to work for all finite fields and also number fields.
