### ISSUE TITLE
Check matrices for symmetry

### ISSUE THREAD

**Issue by johannes-hoffmann** [Nemocas/AbstractAlgebra.jl#612]
Is there a function in AbstractAlgebra to check a matrix for symmetry? I couldn't find one. If not, is there a reason why?

**Comment by thofma** [comment]
No, there is no particular reason. I guess everybody who needs it just writes his own function, e.g.,
```julia
function LinearAlgebra.issymmetric(M::MatElem)
  for i in 1:nrows(M)
    for j in i:ncols(M)
      if M[i, j] != M[j, i]
        return false
      end
    end
  end
  return true
end
```
https://github.com/thofma/Hecke.jl/blob/5498de48e02d27ebb795458c1cf4c95b20015dd4/src/QuadForm/Morphism.jl#L214-L223

I agree that we should have it here.

**Comment by wbhart** [comment]
Not there yet. No reason why not. Just no one thought of implementing it yet. So feel free.
