### ISSUE TITLE
Recursive behavior of ismonomial

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#618]
At the moment, our `ismonomial` function is recursive for univariate polynomials:
```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> S, y = PolynomialRing(R, "y")
(Univariate Polynomial Ring in y over Univariate Polynomial Ring in x over Integers, y)

julia> ismonomial(x*y)
true
```
I see that this definition can be useful when working with nested polynomial rings as multivariate rings. On the other hand, the definition of a monomial of a univariate polynomial ring is pretty clear. An element `f` of the univariate polynomial ring `R[x]` is a monomial if and only if `f == x^i` for some `i` (the word *monomial* might be different, but I have not seen a definition which requires a coefficient of `f` being a monomial (which is not well-defined anyways)). Similar for `isterm`. There are a few other problems/questions:

- The docstring (of `isterm`) mentions "Return true if the given polynomial has one term. This function is recursive, with all 
  scalar types returning true." It is not clear what a scalar type is. Every ring and its elements can be scalars of a univariate 
  polynomial ring. So everything is a scalar. So everything is a scalar type? So for every ring element it should return true?
- The multivariate polynomials don't use the recursive "definition".
- If `ismonomial` is recursive, then so should be `degree` or `isconstant`. It is quite inconsistent to treat polynomials as 
  multivariates for some functions and not for the others.
- At the moment we don't have a function to reliably test if something is `x^i`. This makes writing generic code hard.
- (Sage and Magma don't use the recursive version)

I would propose to introduce `ismonomial_recursive` which has the recursive behavior and reserve `ismonomial` for the non-recursive one.

@wbhart @fieker

**Comment by wbhart** [comment]
Sounds like a reasonable proposal to me. I think the recursive version is needed for gcd, from memory. But it doesn't matter what it is called.

Scalar is poorly defined. I don't even remember what was meant by it. I suspect everything that isn't a polynomial is scalar.
