### ISSUE TITLE
ERROR: MethodError: no method matching zero( ...) for sparse matrix operations over a finite field

### ISSUE THREAD

**Issue by Eetion** [Nemocas/AbstractAlgebra.jl#625]
The same error message seems to appear in several places when working with sparse arrays over a finite field: conversion to a dense array, matrix addition, scaling, and transposing. 

```
(@v1.4) pkg> status "AbstractAlgebra"
Status `~/.julia/environments/v1.4/Project.toml`
  [c3fe647b] AbstractAlgebra v0.10.0
```

```
using SparseArrays
using AbstractAlgebra

julia> F = GF(13)
julia> D = F.([0 0; 0 0])
2×2 Array{AbstractAlgebra.GFElem{Int64},2}:
 0  0
 0  0

julia> d = sparse(D)
2×2 SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64} with 0 stored entries

julia> Array(d)
ERROR: MethodError: no method matching zero(::Type{AbstractAlgebra.GFElem{Int64}})
Closest candidates are:
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeight}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/versionweights.jl:15
  ...
Stacktrace:
 [1] zeros(::Type{AbstractAlgebra.GFElem{Int64}}, ::Tuple{Int64,Int64}) at ./array.jl:505
 [2] zeros(::Type{AbstractAlgebra.GFElem{Int64}}, ::Int64, ::Int64) at ./array.jl:500
 [3] Array{T,2} where T(::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:549
 [4] Array(::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:559
 [5] top-level scope at REPL[147]:1

julia> D+D
2×2 Array{AbstractAlgebra.GFElem{Int64},2}:
 0  0
 0  0

julia> d+d
ERROR: MethodError: no method matching zero(::Type{AbstractAlgebra.GFElem{Int64}})
Closest candidates are:
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeight}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/versionweights.jl:15
  ...
Stacktrace:
 [1] _zeros_eltypes at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:204 [inlined]
 [2] _noshapecheck_map(::typeof(+), ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:159
 [3] map(::typeof(+), ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:1153
 [4] +(::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:1648
 [5] top-level scope at REPL[149]:1

julia> transpose(d)
2×2 LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}:
Error showing value of type LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}:
ERROR: MethodError: no method matching zero(::Type{AbstractAlgebra.GFElem{Int64}})
Closest candidates are:
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeight}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/versionweights.jl:15
  ...
Stacktrace:
 [1] getindex(::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}, ::Int64, ::Int64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/sparsematrix.jl:2005
 [2] getindex at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/adjtrans.jl:178 [inlined]
 [3] isassigned(::LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}, ::Int64, ::Int64) at ./abstractarray.jl:404
 [4] alignment(::IOContext{REPL.Terminals.TTYTerminal}, ::LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::Int64, ::Int64, ::Int64) at ./arrayshow.jl:67
 [5] print_matrix(::IOContext{REPL.Terminals.TTYTerminal}, ::LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:189
 [6] print_matrix at ./arrayshow.jl:162 [inlined]
 [7] print_array at ./arrayshow.jl:310 [inlined]
 [8] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::LinearAlgebra.Transpose{AbstractAlgebra.GFElem{Int64},SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}}) at ./arrayshow.jl:346
 [9] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:137
 [10] display(::REPL.REPLDisplay, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:141
 [11] display(::Any) at ./multimedia.jl:323
 [12] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [13] invokelatest at ./essentials.jl:711 [inlined]
 [14] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:161
 [15] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
 [16] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
 [17] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [18] invokelatest at ./essentials.jl:711 [inlined]
 [19] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354
 [20] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
 [21] run_repl(::REPL.AbstractREPL, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
 [22] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [23] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [24] invokelatest at ./essentials.jl:711 [inlined]
 [25] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [26] exec_options(::Base.JLOptions) at ./client.jl:305
 [27] _start() at ./client.jl:484

d .* 2
ERROR: MethodError: no method matching zero(::Type{AbstractAlgebra.GFElem{Int64}})
Closest candidates are:
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeight}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Resolve/versionweights.jl:15
  ...
Stacktrace:
 [1] _zeros_eltypes at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:203 [inlined]
 [2] _noshapecheck_map(::SparseArrays.HigherOrderFns.var"#3#4"{typeof(*),SparseArrays.HigherOrderFns.var"#15#18"{SparseArrays.HigherOrderFns.var"#23#26"{Int64}}}, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:159
 [3] _shapecheckbc(::Function, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:1025
 [4] _copy(::Function, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:1015
 [5] _copy(::Function, ::SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64}, ::Int64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:1020
 [6] copy at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/higherorderfns.jl:1011 [inlined]
 [7] materialize(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseMatStyle,Nothing,typeof(*),Tuple{SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64},Int64}}) at ./broadcast.jl:820
 [8] top-level scope at REPL[162]:1

```

This is confusing, since the `zero` function seems to work fine of `F`

```
zero(F)
0
```

and matrix multiplication works fine

```
d*d
2×2 SparseMatrixCSC{AbstractAlgebra.GFElem{Int64},Int64} with 0 stored entries
```

A comment on issue [#37022](https://github.com/JuliaLang/julia/issues/37022) suggests that this may have to do with `AbstracAlgebra` itself:

> The field element type does not have a static parameter indicating the parent field. I think this is a design issue with AbstractAlgebra.

**Comment by wbhart** [comment]
There's nothing we can do about that. All of the Julia libraries assume
that one can construct a zero from its type alone, which is a false
assumption for many objects in mathematics.

In our case F is not a type, but an object, as it must contain more
information than is allowed in a type. Therefore zero(T) where T is a type
is pretty much useless.

Perhaps @thofma or @fieker can point you to some of our sparse array code
in Hecke.jl which may be of use with our rings/fields.

**Comment by wbhart** [comment]
Obviously you could also do this step if there were a function for
converting from a Julia sparse array to one of our dense matrices (we have
our own matrix type, for exactly the same reasons as I just mentioned).

But it really depends what you want to do with it. Most of the Julia
algorithms are not going to work with algebraic objects, and it may be that
we don't have the function you are after yet. Quite a few of the Julia
functions are extremely hard to implement for all our rings/fields, and in
some cases algorithms may not even be known or possible.

**Comment by kimikage** [comment]
I think we can do some specializations about the zero element. In other words, I would like to be able to generate a zero element with an anonymous parent field.

**Comment by thofma** [comment]
To copy what I wrote in https://github.com/JuliaLang/julia/issues/37022:

Our AbstractAlgebra types do not satisfy the `Number` interface of julia Base, since it is not possible to compute the zero element just from the type of the element. This is also not practical, as you do not want to recompile a new method for every finite field `ZZ/p` with different `p`.

It is a design decision of julia Base that the type should contain all the information. This is not necessarily a bad one. It seems to work quite well if all you work with is `Float64` or your other four different floating point types. But it is a design decision that is incompatible with areas where you need lots of different "number types", like lots of different finite fields.

**Comment by wbhart** [comment]
You have the same problem with one. Then you have problems if people
want to add one to itself.

There's no way to fix this. It's not a design decision on our part
that needs fixing.

We've talked with the Julia people about using zero(a) instead of
zero(T) where a is an object of the given type. This is something that
would work for us. But although people have at times agreed to do this
in all the Julia libraries, it's a neverending task to remind them to
do it. So we gave up.

Instead, AbstractAlgebra and related libraries define their own
matrices and polynomials.

**Comment by wbhart** [comment]
By the way, here is a simple example. Consider the ring R = Z/1Z with
elements of type T = zmod{Int}. How would iszero(one(T)) work?

There is absolutely no way you can implement this function correctly
without knowing the modulus. This is one of very many examples of
things that you can never solve.

The parent/object model is 30 years old and well studied. If there was
another way to do computer algebra without it, people would be using
it.

**Comment by kimikage** [comment]
> You have the same problem with one. 

That's right, but is "this" issue not only about `zero`?

**Comment by thofma** [comment]
We thought about this before. If you allow zeros with anonymous parents, and you have two instances, say `a` and `b`, you don't know if `a + b` is zero or an error.

**Comment by wbhart** [comment]
.. or even what kind of object it is. Consider a polynomial ring over a fraction field of a polynomial ring.

Suppose you have poly_zero + frac_zero. Which kind of object is the result? Is it a polynomial in the top poly ring or a fraction in the middle ring?

You are by the way at least the tenth person who has suggested this is a "design flaw" in AbstractAlgebra.

**Comment by fieker** [comment]
On Thu, Aug 13, 2020 at 12:08:07AM -0700, Gregory Henselman-Petrusek wrote:
> The same error message seems to appear in several places when working with sparse arrays over a finite field: conversion to a dense array, matrix addition, scaling, and transposing. 
> 
Sorry Gregory, but the functions are not missing they are impossible.
Problem is that your missing zero(GFElem{Int64}) and you want 0 in
GF(13). The information neccessary (13) is not part of the type.

Some julia internals will work as they use zero(some element on the
matrix) rather than zero(type) which will work. However due to empty
matrices this cannot be made to work in general.

We can write a conversion to sparse arrays of course, but I don't know
how many julias functions for them will work due to the same problem...

If you stick to the (dense) matrices in AbstractAlgebra, "all" will
work.

Greetings
 Claus

**Comment by fieker** [comment]
On Thu, Aug 13, 2020 at 12:42:09AM -0700, kimikage wrote:
> I think we can do some specializations about the zero element. In other words, I would like to be able to generate a zero element with an anonymous parent field.
> 
That will have to be treated specially in all arithmetic operations...
and has spill on effects: trace, norm, ... will all be anonymous zeros
as well - but in different rings probably.
Further: you'd need (sooner or later) the same for one() and thus for
all integers and rationals (operations with one without a parent). Here
the loss of the characteristic will be bad...

What are you trying to do actually? We have sparse matrices (a different
data structure) implemented in Hecke. Those can be converted to Julia:

julia> using Hecke
julia> k = GF(13)
Galois field with characteristic 13

julia> matrix(k, 2, 2, [1,2,3,4])
[1  2]
[3  4]

julia> sparse_matrix(ans)
Sparse 2 x 2 matrix with 4 non-zero entries


julia> Array(ans)
[1  2]
[3  4]

julia> sparse_matrix(ans)
Sparse 2 x 2 matrix with 4 non-zero entries


julia> sparse(ans)
2×2 SparseArrays.SparseMatrixCSC{Nemo.gfp_elem,Int64} with 4 stored entries:
  [1, 1]  =  1
  [2, 1]  =  3
  [1, 2]  =  2
  [2, 2]  =  4

**Comment by Eetion** [comment]
Thanks, all, very much for this discussion.  

> What are you trying to do actually?

@fieker Given the expertise in this community, let me say a little more than is strictly necessary, with the hope that someone might be able to suggest some high level design decisions.

Question

Given the following goals, would it make sense to write a new CSC matrix class in Julia that supports the primitive operations of sparse matrix addition, multiplication, scaling, slice, transpose, and conversation to dense format with coefficients from `AbstractAlgebra`, `Hecke`, and `Gapjm`, given that the intended operations on these matrices will be limited to simple row and column reductions.  (Sparse `Hecke` format sounds attractive and is something we will probably try export to, but for reasons explained below we have interest in traditional CSC format, too).

Goals

I am part of a mathematicians developing software for efficient (sparse) methods of homological algebra, specifically focused on data applications (cf persistent homology and topological data analysis, TDA).  The computations we run are very simple: triangular solve, row, and column reduction cover most of our needs, as a community.  Under other circumstances we would use the (fantastic) tools for sparse linear algebra that already exist, but the size/shape of our matrices tend to make them incompatible with existing solvers.  In particular, our boundary arrays have #'s of rows on the order of tens or hundreds of millions, and #'s of columns on the order of hundreds of billions or trillions.  

Those who work in algorithms deal with the size problem mainly via compression schemes that break an array into parts and process one part at a time (never actually constructing the full matrix in its entirety).  Quite often in practice, one only ever ends up using a part of a matrix, but it's impossible to know which part, ahead of time.  The most successful paradigm has been to create a "matrix object" which uses relatively little memory but which can be queried to produce individual rows/columns of the larger matrix.  Statistically speaking, this tends to work quite well.

A major challenge in TDA has been that developers rarely expose "matrix objects" to the user.  More often, a developer creates a single-use matrix object for a single computation (eg, a betti number); their program accepts user input and returns the number, but not the matrix object.

As one might imagine, this poses a significant barrier to entry for people who want to do research on homological data, but don't have time to code matrix objects from scratch.  My group's goal is to lower that barrier.  One part of our approach is to create a library for sparse homological algebra that does expose the matrix object, but another very important part is functionality to export objects/computations to more sophisticated platforms (like `AbstractAlgebra`, `Hecke`, `Gapjm`), at least when arrays are small enough to fit in memory.  

It had been our idea to use a very basic data structure, like the Julia sparse array, as the default export format for our smaller arrays.  However, based off the discussion above, it sounds as though users wouldn't have access to many of the basic operations they'd want and expect.  Exporting to `Hecke` sounds like a good option no matter what, but the internal workings of our own library assume a CSC-style matrix format, and it would be ideal to have a conventional CSC matrix class in Julia to mirror this format.  Since our operations are so primitive (no determinants, nothing spectral), we could probably write such a class ourselves.  We'd prefer to avoid doing this, though, if at all possible; it seems gratuitous to write a new CSC class in a language that has so much infrastructure, already.

One final note, in closing.  Virtually all computations in TDA run on prime-field (where p is small) or rational coefficients.  The closest one gets to non-field computations in the current literature are heuristics that lift cocycles in large-prime-field cohomology to cocycles in integer-cohomology.  However, we hope and expect that the new library will let people start working with more interesting rings/modules.  So a heuristic solution that allowed people to work comfortably with the first 1,000 primes (or really just the first 10) would cover 98% of all use cases, but a more general solution could generate a very interesting additional 2%.

**Comment by Eetion** [comment]
@wbhart, there are a number of devoted Julia users in the TDA community.  Most are not experienced programmers, but with very clear instructions about what to say, and to whom, I think that many would be glad to help remind the Julia developers of this issue.

**Comment by wbhart** [comment]
Dear Gregory,

The basic issue is that we can handle this:

julia> using AbstractAlgebra

julia> zero(ZZ(1))
0

julia> R = ResidueRing(ZZ, 23)
Residue ring of Integers modulo 23

julia> zero(R(1))
0

julia> one(R(1))
1

Therefore if Julia libraries use something like zero(A[1,1]) instead of
zero(T), everything works fine. For dense matrices this is easy. But for
sparse matrices I guess the problem they have is finding a nonzero entry of
the sparse matrix to do this with. So I can understand why this is actually
a challenge and possibly a performance issue.

There's nothing particularly special about the arithmetic mo p in
AbstractAlgebra though. It's overkill to use AbstractAlgebra for that.

If you only need arithmetic for small primes p then you can put p in the
type, though every function will be compiled by Julia for every p, which
can take absolutely ages if you want to use say the first 1000 primes.

If you only want to work with one p at a time, you can use a global
modulus, avoiding the problem. But in that situation you could avoid the
problem yourselves altogether by just defining zero(T) and one(T) to return
something based on the current modulus.

Bill.

**Comment by Eetion** [comment]
Dear Bill (and Claus and ,@thofma)

Thanks for this explanation; while still quite shaky on how types work in Julia, I think I can can wrap my head around the idea that functions which take parametric types have to compile separately for each choice of parameter, and that this becomes a problem when you need to use many different parameters.  

Most users *will* pick a single modulus and stick to it, so defining zero(T) and one(T) for a single prime is tempting.  Just to be clear, Hecke does not have functionality for sparse matrix slice / transpose / multiplication, correct?

Thank you again, all, for the very patient explanations.

Greg

**Comment by fieker** [comment]
On Thu, Aug 13, 2020 at 07:43:25PM -0700, wbhart wrote:
> Dear Gregory,
> 
> The basic issue is that we can handle this:
> 
> julia> using AbstractAlgebra
> 
> julia> zero(ZZ(1))
> 0
> 
> julia> R = ResidueRing(ZZ, 23)
> Residue ring of Integers modulo 23
> 
> julia> zero(R(1))
> 0
> 
> julia> one(R(1))
> 1
> 
> Therefore if Julia libraries use something like zero(A[1,1]) instead of
> zero(T), everything works fine. For dense matrices this is easy. But for
> sparse matrices I guess the problem they have is finding a nonzero entry of
> the sparse matrix to do this with. So I can understand why this is actually
> a challenge and possibly a performance issue.
Usually, in the sparse format (any), finding a non-zero entry - if it
exists, is trivial. The problem one way or other is with empty matrices.
(Sparse formats store only non-zero entries typically)
> 
> There's nothing particularly special about the arithmetic mo p in
> AbstractAlgebra though. It's overkill to use AbstractAlgebra for that.
> 
> If you only need arithmetic for small primes p then you can put p in the
> type, though every function will be compiled by Julia for every p, which
> can take absolutely ages if you want to use say the first 1000 primes.
> 
> If you only want to work with one p at a time, you can use a global
> modulus, avoiding the problem. But in that situation you could avoid the
> problem yourselves altogether by just defining zero(T) and one(T) to return
> something based on the current modulus.
> 
> Bill.
But if you're only interested in "small" primes and huge matrices, then
clearly some packing could also help. In particular if you only want
small primes, then also delayed reduction would be useful.

Our sparse matrices are row matrices - as the default in algebra is more
rows (and some of the underlying stuff is rooted in C).
It currently supports "all" exact rings and
 - transpose
 - row operations
 - rref (echelon form)
 - det
 - some Wiedemann method to get (a factor of) the minpoly of A*A'
 - various mat * vec versions
what is lacking is 
 - a good structured Gaussian elemination with
    switch over to the dense case
 - mat * mat
 - Lanczos/ Wiedemann for (some) nullspace elements
 - special casing for small primes

Doing the same transposed would be trivial I guess.... however "our"
format was chosen to support row operations for the echelon algorithms.
I do not see this in the CSC format...
> 
> On Fri, 14 Aug 2020 at 00:49, Gregory Henselman-Petrusek <

**Comment by fieker** [comment]
On Fri, Aug 14, 2020 at 12:55:11AM -0700, Gregory Henselman-Petrusek wrote:
> Dear Bill (and Claus and @thofma)
> 
> Thanks for this explanation; while still quite shaky on how types work in Julia, I think I can can wrap my head around the idea that functions which take parametric types have to compile separately for each choice of parameter, and that this becomes a problem when you need to use many different parameters.  
> 
> Most users *will* pick a single modulus and stick to it, so defining zero(T) and one(T) for a single prime is tempting.  Just to be clear, Hecke does not have functionality for sparse matrix slice / transpose / multiplication, correct?
> 
"slice" is there as sub(Matrix, range, range) but that could be expanded
transpose is there
mat * vec, but not mat * mat (was no need - but could be added)

**Comment by Eetion** [comment]
Ah, that's great!  Is there documentation for these operations?  I looked [here](http://www.thofma.com/Hecke.jl/latest/sparse/intro/) earlier, but didn't see these things.  Thanks!

**Comment by fieker** [comment]
On Fri, Aug 14, 2020 at 01:44:12AM -0700, Gregory Henselman-Petrusek wrote:
> Ah, that's great!  Is there documentation for these operations?  I looked [here](http://www.thofma.com/Hecke.jl/latest/sparse/intro/) earlier, but didn't see these things.  Thanks!

There is some under Misc, but that needs improvement....

**Comment by wbhart** [comment]
Another thing worth knowing perhaps is that the C library Flint will
later this year have sparse matrices. The arithmetic should be faster
than AbstractAlgebra, but the matrix algorithms may be pretty much the
same as what Hecke is offering, so whether this would give you any
speedup is unsure.

Flint is wrapped in the Nemo.jl library and works otherwise the same
as AbstractAlgebra. Once the sparse matrices are wrapped, you could
use that, though you may still need some functions to convert your
types to and from it.

Bill.

**Comment by Eetion** [comment]
Thanks!  Flint sounds very interesting.  There are several questions I'd like to ask but hesitate to keep troubling everyone (perhaps there's documentation somewhere? I didn't see anything on the Flint website but I could easily be missing something).
1) Would the format of Flint sparse arrays (both in the base library and in the Julia wrapper) be CSC?  
2) A core piece of functionality in our intended workflow is to obtain a factorization A = VPU where V and U are upper triangular, and P has at most one nonzero entry per row and column.  This can be obtained by Gaussian elimination (adding rows low to high and columns left to right), but it's important that the elimination process never swap rows or columns.  This constraint was one thing that motivated us to write our own matrix libraries in the first place (mathematically, it comes from the need to compute row and column bases which respect filtrations on the underlying vector space/module).  Would the Flint library allow for this sort of functionality, possibly by allowing the user to specify an ordering on rows and columns?
Thank you again!

**Comment by wbhart** [comment]
On Fri, 14 Aug 2020 at 21:00, Gregory Henselman-Petrusek <
notifications@github.com> wrote:

> Thanks! Flint sounds very interesting. There are several questions I'd
> like to ask but hesitate to keep troubling everyone (perhaps there's
> documentation somewhere? I didn't see anything on the Flint website but I
> could easily be missing something).
>

The feature is still in development, so no documentation yet.

>
>    1. Would the format of Flint sparse arrays (both in the base library
>    and in the Julia wrapper) be CSC?
>
> No, matrices are not stored as a set of three arrays.

>
>    1. A core piece of functionality in our intended workflow is to obtain
>    a factorization A = VPU where V and U are upper triangular, and P has at
>    most one nonzero entry per row and column. This can be obtained by Gaussian
>    elimination (adding rows low to high and columns left to right), but it's
>    important that the elimination process never swap rows or columns. This
>    constraint was one thing that motivated us to write our own matrix
>    libraries in the first place (mathematically, it comes from the need to
>    compute row and column bases which respect filtrations on the underlying
>    vector space/module). Would the Flint library allow for this sort of
>    functionality, possibly by allowing the user to specify an ordering on rows
>    and columns?
>
> No, I don't believe this will be supported. I would guess you are better
sticking with Julia matrices after all.

Bill.

**Comment by Eetion** [comment]
Thanks very much, Bill, for your explanations and perspective.  Thanks, also, to Claus, for details about Hecke.jl.  Perhaps custom objects/methods will be needed for some workflows, but we're very glad to know about these packages and plans for expansion; will certainly encourage users to explore Nemo/Hecke/AbstractAlgebra for advanced usage.
