### ISSUE TITLE
parent(T) for Julia types

### ISSUE THREAD

**Issue by daviddelaat** [Nemocas/AbstractAlgebra.jl#65]
Should parent(BigInt) and parent(BigFloat) be implemented?

And in a similar fashion should, e.g., PolynomialRing(BigInt, "x") work as an alternative of PolynomialRing(ZZ, "x")?

**Comment by wbhart** [comment]
On 23 March 2018 at 19:23, David de Laat <notifications@github.com> wrote:

> Should parent(BigInt) and parent(BigFloat) be implemented?
>

No, parent applies to an object, not a type. Thus parent(BigInt(123))
works, parent(BigInt) does not.

> And in a similar fashion should, e.g., PolynomialRing(BigInt, "x") work as
> an alternative of PolynomialRing(ZZ, "x")
>

That's not a bad idea. Feel free to submit a pull request.

**Comment by daviddelaat** [comment]
But why should parent(T) not also work? For instance I currently have something like
```
function myfunction(a::MyObject{T}) where T
   R, x = PolynomialRing(parent(one(T)), "x")
   ...
```
where I would like to replace `parent(one(T))` by `parent(T)`

**Comment by wbhart** [comment]
That code is incorrect. You can't call one(T) since one only applies to a ring, not a type.

**Comment by wbhart** [comment]
You may find it useful to read this section of our documentation, to understand why types are not enough for computer algebra:

https://nemocas.github.io/AbstractAlgebra.jl/types.html

**Comment by wbhart** [comment]
Note that the diagram on that page is out of date. I've been meaning to update it for ages. But if you replace Nemo with AbstractAlgebra, you get the basic gist.

**Comment by daviddelaat** [comment]
This code is in a julia project where abstractalgebra is just one of the dependencies, and T here is either BigInt or BigFloat, for which I think the code is correct. But I understand one(T) cannot work for general abstractalgebra types, so I agree it's better to implement PolynomialRing(BigInt, "x") and PolynomialRing(BigFloat, "x")

**Comment by daviddelaat** [comment]
BTW, Just an off topic thought regarding the type hierarchy: I wonder whether it's feasible for julia to ever have a heuristic that chooses to not always compile methods for types whose parameters vary heavily. It would be lovely able to write something like
```
function foo(p::Matrix{PolyRing{ZZ,(:x,:y,:z)}})
```
where it compiles the method for `Matrix{PolyRing{ZZ,(:x,:y,:z)}}` if there are only a few polynomial rings in use and starts using a generic method otherwise..

**Comment by wbhart** [comment]
I don't think that is the solution that we eventually want. We genuinely want our generics compiled. That's the attraction of Julia.

What we really want is that Jit compilation only happens after a certain number of traversals over the code. It will happen one day, but that's the sort of thing that only very mature languages do.

**Comment by daviddelaat** [comment]
Yes, you're right, that's a better heuristic.

**Comment by fieker** [comment]
On Fri, Mar 23, 2018 at 06:23:46PM +0000, David de Laat wrote:
> Should parent(BigInt) and parent(BigFloat) be implemented?
I'd say no - BigInt is a type and therefore different semantics apply.
parent(BigInt) should, conceivably, be Type or similar.
> 
> And in a similar fashion should, e.g., PolynomialRing(BigInt, "x") work as an alternative of PolynomialRing(ZZ, "x")?
> 
No objections.
