### ISSUE TITLE
GF arithmetic broken for unsigned integers

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#653]
I can say https://github.com/Nemocas/AbstractAlgebra.jl/blob/b2e4a749d666c7f76ee20c83a47217d55c6ca21f/src/julia/GF.jl#L177 is definitely broken for GFElem{UInt} since there are no negatives there. I would recommend:
For `+ on GFElem{UInt} or on GFElem{T} in general`, do `a < p - b ? a + b : a - (p - b)`. This should work because there is nothing to go wrong here.

Since julia's native Ints have defined 2s complement behaviour, for `+ on GFElem{Int}`, we can do `Int(min(UInt(a + b), UInt(a + b - p)))`. This optimization is kinda pointless because the parent check is probably going to preclude vectorization anyways.

_Originally posted by @tthsqe12 in https://github.com/Nemocas/AbstractAlgebra.jl/pull/652#issuecomment-702027390_

**Comment by thofma** [comment]
My question is: Does this also work for UInt8 and Int8 etc?

**Comment by wbhart** [comment]
Assuming p, a and b all fit in a UInt8/Int8, then it should work. I didn't check the Int case, but the UInt case is clear. I think it's a standard way of detecting overflow.

Maybe you had some other potential issue in mind though?

**Comment by tthsqe12** [comment]
@thofma I updated my comment

**Comment by thofma** [comment]
OK great, Then we can dispatch on `Signed` and `Unsigned`. I will prepare a PR. Thanks @tthsqe12.

**Comment by tthsqe12** [comment]
Ok. When you fix the generic, please don't compute p-b twice. I am not able to make pr's at the moment.

**Comment by thofma** [comment]
OK, any clever suggestions for subtraction? It is equally broken,

**Comment by wbhart** [comment]
Sure, consider a, b \in [0, p - 1) both in UIntN. We can compute a - b mod p as:

a < b ? a + p - b : a - b
