### ISSUE TITLE
size(A,1) instead of rows(A)

### ISSUE THREAD

**Issue by daviddelaat** [Nemocas/AbstractAlgebra.jl#66]
I think in the matrices should work as Julia matrices as much as possible. In particular I think rows(A) should be replaced by size(A,1) and cols(A) by size(A,2). This makes it easier to write generic code that works for both type of matrices.

**Comment by wbhart** [comment]
On 23 March 2018 at 19:25, David de Laat <notifications@github.com> wrote:

> I think in the matrices should work as Julia matrices as much as possible.
> In particular I think rows(A) should be replaced by size(A,1) and cols(A)
> by size(A,2). This makes it easier to write generic code that works for
> both type of matrices.
>
I'm ok with this (though rows and cols shouldn't be removed -- they should
be replaced with nrows and ncols, though that is another matter).

Let's see what everyone else thinks.

**Comment by daviddelaat** [comment]
Personally I think `nrows(A)` should be implemented if and only if julia matrices have this function, otherwise it will just lead to code that is less generic than it could be, but I don't have a strong opinion on this.

**Comment by wbhart** [comment]
There's very little of our code that could/would work directly with Julia matrices. So I don't think there is any danger of us writing less generic code because of this.

But I accept the argument that we should also implement the Julia function so that people can write generic code for our matrices and Julia ones where possible (that's not going to be easy to do, since our matrices really are very different).

**Comment by thofma** [comment]
We have implemented `size` for all AbstractAlgebra/Nemo matrices, but I don't want to replace `rows(A)` with `size(A, 1)`.

**Comment by fieker** [comment]
On Fri, Mar 23, 2018 at 06:58:43PM +0000, wbhart wrote:
> On 23 March 2018 at 19:25, David de Laat <notifications@github.com> wrote:
> 
> > I think in the matrices should work as Julia matrices as much as possible.
> > In particular I think rows(A) should be replaced by size(A,1) and cols(A)
> > by size(A,2). This makes it easier to write generic code that works for
> > both type of matrices.
> >
> I'm ok with this (though rows and cols shouldn't be removed -- they should
> be replaced with nrows and ncols, though that is another matter).
> 
> Let's see what everyone else thinks.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nemocas/AbstractAlgebra.jl/issues/66#issuecomment-375767405

We (ie currently in Hecke only) have the size in all variations for
MatElem, so that's fine.
I agree rows -> nrows would be useful, but I too don't want to always
use size...

Claus

**Comment by daviddelaat** [comment]
Ok, I'll submit a pull request later.

**Comment by rfourquet** [comment]
So `size` is defined for `AbstractAlgebra` matrices, so some "Julia generic" algorithms may work on AA matrices. But we want to continue writing `nrows(A)` instead of `size(A, 1)`. What about defining `nrows(::Matrix)`, which may allow some AA algorithms to work on Julia matrices (or at least be a step in this direction). Then this issue could be closed.

**Comment by rfourquet** [comment]
Reading again this topic and coming up again with the idea suggested above: define `nrows(::Matrix)` ? Or let's close this issue.

**Comment by fieker** [comment]
On Fri, Mar 06, 2020 at 05:01:13AM -0800, Rafael Fourquet wrote:
> Reading again this topic and coming up again with the idea suggested above: define `nrows(::Matrix)` ? Or let's close this issue.
> 
OK: rows is depricaed and should do s.th. different, namely return the
rows, not the number of them

nrows can, as a fallback, be defined as size(?, ?) but needs to be there
as this is the primary interface for our matrices.

I am happy to close this

**Comment by thofma** [comment]
Yes, go ahead.

**Comment by rfourquet** [comment]
> Yes, go ahead.

Ok will do.

**Comment by rfourquet** [comment]
Thinking more about this, it doesn't seem very useful to define `nrows`/`ncols` on Julia matrices. As @wbhart put it,

> There's very little of our code that could/would work directly with Julia matrices. 

Most of our functions taking matrices are constrained to `MatrixElem`, and call other functions defined only on `MatrixElem`. So widening `ncols` to (Julia) `Matrix` in isolation will accomplish nothing. So the decision is: do we generally widen our type signatures to accept `Matrix` when it makes sense? `MatrixElem` is already a `Union`, so `Matrix` migth be added to this `Union` to limit code churn, although I'm not sure it would work without problems.

**Comment by thofma** [comment]
I think almost nothing will work, even if we widen the signatures. Also at the moment this has rather low priority.

**Comment by fingolfin** [comment]
We won't replace `nrows(a)` by `size(A,1)`, so the issue as given in its title, can be closed. There are various following discussions, as far as I can tell, nothing is left to be done there either. (And even if there is, it should arguably be in a new dedicated issue)
