### ISSUE TITLE
Remove `show_minus_one`, `needs_parentheses` and `displayed_with_minus_in_front`

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#711]
Once all our code has been converted to use `expressify` (see also https://github.com/Nemocas/AbstractAlgebra.jl/issues/710 and https://github.com/Nemocas/Nemo.jl/issues/938), we can remove `show_minus_one`, `needs_parentheses` and `displayed_with_minus_in_front` in all packages using it. Of course they should be removed in the right order: i.e.,
1.  resolve the two issues above
2. make new releases of AA and Nemo
3. remove them from Singular, Nemo and Hecke and make releases of those
4. remove them in AA and release it

(Of course in a monorepo, the above could be done with a single PR and no releases would be really necessary either).

Done in:
- [x] Singular.jl
- [x] Hecke.jl
- [x] Nemo.jl
- [x] AbstractAlgebra.jl

**Comment by tthsqe12** [comment]
I just opened https://github.com/Nemocas/Nemo.jl/pull/943 which removes these three functions completely from Nemo.jl.

**Comment by fingolfin** [comment]
@tthsqe12 thanks, great! Now we just need `expressify` for `SparsePoly` (see #710).

**Comment by tthsqe12** [comment]
Ah, I am sorry. I got the order wrong. We have to remove the uses in AA but still keep the symbols available for export. Then remove them from the packages that depend on AA, then remove them completely from AA?

**Comment by fingolfin** [comment]
Yeah. "So easy" 🤔

**Comment by tthsqe12** [comment]
Everything is under control :+1:

**Comment by wbhart** [comment]
@tthsqe12 I think the order should be:

* remove *uses* of these functions in AA
* remove the functions and uses from all other packages
* remove the functions in AA

Version numbers need to be changed because the interface is being changed (these functions are documented and used externally). But I don't see any other reason to change the version numbers.

**Comment by tthsqe12** [comment]
This should be just about done. @thofma hecke?

**Comment by thofma** [comment]
Yes, Hecke is also done. The functions are not called anymore.
