### ISSUE TITLE
divexact documentation unclear

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#719]
When I type `?divexact` then lots of docstrings are printed (see also issue #535); most are saying either "Return a/b." or

> Return x/y where the quotient is expected to be exact.

But it never explains what "exact" here means. The answer to this can be found [in the manual](https://nemocas.github.io/AbstractAlgebra.jl/latest/rings/#Exact-division) but not in the REPL. IMHO that's that's bad -- the REPL should provide this answer to.

**Comment by fingolfin** [comment]
I only discovered issue #535 after I submitted it; still, I think the two issues are about two slightly different things (although we might end up closing both in a single PR)

**Comment by wbhart** [comment]
This appears to have been fixed.
