### ISSUE TITLE
Reduce duplication between ring and ncring documentation

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#725]
I am unhappy that the ncring and ring documentation overlap so much, and duplicate tons of stuff.

That adds work to people working on documentation; it risks the two pages drifting apart; and also is worse for the users, who have to go over everything on the two pages with a comb to find the difference.

How about instead having a single page which lists all the common stuff; and then ring and ncring just say "everything from that page, plus the following few points" ? Or alternatively, keep the ncring page more or less as it is, but change the ring page to say "this is like ncring, except that the following are added: ... ; and the following are replaced by this and that ...

**Comment by wbhart** [comment]
@fingolfin It's a double edged sword. Deduplication makes less work for us, but my experience is it increases the amount of bug reports from people who didn't read the documentation pointed to by the link.

For what it is worth, the Magma documentation seems to duplicate everything, though they don't give a description of each function if it is something they consider standard. I personally find that very hard to use, as I am often unable to find a full description of what I'm looking for and even less often able to find an example.

My perspective on this is that regardless of what happens for AbstractAlgebra, Nemo should have a complete set of documentation for everything it does. Of course we can omit obvious things like what + and - do. But it's currently not working in practice that people have to look at AbstractAlgebra documentation to see what Nemo does.

I personally think our documentation is on the whole pretty inadequate, e.g. it doesn't give very careful statements about what inputs are valid, when exceptions are raised or even what the mathematical or other justification is for things being the way they are. Moreover, there are few tests that actually check that these statements are actually correct.

One thing I would personally like to do is to radically improve the Nemo docs over the next four years. I don't think it is necessary to duplicate the AbstractAlgebra "interface" pages in the Nemo docs. The interface is really only relevant to AbstractAlgebra, not all the packages that actually implement it. People writing Nemo should know to look at the AbstractAlgebra documentation to see the interface docs.

However, I think it is important for users of Nemo to know what generic functionality is provided (by AbstractAlgebra), thus I don't see a way around duplicating that if we want to have solid documentation.

Another solution would be to move all the more advanced generic implementations back into Nemo and leave just basic arithmetic for the generic types in AbstractAlgebra. For this we'd have to look at exactly how AbstractAlgebra is currently being used by the community. My sense is that most people using it are not doing Hermite normal forms and solving in generic recursive rings. They are using it as a Julia only implementation of Z/nZ and basic polynomial and power series arithmetic only. If they require more than that, they are probably switching to Nemo anyway.
