### ISSUE TITLE
Function coefficients is missing for univariate polynomials

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#728]
We have an iterator for multivariates but not univariates. Perhaps terms should also exist?

**Comment by fieker** [comment]
On Fri, Jan 15, 2021 at 01:18:38AM -0800, wbhart wrote:
> We have an iterator for multivariates but not univariates. Perhaps terms should also exist?

Definitely - we have it in Hecke...
[1] coefficients(f::PolyElem) in Hecke at
/home/fieker/.julia/dev/Hecke/src/Misc/Poly.jl:725

some of "our" names predate choices in Nemo, but we can change our
names...

**Comment by wbhart** [comment]
Note coeffs is an iterator for MPoly. One uses collect(coeffs(f)) to get the coefficients as an array.

**Comment by wbhart** [comment]
Don't forget coeffs_and_monomials and coeffs_and_monomials_and_expos.

I really think remembering the word zip is easier. But if you want to add these, go for it.

**Comment by wbhart** [comment]
By the way, it's exponent_vectors, not expos. So why did I name it coeffs instead of coeffs? That's because the function that was previously there was called that. I simple replaced that function with an iterator.

So maybe we should revisit all the names again.

**Comment by fieker** [comment]
On Fri, Jan 15, 2021 at 02:55:37AM -0800, wbhart wrote:
> By the way, it's exponent_vectors, not expos. So why did I name it coeffs instead of coefficients? That's because the function that was previously there was called that. I simple replaced that function with an iterator.
> 
> So maybe we should revisit all the names again.

Oh yes.... (this wasn't meant as a complaint or criticism: Tommy and I
(and Carlo) come back to this renaming orgies every now and then:
sanitising names is fun...)
But my gut feeling is: this will always be a second step: sanitising
after the work is done...

**Comment by wbhart** [comment]
We appear to have implemented this. Terms and exponents just doesn't seem that useful for univariates. If we encounter a situation where we need them, we can open a ticket for that.
