### ISSUE TITLE
multiply_row! can affect more than one row

### ISSUE THREAD

**Issue by johannes-hoffmann** [Nemocas/AbstractAlgebra.jl#755]
Consider the following, where I would (maybe naively) expect that the second row remains unchanged:
```
julia> using AbstractAlgebra
julia> A = identity_matrix(ZZ, 2);
julia> multiply_row!(A, 2, 1)
[2  0]
[0  2]
```
I guess the ones on the diagonal are both references to the same object (via `diagonal_matrix`), which leads to this behavior due to `mul!` in `multiply_row!`?

**Comment by thofma** [comment]
Yep, this is the reason and this is bad.

**Comment by wbhart** [comment]
multiply_row! should not exist. Matrices are not allowed to have their entries modified. They can be rearranged or replaced, but not modified.

**Comment by thofma** [comment]
When you say "should not exist", do you mean we should not have this functionality at all? I don't see the harm with having the correct version of this function, which just does replacing and not mutating.

**Comment by wbhart** [comment]
Yes, I suppose it can do that.

**Comment by wbhart** [comment]
Also affects multiply_col!, add_row! and add_col!
