### ISSUE TITLE
PowerSeries Problem - the next one

### ISSUE THREAD

**Issue by fieker** [Nemocas/AbstractAlgebra.jl#759]
There is a minor design flaw - or a misunderstanding:
```julia
using AbstractAlgebra
B, x = PolynomialRing(QQ, "x")
S, t = PowerSeriesRing(B, 4, "s")
a = S([3*x, 2*x, 4*x], 3, 4, 1)
b = S([-3*x], 1, 4, 1)
AbstractAlgebra.addeq!(a, b)
b = S([-3*x, 4*x, 5*x], 3, 4, 1)
AbstractAlgebra.addeq!(a, b)
```
gives a wrong result.  
Reason:
the first addeq results in a zero coefficient in fron, hence renormalize shifts the coefficients to the front, resulting in a.coeff[3] === a.coeff[2]. Since the coeff len is still 3, the call to fit! in the next addeq! does nothing. But now the internal addeq! creates havoc as the coeffs of a share common objects.

This actually happens when multiplying power series in similar settings, or, in my case, doing polynomial operations over power series over qadics.

A tentative fix would be to make fit! make usre the the "new" coeffs are properly seperated, ie. initialised with new zeros.
I think the the above example is legal by our conventions. On input a and b have completely separate coefficients.
I put this "fix" into a separate PR.

**Comment by wbhart** [comment]
The main thing is series addeq! is not well tested and also not used. It was done quickly so that the person who did it properly would have a starting point. It's not something I thought would ever actually be used.

**Comment by fieker** [comment]
addeq! is used in mul! - thats how I found it....

**Comment by wbhart** [comment]
Seems to have been fixed in master.
