### ISSUE TITLE
Multivariate Series Design Ideas

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#774]
I will be implementing a module for multivariate series. Here are some design issues to discuss:

1) How will precision be denoted? It seems Sage uses the notation R.O(3) to truncate every variable to precision 3, where R is the ring. This will work for us, though we will have to print it as O(3).

2) Of course the module should be based on MPoly polynomials, however we have many different orderings there. Do we want to just stick with lex, or do we want deglex and degrevlex too? If we want the latter, should the precision control the total degree or the degree in each variable as per lex? (I'm not even sure if there are good algorithms for this.)

3) Does Singular have multivariate series? I couldn't find them in the manual so far. Similarly for Magma, I found some Algebraic Series module, but this seems to be something slightly different.

4) We don't have the equivalent of mullow for MPoly. In fact I don't know an algorithm for this which is better than mul + truncate. Is the latter sufficient?

5) Do we want both relative and absolute precision models? (I see no problem for relative as well, it just needs a vector of valuations.)

6) We don't have any primitives for multivariate series division or inversion in MPoly (or Flint) so these will have to be implemented generically, which is somewhat difficult given that it is generally very difficult to have an efficient generic interface for multivariate polynomials (we only have concrete types so far, except for iterators, eval/subst and builders).

7) I don't know an algorithm for square root of multivariate series. Indeed Sage does not implement it either. They seem to hint it can be implemented in terms of multivariate square root for polynomials, which we have and apparently they don't.

8) Should valuation return the valuation in each variable or a global valuation?

9) What other functionality do we need? Log, exp, integral, derivative, evaluation/substitution (not sure we even have the latter for univariate series yet)?

**Comment by wbhart** [comment]
MPowerSeriesRing or MultivariatePowerSeriesRing?

**Comment by fieker** [comment]
On Mon, Mar 08, 2021 at 06:50:48AM -0800, wbhart wrote:
> I will be implementing a module for multivariate series. Here are some design issues to discuss:
Good!!
> 
> 1) How will precision be denoted? It seems Sage uses the notation R.O(3) to truncate every variable to precision 3, where R is the ring. This will work for us, though we will have to print it as O(3).
For me, the variables shuld have independend degrees.
> 
> 2) Of course the module should be based on MPoly polynomials, however we have many different orderings there. Do we want to just stick with lex, or do we want deglex and degrevlex too? If we want the latter, should the precision control the total degree or the degree in each variable as per lex? (I'm not even sure if there are good algorithms for this.)
Just lex. I am currently working on Wolfram to accept that arithmetical
operations and structural computations are different and can use
differend orderings. Mohammeds eyes lit up whe he heard this: it is
going to solve many problems...
> 
> 3) Does Singular have multivariate series? I couldn't find them in the manual so far. Similarly for Magma, I found some Algebraic Series module, but this seems to be something slightly different.
Singular has, as far as I know, no types for series. Janko thinks in
terms of "jet": jet(poly, n) truncates the polynomial at degree n
> 
> 4) We don't have the equivalent of mullow for MPoly. In fact I don't know an algorithm for this which is better than mul + truncate. Is the latter sufficient?
> 
We will see by application. However, the classical, stupid school
method can easily not compute terms that are too large.
> 5) Do we want both relative and absolute precision models? (I see no problem for relative as well, it just needs a vector of valuations.)
In my projected application (galois stuff) I need abs only, but the
geometers may have different ideas.
I'd start with abs
> 
> 6) We don't have any primitives for multivariate series division or inversion in MPoly (or Flint) so these will have to be implemented generically, which is somewhat difficult given that it is generally very difficult to have an efficient generic interface for multivariate polynomials (we only have concrete types so far).
exact division can be done with lifting. Not claiming super efficiency,
but it should work....
> 
> 7) I don't know an algorithm for square root of multivariate series. Indeed Sage does not implement it either. They seem to hint it can be implemented in terms of multivariate square root for polynomials, which we have and apparently they don't.
Root of x^2-f, thus in most cases lifting of roots...
> 
> 8) Should valuation return the valuation in each variable or a global valuation?
We need possibly different things, but including a vector... but also
degree in each variable...
> 
> 9) What other functionality do we need? Log, exp, integral, derivative, evaluation/substitution (not sure we have the latter for univariate series yet)?
"we" "have" some of this in the univariate case, but I'd say yes we
need. The other stuff: we need to talk to customers.
I recall that Janko (Magdalen) need evaluation of power series at a
polynomial (to model some parametrisation change)

Here's my application:
given f in in Q(x,y)[t] or so, (assume for the time being Z[x,y][t]) I
need a splitting field as an extension of Q(x,y). Canonically I could
use
 C[[x, y]] (bivariate power series over C)
 Qq[[x, y]] (bivariate over q-Adics)
Guess what I prefer? 

"my" "alogorithm" is 
 - to find irreducibles in x and y that are "nice"
 - move from Q(x,y)[t] -> Q(x,y)/<p(x), q(y)> [t] = K[t], K some number
   field
 - find a nice prime and move from K -> qAdic of "small" degree s.th. my
   poly has roots mod p
 - apply Hensel/Newton lifting to increase precision in all directions
   as required (q-adic, x and y)
 
Then, I need to evaluate slpolys at those values and decide if the
result is a small degree polynomial, not a series. I have on the
degrees...

**Comment by fieker** [comment]
On Mon, Mar 08, 2021 at 07:11:31AM -0800, wbhart wrote:
> MPowerSeriesRing or MultivariatePowerSeriesRing?

Whatever you want, its only a short search and replace away

(if you want I am still in town)
