### ISSUE TITLE
coeffs or coefficients?

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#779]
The iterator for the coefficients of an MPoly is currently coeffs. This was done to be in line with coeff(f, i).

The iterator for coefficients of a Poly is currently coefficients, in line with our abbreviations policy.

We should change one or the other, but need to choose which. Both would be breaking changes, though I am happy to make the changes across our packages with a deprecation once a decision is made.

**Comment by wbhart** [comment]
@thofma @fieker @rfourquet

**Comment by wbhart** [comment]
Sorry, didn't mean to tag you on this one. Decision is already made.

**Comment by wbhart** [comment]
Hmm, why didn't this close.

**Comment by rfourquet** [comment]
I lost track: was it discussed whether `coeff` should also be renamed to `coefficient` ?

**Comment by wbhart** [comment]
We haven't discussed it. I have to review whether that is a good idea or not. It's a super big change so I'm not keen on doing it until all the other is taken care of. But I'll return to it later for a decision if it seems worth it.
