### ISSUE TITLE
Concretize the generic interface for AbstractAlgebra

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/AbstractAlgebra.jl#785]
I think the generic interface in AbstractAlgebra should be concretized and distinguished from specific types-interface.

#782 I think suggests changes in the right direction.

**Comment by thofma** [comment]
Yes, fully agree. I think it would make sense to first discuss how the folder structure should be before doing more work in this direction.

@wbhart made in #782 already some suggestions for the organization of the splitting:
>[Aside: I guess we will eventually change the current generic directory to be called generic_structures or something similar, so generic_algorithms seems like a reasonable name for the directory for all the stuff you are moving. Edit: currently it seems to be called algorithms, so maybe we end up with "structures" and "algorithms" or similar. Edit: Edit: maybe we even end up with "algorithms" and "structures" inside a single "generic" directory.]

I personally would prefer if the directory for the "algorithms" would end up at the top level in `src/`. But I have no strong opinion. We just need to make a decision.

**Comment by wbhart** [comment]
I have no strong preference, so long as both dirs are named clearly.

**Comment by albinahlback** [comment]
> I think it would make sense to first discuss how the folder structure should be before doing more work in this direction.
> [...]
> I personally would prefer if the directory for the "algorithms" would end up at the top level in `src/`. But I have no strong opinion. We just need to make a decision.

I think that would be a good decision. I would prefer the generic interface of AA to be "directly visible" from `src/`, i.e. not hidden under `algorithms/`.

**Comment by wbhart** [comment]
I began splitting the abstract and generic stuff here https://github.com/Nemocas/AbstractAlgebra.jl/pull/887

I decided to put the algorithms stuff at the top level src directory and the generic types stuff in generic.
