### ISSUE TITLE
We use set_precision!, Julia uses setprecision

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#792]
I am not sure if this is a problem or not. Just wanted to bring it to the attention of others.

**Comment by fieker** [comment]
On Fri, Mar 12, 2021 at 05:59:05AM -0800, wbhart wrote:
> I am not sure if this is a problem or not. Just wanted to bring it to the attention of others.
> 
We use both.... there is/was/would have been an issue about this
somewhere...

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/issues/615

**Comment by wbhart** [comment]
Yeah I was talking about set_precision! vs setprecision. The reason I mention it is I went looking for the exact name in the REPL help and got the Julia one, which could be confusing for others.

Otherwise, yes, we've made a decision and I'm not pushing for it to be changed.

**Comment by wbhart** [comment]
I don't think we will make a further change to the names here, so I will close this.
