### ISSUE TITLE
Diagram of abstract types is outdated

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/AbstractAlgebra.jl#794]
I am currently working on it. It will use Kroki.jl in order to vectorize the output.

**Comment by wbhart** [comment]
I am very happy that you are doing this, but did you see the one in the dev docs that I did recently?

See the bottom of this page:

https://nemocas.github.io/Nemo.jl/dev/developer/typesystem/

**Comment by wbhart** [comment]
That one has a few nice properties. Firstly it is done in editable svg, so there are a lot of tools for editing it, even online ones. Secondly it looks essentially like text in GitHub, rather than a binary blob. Thirdly it is vectorised and scalable.

**Comment by albinahlback** [comment]
I did not know, very nice!

Would it be possible to make the text markable directly (instead of needing to view the actual image)? Also is it possible to scale some texts (some longer words like `AbstractPermutationGroup` is very very small)?

**Comment by wbhart** [comment]
By all means. The file should be editable using standard tools for editing svg's. Go right ahead. I am not so artistic. My only concern here was making the lines not cross. :-)

**Comment by wbhart** [comment]
Can we close this issue now? The original issue seems to have been dealt with.

**Comment by albinahlback** [comment]
Yes.
