### ISSUE TITLE
deprecate valence

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#802]
In src/generic/Misc/Poly.jl we have valence. However, this seems to do exactly the same thing as trail, except that trail returns zero if the polynomial is zero.

Does anyone object if I deprecate valence and make a PR against Hecke to switch it to trail?

Perhaps trail should be renamed to trailing_coefficient while we are at it?

**Comment by fieker** [comment]
On Tue, Mar 16, 2021 at 07:39:07AM -0700, wbhart wrote:
> In src/generic/Misc/Poly.jl we have valence. However, this seems to do exactly the same thing as trail, except that trail returns zero if the polynomial is zero.
> 
> Does anyone object if I deprecate valence and make a PR against Hecke to switch it to trail?
> 
> Perhaps trail should be renamed to trailing_coefficient while we are at it?
> 
I'd say yes to both

**Comment by thofma** [comment]
Yes to both!

**Comment by wbhart** [comment]
And this.
