### ISSUE TITLE
map_coeffs -> map_coefficients

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#804]
As I am currently deprecating coeffs and trail for coefficients and trailing_coefficient, do you also want me to deprecate map_coeffs for map_coefficients?

**Comment by wbhart** [comment]
As far as I can see, those are the last remaining coeff or coeffs deprecations that would be needed, except for coeff and setcoeff! which I'm inclined to leave just as they are.

**Comment by wbhart** [comment]
@fieker @thofma @rfourquet

**Comment by fieker** [comment]
On Thu, Mar 18, 2021 at 02:36:55AM -0700, wbhart wrote:
> @fieker @thofma @rfourquet 

map_coefficients - for consistency
(although I hate typing complicated words like that)

**Comment by wbhart** [comment]
Ok, once the dust settles from the lead, trail, lm, lc, lt, valence, coeffs PRs I'll make a PR to also change these.
