### ISSUE TITLE
Implement tail for polynomials

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#815]
This should return everything but the leading_term.

For multivariates, implementation should be independent of representation. Singular can likely do this faster than Nemo, but we'd still need to make a copy in our model. Perhaps there should be a "view/sub" version which allows access to the tail without a copy.

**Comment by tthsqe12** [comment]
Why do we need this? If you mean returning something that behaviors just like an ordinary polynomial, I don't think you will find singular.jl polynomials to fit the bill out of the box.
Is there something for which `Base.Iterators.drop(terms(p), 1)` doesn't satisfy your needs for a polynomial `p`?

**Comment by wbhart** [comment]
See the thread on oscar-dev for the origin of the suggestion. It's just a convenience function like constant_coefficient, etc. I believe.

**Comment by wbhart** [comment]
Here is an implementation for MPolys which seems to work ok:

```
function tail(f::AbstractAlgebra.MPolyElem)
          ctx = MPolyBuildCtx(parent(f))
          cv = Iterators.drop(zip(coefficients(f), exponent_vectors(f)), 1)
          for (c, v) in cv
             push_term!(ctx, c, v)
          end
          return finish(ctx)
       end
```

**Comment by wbhart** [comment]
I'm a bit worried about the name though. We just changed lead to leading_coefficient and lt to leading_term. Perhaps something more descriptive is needed that fits well with leading_term, though I am not sure what. I think trailing_terms is a misleading name as it seems like it should be an iterator. Suggestions welcome.

**Comment by wbhart** [comment]
trailing_part maybe?

**Comment by wbhart** [comment]
I have decided to use tail for the name. It's not in the Julia namespace. The only place it is currently used in our packages is in Oscar.jl where it computes.... the tail of a polynomial (and even there, only in an example).

Any complaints should be lodged now as I'm about to implement it.

**Comment by rfourquet** [comment]
Given the effort put into more consistent and explicit names, as you mentioned, I think a more specific name than `tail` is warranted. The non-exported `Base.tail` exists for tuples, and a generic name like that seems to refer to a collection. What about  `tail_terms` ?

**Comment by wbhart** [comment]
I decided that anything else would just be a synonym of the ordinary English word tail, and therefore tail is not an abbreviation.

tail_terms sounds like an iterator for the tail terms

trailing_terms suffers the same problem

tail_part seems like it doesn't add anything to the name tail

trailing_part may be confused with other functions starting with "trailing" which refer to the trailing term, not the tail of the poly

So in the end I decided that in fact the best name was tail.

**Comment by fieker** [comment]
On Thu, Mar 25, 2021 at 08:12:37AM -0700, wbhart wrote:
> I decided that anything else would just be a synonym of the ordinary English word tail, and therefore tail is not an abbreviation.
> 
> tail_terms sounds like an iterator for the tail terms
> 
> trailing_terms suffers the same problem
> 
> tail_part seems like it doesn't add anything to the name tail
> 
> trailing_part may be confused with other functions starting with "trailing" which refer to the trailing term, not the tail of the poly
> 
> So in the end I decided that in fact the best name was tail.
> 
No complaints

**Comment by tthsqe12** [comment]
If there does not seem to be a good name for this function, we could just leave the name up to the user since it is trivial to implement:
```
f(p) = p - leading_term(p)
```

**Comment by wbhart** [comment]
I was asked to implement it. It now exists.

**Comment by fieker** [comment]
On Thu, Mar 25, 2021 at 08:16:14AM -0700, tthsqe12 wrote:
> If there does not seem to be a good name for this function, we could just leave the name up to the user since it is trivial to implement:
> ```
> f(p) = p - leading_term(p)
> ```

Yep, but in singular you can do MUCH better than that - which is the
point of this. Also the Groebner people reallyl like this function...

**Comment by wbhart** [comment]
I haven't implemented a fast Singular version, since we'd need to make a copy anyway, unless spolys are going to be fully immutable.
