### ISSUE TITLE
tail for Poly and trailing_coefficient for MPoly?

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#822]
We currently have tail for MPoly (well, if the PR gets merged we will) and trailing_coefficient for Poly.

Do we want these to work for all polynomial types, i.e. tail for Poly and trailing_coefficient for MPoly?

I don't see much of a use for tail for Poly. I'm not sure how important the latter is either.

Let me know if you want them or not. They are easy to implement.

**Comment by fieker** [comment]
On Fri, Mar 26, 2021 at 02:49:22AM -0700, wbhart wrote:
> We currently have tail for MPoly (well, if the PR gets merged we will) and trailing_coefficient for Poly.
> 
> Do we want these to work for all polynomial types, i.e. tail for Poly and trailing_coefficient for MPoly?
> 
> I don't see much of a use for tail for Poly. I'm not sure how important the latter is either.
> 
> Let me know if you want them or not. They are easy to implement.

I'd say yes: people use the "wrong" types all the time: PolyElem for
MPoly in 1 var and MPoly with 1 var for PolyElem, so we need both
