### ISSUE TITLE
dense_poly_type and series_type

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#837]
We currently have dense_matrix_type for getting the type of a matrix that has been constructed using the function matrix.

We should also have functions dense_poly_type and dense_series_type.

Later on, if the SparsePoly module ever gets going we could have sparse_poly_type, but I don't propose to implement that now.

The purpose of such functions (I think) is so that the inner constructors can be called directly without first calling the constructor for the parent object. Indeed, we usually don't care about the parent at all, and want it to be minimally populated. Context objects can sometimes be copied from somewhere else, and so on.

Indeed Hecke seems to already have dense_poly_type and various other Hecke specific "blah_types".

Any comments on this proposal before I go ahead and implement it?

**Comment by thofma** [comment]
Love it!

PS: There are more applications, for example it is also helpful when specifying the types of arrays without constructing an instance.

**Comment by fieker** [comment]
On Fri, Apr 09, 2021 at 02:11:58AM -0700, wbhart wrote:
> We currently have dense_matrix_type for getting the type of a matrix that has been constructed using the function matrix.
> 
> We should also have functions dense_poly_type and dense_series_type.
> 
> Later on, if the SparsePoly module ever gets going we could have sparse_poly_type, but I don't propose to implement that now.
> 
> The purpose of such functions (I think) is so that the inner constructors can be called directly without first calling the constructor for the parent object. Indeed, we usually don't care about the parent at all, and want it to be minimally populated. Context objects can sometimes be copied from somewhere else, and so on.
> 
> Indeed Hecke seems to already have dense_poly_type and various other Hecke specific "blah_types".
> 
> Any comments on this proposal before I go ahead and implement it?

This would be helpful iff we support arithmetic with polynomials/ series
without a parent. Currently this does not work at all...
For matrices if I recall, we invested time to make sure to NOT compare
the parents, but the base_ring and the dimension instead.

So will this then involve
 - a new type: poly/ series without parent (the base_ring would then
   needed to be stored)
 - a removal of check_parent?

**Comment by wbhart** [comment]
Yes I see the problem, namely that to create a polynomial from the type alone one may need the parent. For fmpz_poly it works fine because the parent is fixed. But for generic polynomials one needs the parent to create the polynomials, since the polynomials store their parent. Thus just being able to derive the type is not enough in general.

Originally the inner constructors did not require the parent to be set. This is still the case for generic Polys but not for all other types, as we've been systematically passing the parent to the inner constructors. That could be reversed of course.

That leaves it up to the polynomial(blah) function to create the parent.

Some thoughts occur, but nothing I want to be quoted on:

* no I don't want to create parentless polynomials
* we could have a dummy parent for use in library code only, never to be passed back to the user which gets inserted to keep check_parent happy
* I don't see any need to cache parents created in library code, I agree with that principle

This all needs some thought. I'll try to come up with a better proposal next week.

**Comment by wbhart** [comment]
Probably generic evaluation/substitution code breaks if polynomials don't have proper parents. Things like derivatives might also break if variables are not distinguished. I think it is going to lead to more error prone code.

Really all I had in mind here was to have a polynomial(series) function which would create the relevant parent itself. It can copy the variable symbol and base ring across from the series. Anything anyone else adds to the parent objects in the future would be ignored and not copied. Functionality which requires such would simply be unavailable when creating polynomials in library code in this way.

**Comment by wbhart** [comment]
We could also make use of the function similar for polynomials and series, to create a similar series to an existing one but with a different base ring or variable.

**Comment by wbhart** [comment]
I have decided that making it so the inner constructors for polynomials can be called directly is not feasible for exactly the reasons highlighted by @fieker.

I now only want the functions dense_poly_type and abs_series_type and rel_series_type for type assertions and for typing arrays (and anything else where it happens to be useful).

Later we can also implement sparse_poly_type (if the SparsePoly module ever takes off) and mpoly_type, assuming we decide we need it. 

For now the polynomial, abs_series and rel_series constructors that I propose in https://github.com/Nemocas/AbstractAlgebra.jl/issues/836 will simply call the PolynomialRing and PowerSeriesRing constructors (in a safe way) to discourage devs from calling those themselves.

**Comment by wbhart** [comment]
Nevermind, I see that it in fact has to be like this.

**Comment by wbhart** [comment]
I made PR's for the dense_poly_type part. This was already completely done in Hecke, so it was only necessary to move the functions from Hecke to AA and Nemo and add tests.

**Comment by wbhart** [comment]
The abs_series_type and rel_series_type have been implemented and merged as part of #862
