### ISSUE TITLE
rand for PolyElem does not necessarily return a poly with degree in specified range

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#839]
Due to the leading coefficient possibly being zero, the degree can be lower than the range specified.

The main problem with changing it to produce a polynomial in the given range is that our test code will then only produce nonzero polynomials, as the zero polynomial does not have degree 0.

Any suggestions for how to get around this? E.g. rand(S, 0:5, -10:10) cannot produce the zero polynomial if we change it to only produce polynomials with degree in the range 0:5.

@thofma @fieker @tthsqe12 ( and possibly @rfourquet )

**Comment by wbhart** [comment]
The degree does seem to be -1. Of course that'd mean modifying all our test code to start at -1.

**Comment by thofma** [comment]
I like the idea of using `-1` for including zero polynomials. Makes it also easy to specify non-zero polynomials. I could help with adjusting the test code.

**Comment by wbhart** [comment]
Ok then. I am not sure if I'll get to it today or not, but could work on it with you tomorrow perhaps.
