### ISSUE TITLE
IdealSet is defined as a function and overwritten in Singular.jl

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#84]
AbstractAlgebra exports a function IdealSet, but this is the name of a type in Singular.jl, so it gets overwritten in Singular.jl.

**Comment by wbhart** [comment]
I guess this is intended to be used to construct the ideal set parent object for a given ring. But we should export such a function to the user from Oscar.jl rather than AbstractAlgebra.jl. That would then call the individual constructors in the various packages, rather than just import and export them. So I think I will remove the function in Nemo.jl.

**Comment by fieker** [comment]
On Fri, Apr 27, 2018 at 03:53:00AM -0700, wbhart wrote:
> I guess this is intended to be used to construct the ideal set parent object for a given ring. But we should export such a function to the user from Oscar.jl rather than AbstractAlgebra.jl. That would then call the individual constructors in the various packages, rather than just import and export them. So I think I will remove the function in Nemo.jl.
> 
So every package has to define a not exported function IdealSet that
will be called from Oscar?
Or should Oscar do
IdealSet(R::RingOfAbstractAlgebra) = AA.IdealSet(R)
or
IdealSet(R::RingOfAbstractAlgebra) = AAIdealSet(R)

and so on:

IdealSet(R::RingOfNemo) = Nemo.IdealSet(R)
IdealSet(R::RingOfHecke) = Hecke.IdealSet(R)

I can see that it is much easier to remove it from AA, but I think in
the long run, it will be renamed in Singular...

**Comment by wbhart** [comment]
The problem isn't that they export the function IdealSet. They can do this just fine.

The problem is the intention of having a function in AA that can be overloaded by other packages. This doesn't work for things that could be constructing types.

The intention of exporting it from AA is that other packages will import it. Singular.jl would not, for example, because of the conflict. So that kind of defeats the purpose of having it in the first place.

I would definitely expect that in the very long run, AA would itself define an IdealSet function which allows the definition of ideal sets for certain (very limited) ideals that it can construct. But the intention wouldn't be that other packages import this, since they probably do something much more sophisticated.

The principal of exporting dummy functions from AA that other packages can import and extend is actually fine. It just can't be done for things that might be types (with capital letters), unless the intention is that other packages NOT import them from AA.

**Comment by wbhart** [comment]
What I'm saying is that the other solution here is that I don't import IdealSet from AA in Singular.jl. But this demonstrates why it's a bad idea to define it with the intention of it being imported, because it just won't be in practice. It's fine to define it with the intention of it not being imported, as with many things with capital letters defined in AA.
