### ISSUE TITLE
Document PolynomialRing

### ISSUE THREAD

**Issue by ssiccha** [Nemocas/AbstractAlgebra.jl#863]
The method `PolynomialRing` is not documented, although IMO it is very central.

I'm a new user of Julia and Nemo, so I might just have missed it. Loading `Nemo` or `AbstractAlgebra` and entering `?PolynomialRing` only returns `No documentation found.` and a list of methods for `PolynomialRing`, but no documentation for these.

Ofc, I have found the example below:
https://nemocas.github.io/Nemo.jl/dev/constructors/#Constructing-parent-objects

**Comment by fieker** [comment]
On Tue, May 18, 2021 at 05:21:32AM -0700, Sergio Siccha wrote:
> The method `PolynomialRing` is not documented, although IMO it is very central.
> 
> I'm a new user of Julia and Nemo, so I might just have missed it. Loading `Nemo` or `AbstractAlgebra` and entering `?PolynomialRing` only returns `No documentation found.` and a list of methods for `PolynomialRing`, but no documentation for these.
> 
> Ofc, I have found the example below:
> https://nemocas.github.io/Nemo.jl/dev/constructors/#Constructing-parent-objects
> 
https://nemocas.github.io/AbstractAlgebra.jl/latest/mpolynomial_rings/
