### ISSUE TITLE
Implement variable-string-free polynomial rings, series rings, etc.

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#873]
Currently when we want to use polynomials, series, etc. in Generic code we often:

* don't care what variable name is used, since it will only ever be printed when debugging
* don't want the polynomial ring cached, since it pollutes the cache
* don't typically use the generator of the polynomial, since it is inefficient

We have developed numerous ways around this, such as using polynomial, abs_series and rel_series constructors. However, I propose an even better solution.

Suppose we implement parent constructors of the form:

R = PolynomialRing(ZZ) # univariate polynomial ring over ZZ
R = PolynomialRing(ZZ, 3) # multivariate polynomial ring over ZZ in 3 variables
R = RelSeriesRing(ZZ, cap=10) # relative power series ring over ZZ, precision cap 10
R = AbsSeriesRing(ZZ, cap=10) # absolute power series ring over ZZ, precision cap 10
R = AbsSeriesRing(ZZ, 3, cap=10) # absolute power series ring over ZZ in 3 variables, precision cap 10

These would create rings with the following properties:

1) They would not be cached (even as an option). You want that, use the full form we already have. This automatically protects against adding polynomials from two different rings, making generic code less prone to accidental bugs.
2) They would create the same type as the existing constructors, but would not set the variable symbol at all. Printing code would check if it is assigned, and if not, use default values, x for univariate, x1, x2, ... for multivariate. You want specific variable names, use the full form.
3) Note they do not return a variable, only the ring, which is the most common thing we want in Generic code.
4) They would be implemented in Generic with underscores, so the generic types would not accidentally be constructed from Generic code when say Nemo rings were more desirable. Instead we'd import the external AbstractAlgebra version of these into Generic without the underscore, so they'd automatically be called.

I think this proposal totally resolves all the current problems I have with the current use of parent rings inside Generic code. They seem to be foolproof and yet maximally useful, given our current usage patterns.

@fieker @thofma @tthsqe12 ?

**Comment by wbhart** [comment]
It's also possible to implement some nice macros that *can* be used in library code, to further simplify these, since there is no injection into scope here.

**Comment by fieker** [comment]
On Thu, May 20, 2021 at 07:50:13PM -0700, wbhart wrote:
> Currently when we want to use polynomials, series, etc. in Generic code we often:
> 
> * don't care what variable name is used, since it will only ever be printed when debugging
> * don't want the polynomial ring cached, since it pollutes the cache
> * don't typically use the generator of the polynomial, since it is inefficient
> 
> We have developed numerous ways around this, such as using polynomial, abs_series and rel_series constructors. However, I propose an even better solution.
> 
> Suppose we implement parent constructors of the form:
> 
> R = PolynomialRing(ZZ) # univariate polynomial ring over ZZ
> R = PolynomialRing(ZZ, 3) # multivariate polynomial ring over ZZ in 3 variables
> R = RelSeriesRing(ZZ, cap=10) # relative power series ring over ZZ, precision cap 10
> R = AbsSeriesRing(ZZ, cap=10) # absolute power series ring over ZZ, precision cap 10
> R = AbsSeriesRing(ZZ, 3, cap=10) # absolute power series ring over ZZ in 3 variables, precision cap 10
Fundamentally, we have them already.... the key difference are the
defaults, ie. they still default to cache = true
The very first things I've added to Hecke were the nameless
constructors...

**Comment by wbhart** [comment]
There are four points I gave outlining how these would be different to what we already have. Which of those four points do you already have?

Note that these are for the rings, not the elements.

**Comment by thofma** [comment]
I think we added `PolynomialRing(R) = PolynomialRing(R, "\$")` as a fallback, because some people got tired of writing "x" :smile:

I would be in favor of changing it as @wbhart suggests (making `cached = false` the default). In case one uses the nameless version, one usually does not want the caching. Do you have a scenario where you want the nameless version with caching @fieker?

**Comment by wbhart** [comment]
I don't think it should be an option. If you want features of the full interface, use the full interface. Let's make this as foolproof as possible!

**Comment by wbhart** [comment]
And just to clarify, this would not set a default string of "x". It would set *no* string, i.e. the field would remain unassigned.

The printing code would detect this and print "x" instead. Now that @tthsqe12 has made that possible with expressify, I think this is the best solution by far.

**Comment by thofma** [comment]
(No, it does not work nicely in the printing system. The function calls `var(R)` of the polynomial ring, which will throw an error if it is not assigned. The only way to test if it is assigned is to ask `isdefined(R, ...)`, but this would make the field name part of the polynomial ring interface. Not sure we want this. Or one does a `try catch` :cry: )

**Comment by wbhart** [comment]
I think it is important for performance reasons that we find a way to do that. I'd be more than happy to have var of a polynomial ring return "x" if it's unassigned. It's only going to be used here.

**Comment by wbhart** [comment]
Even better, it can return :unassigned, then the printing code can check for this.

**Comment by thofma** [comment]
Soo, we set `var = :unassigned` and then print "x". I am probably missing something, but why don't we set `var = :x` then?

**Comment by wbhart** [comment]
If it is done with a symbol, that might be fast enough. Let me try an experiment. The problem is at the moment we use a default value of "x" which is expensive, I believe.

**Comment by wbhart** [comment]
But my proposal was to not set it, and have the var *function* return :unasssigned.

**Comment by wbhart** [comment]
Yeah, I make it 24922 times slower to use a string than a symbol. So at the very least we should have these functions assign the symbol directly. Of course this all means adding to our interface. We'd have to add these new parent object constructors which I listed, to our interface, and we'd have to make the current inner constructors accept symbols instead of strings if we don't already, and that would have to be in the interface. But that's what we should have done from the start.

**Comment by thofma** [comment]
I guess we just need the symbol accepting constructors and then directly pass `:x`. This should be cheap.

**Comment by wbhart** [comment]
Yes, let's do it that way. That is a bit more regular, and definitely seems like a massive performance improvement. I think it really matters here, because library code could easily construct many polynomial or series rings. It doesn't matter for the user because they are typing the stuff out, so performance is irrelevant.

**Comment by wbhart** [comment]
It will also resolve https://github.com/Nemocas/AbstractAlgebra.jl/issues/48 which means triple internet points. Double because it will close this ticket and that one. Triple, because that is a really old ticket.

**Comment by thofma** [comment]
Do you think it would be confusing for users that `PolynomialRing(R, "x")` and `PolynomialRing(R)` have different return values (ring vs. tuple)?

**Comment by tthsqe12** [comment]
I do not think this is confusing and have never like the fact that `PolynomialRing(R, "x")` returns more than what is says it is.

**Comment by wbhart** [comment]
I don't think users should use this function. I think it should be used mainly by developers in library code. Of course I'm not going to stop advanced users using it. But I just think we need to explain clearly the difference.

It feels ok to me that the version that takes a variable string returns a variable and the one that doesn't, doesn't.

**Comment by wbhart** [comment]
There might be a good application for taking the cached keyword, actually (though the default should still be false).

We often have things like:

function myfun(p::PolyElem{T}; cached:Bool=true, parent::AbstractAlgebra.PolyRing=PolynomialRing(base_ring(a))) where T

where the function myfun is supposed to do something with the polynomial or vector p and return a new polynomial in the polynomial ring Rx. If this was a user facing function, you'd want the default for cached to be true, in which case it would be convenient to be able to pass that into the PolynomialRing constructor here.

I just hit an example of that in trying to clean up power_sums_to_polynomial.

**Comment by wbhart** [comment]
Or maybe not. Perhaps it is not ever a good idea to cache rings created automatically for the user without their intervention.

**Comment by wbhart** [comment]
In fact we will have to use different names to the existing constructors. We can't use PolynomialRing because the only way to make this safe to use would be to make Generic.PolynomialRing call the AbstractAlgebra version of the function. But we can't do that as it will break the ability to construct a generic polynomial ring when say a Nemo one would ordinarily be constructed.

I can't call it PolyRing either, as we already have both AbstractAlgebra.PolyRing and Generic.PolyRing types, and the two cannot be brought together.

Without renaming the abstract type to AbstractPolyRing, the best I can do is call the functions:

UPolyRing
AbsSeriesRing
RelSeriesRing

If you want me to rename all the abstract types instead, now is the time to speak up. That would enable us to have

PolyRing
AbsSeriesRing
RelSeriesRing

**Comment by tthsqe12** [comment]
yes. I like Abstract in front of all of the abstract types. Have had my fingers burned more than once on AbstractAlgebra.PolyRing and AbstractAlgebra.Generic.PolyRing.

**Comment by wbhart** [comment]
I'm happy to do it that way. What do you think @thofma @fieker 

It is a very disruptive change, but I'm happy to do the necessary PRs across our packages.

**Comment by thofma** [comment]
I really dislike that we have to type `AbstractAlgebra.PolyRing` and `AbstractAlgebra.Ring`. So much noise in the docstrings. I really dislike it. Have I mentioned that I really dislike it?

I am probably a bit consufed, but why can't we have `AbstractAlgebra.PolynomialRing(R::Ring) = AbstractAlgebra.PolynomialRing.Generic(R::Ring)`?

By the way I really dislike the `AbstractAlgebra` prefix on everything.

**Comment by wbhart** [comment]
The main reason we had it originally was so that it would still be possible to create a generic polynomial ring even if typing PolynomialRing would give say a Nemo one. For example, you could do Generic.PolynomialRing(Nemo.ZZ) and still get a generic polynomial ring over Nemo.ZZ's.

It's not turned out to be a very useful feature to be honest. And I'm happy to get rid of it if there is agreement.

But in order to do so we would actually *have* to put Abstract in front of all the abstract types, as we currently have an abstract type called PolyRing and a generic type called PolyRing. As these can't have the same name, one would have to be renamed. The logical choice would be to rename the abstract type to AbstractPolyRing, and same for all other abstract types.

I can't guarantee there aren't other conflicts I haven't thought of that would have to be resolved if we made this change. But I think those are the main ones.

I don't particularly like UPolyRing. I prefer PolyRing actually, and I think that is what the new variable-string-free constructor should be called. I like the idea of it having the same name as the generic type. It feels natural.

**Comment by tthsqe12** [comment]
I think we should still have the ability to construct a generic polynomial over Nemo.ZZ.

**Comment by wbhart** [comment]
Well, I suppose it would be possible to just change PolynomialRing and other parent constructors to be the same in both Generic and AbstractAlgebra but still keep the distinction for AbstractAlgebra.PolyRing and Generic.PolyRing. I'm not massively in favour of that though, as it is PolyRing I would like to overload for this new variable-string-free constructor.

As you already mentioned, PolynomialRing returns a tuple. It make sense to use PolyRing for the new constructor as it does not return a tuple.

**Comment by thofma** [comment]
I did not understand why we cannot define
```
AbstractAlgebra.PolynomialRing(R::Ring) = Generic.PolynomialRing(R::Ring)
```
in the toplevel of `AbstractAlgebra` and then
```
PolynomialRing(R::Ring) = blub
```
inside the `Generic` module.

**Comment by wbhart** [comment]
@tthsqe12 It would still be technically possible. For example you could call PolyRing{fmpz}(Nemo.ZZ) directly.

**Comment by thofma** [comment]
Also typing of the `AbstractAlgebra.` in front of everything is just a consequence of us putting the wrong things into the `Generic` module. It should only contain the generic implementation of the polynomial ring interface and not the methods that work for arbitrary `AbstractAlgebra.PolyRing`.

**Comment by wbhart** [comment]
@thofma Because that leads to you needing to call AbstractAlgebra.PolynomialRing(R) everywhere inside Generic, otherwise it would call the Generic version, which will create a generic polynomial ring where you probably want a Nemo one or whatever.

**Comment by thofma** [comment]
Yes, then this is excatly the problem with the wrong methods inside `Generic.` They should not be there and this is probably a good reason to finally untangle this.

**Comment by wbhart** [comment]
@thofma I guess that is true. If we moved all generic functions (as opposed to functions that only work for generic types) out of Generic back into AbstractAlgebra then that problem goes away.

**Comment by thofma** [comment]
If I remember correctly @tthsqe12 is also very much in favor of this.

I guess the biggest problem is the naming of the directoy, see https://github.com/Nemocas/AbstractAlgebra.jl/issues/785.

**Comment by wbhart** [comment]
Is there any serious reason to actually have a directory instead of just putting the files in the top level src directory. I mean, the files belong to AbstractAlgebra, so why not put them in the src directory.

**Comment by wbhart** [comment]
Yeah I see that you suggested that yourself @thofma on that ticket, so let's just put the generic algorithms files at the top level src directory and just have the directory generic for generic types.

**Comment by tthsqe12** [comment]
The last bug I dealt with along these lines was
https://github.com/Nemocas/AbstractAlgebra.jl/commit/729469b1dd50ea2bda995446cf385e39e44b91fd#diff-33a1a1a6c32a906fbd29bb6edf7a96d24792294ce12ece53df03c2ba31887b10

It would be nice if we knew we were writing code for the AbstractAlgebra.Generic.MPolyElem or the abstract AbstractAlgebra.MPolyElem, which doesn't have a .coeffs member. Possibly by separating the two implementations into different files.

**Comment by thofma** [comment]
Yes, this is the plan @tthsqe12.

If we every want to split the long files (looking at `Matrix.jl` for example), would you split them also in `src/`?

(I think @albinahlback was in favor of that. I suggested `src/bla/`, but I have no strong opinion. Top level is fine for me.)

**Comment by wbhart** [comment]
If there are no objections I will go ahead and start doing this. We don't need a ticket as #782 basically is about that.

This is the simplest way for everyone to get what they want. We can even retain the ability to create generic polynomials over Nemo.ZZ I think. And it makes perfect sense for the new constructors to be named after the Abstract types.

@tthsqe12 What we are discussing would make this problem essentially go away. The only code that would even refer to Generic.PolyRing would be inside src/generic. Referring to PolyRing in the vast majority of our code would mean AbstractAlgebra.PolyRing.

**Comment by wbhart** [comment]
... well, except for the fact that we don't have abstract types for AbsSeriesRing and RelSeriesRing right now. We only have SeriesRing, which is almost useless I would say. But that is a problem for another time.

**Comment by wbhart** [comment]
I think this would have to be merged first https://github.com/Nemocas/AbstractAlgebra.jl/pull/871 otherwise there will be merge conflicts.

**Comment by fredrik-johansson** [comment]
Parallel to this, how about allowing something like

    x = Polynomial(QQ)

Quite often I just want the generator.

**Comment by thofma** [comment]
I think with the proposal here this could be done via `polynomial(QQ, [1, 0])`.
