### ISSUE TITLE
Something is missing/superfluous in docstring for length of MPolys

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#876]
Currently there are two descriptions given for length, which seem to contradict one another, on this page [1].

[1] https://nemocas.github.io/AbstractAlgebra.jl/latest/mpolynomial_rings/

**Comment by tthsqe12** [comment]
That is quite a long page. I could only find one description. Can you point to or quote the contradictions?

**Comment by wbhart** [comment]
The description for the function length under Basic manipulation .... There are two descriptions of what it does.

**Comment by tthsqe12** [comment]
What I see is
> length(f::MyMPoly{T}) where T <: AbstractAlgebra.RingElem
> Return the number of nonzero terms of the given polynomial. The length of the zero polynomial is defined to be 000. The return value should be of type Int.
> ?????
> Return an array of the degrees of the polynomial fff in each of the variables.

This indicates to me that the documentation for degrees is missing in the ????? spot. :)

**Comment by wbhart** [comment]
Ah, that's what it is. Thanks. It was late last night and I couldn't figure out what that would be.

Curious that the docstring appears but not the function name.
