### ISSUE TITLE
power_sums_to_poly(poly_to_power_sums(f)) != f

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#883]
```
julia> using AbstractAlgebra
[ Info: Precompiling AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rationals, x)

julia> f = rand(R, 0:10, -10:10)
3//4*x^8 - 2//3*x^7 - 3//7*x^6 + 3//2*x^5 + 2//7*x^4 - 3//2*x^3 - 3//4*x^2 + 9//8*x - 9//2

julia> V = polynomial_to_power_sums(f)
8-element Vector{Rational{BigInt}}:
         2//3
        82//63
     -1265//378
    -15146//3969
     16418//11907
   9433507//1000188
   6975379//857304
 625311010//15752961

julia> g = power_sums_to_polynomial(V)
x^8 - 2//3*x^7 - 3//7*x^6 + 3//2*x^5 + 2//7*x^4 - 3//2*x^3 - 3//4*x^2 + 9//8*x - 9//2
```

I'm not sure what I should be expecting here. Should this return the same polynomial back? Should the input to polynomial_to_power_sums only accept monic polynomials? Should it scale by the leading coefficient? Something else?

Then there is this:

```
julia> f = rand(R, 0:10, -10:10)
1//2

julia> V = polynomial_to_power_sums(f)
Rational{BigInt}[]

julia> g = power_sums_to_polynomial(V)
ERROR: BoundsError: attempt to access 0-element Vector{Rational{BigInt}} at index [1]
Stacktrace:
 [1] getindex
   @ ./array.jl:801 [inlined]
 [2] power_sums_to_polynomial(P::Vector{Rational{BigInt}})
   @ AbstractAlgebra.Generic ~/.julia/dev/AbstractAlgebra/src/generic/Misc/Poly.jl:91
 [3] top-level scope
   @ REPL[14]:1
```

Should the power_sums_to_polynomial function exclude constant polynomials, or should it return 1 or maybe take a leading coefficient?

```
julia> f = rand(R, 0:10, -10:10)
2//3*x^2 - 9*x

julia> V = polynomial_to_power_sums(f)
2-element Vector{Rational{BigInt}}:
  9//1
 81//1

julia> g = power_sums_to_polynomial(V)
x - 9
```

Should the function exclude polynomials with zero constant coefficient?

```
julia> f = R()
0

julia> V = polynomial_to_power_sums(f)
ERROR: BoundsError: attempt to access 0-element Vector{Rational{BigInt}} at index [2]
Stacktrace:
 [1] getindex
   @ ./array.jl:801 [inlined]
 [2] polynomial_to_power_sums(f::AbstractAlgebra.Generic.Poly{Rational{BigInt}}, n::Int64)
   @ AbstractAlgebra.Generic ~/.julia/dev/AbstractAlgebra/src/generic/Misc/Poly.jl:65
 [3] polynomial_to_power_sums(f::AbstractAlgebra.Generic.Poly{Rational{BigInt}})
   @ AbstractAlgebra.Generic ~/.julia/dev/AbstractAlgebra/src/generic/Misc/Poly.jl:55
 [4] top-level scope
   @ REPL[20]:1
```

Should the function exclude the zero polynomial?

Also, what does the function actually do? What are power sums?

**Comment by wbhart** [comment]
```
julia> using AbstractAlgebra
[ Info: Precompiling AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rationals, x)

julia> f = 3//2*x^2 + x + 7//3
3//2*x^2 + x + 7//3

julia> V = polynomial_to_power_sums(f)
2-element Vector{Rational{BigInt}}:
 -2//3
 -8//3

julia> power_sums_to_polynomial(V)
x^2 + 2//3*x + 14//9
```

**Comment by fieker** [comment]
To spell it out: thus is about the newton-girard formulae, power sums are sum x_i^j where x_i is running over the roots. And yes customarily they are applied to monic polynomials, in my application to non constant, mostly irreducibles

**Comment by wbhart** [comment]
Ok, that explains why nothing changes when the polynomial is multiplied by a power of x. Is this a problem? Should the power_sums_to_polynomial take a degree or something? Is it important that the identity in the title of this issue holds?

**Comment by fieker** [comment]
On Wed, May 26, 2021 at 05:10:00AM -0700, wbhart wrote:
> Ok, that explains why nothing changes when the polynomial is multiplied by a power of x. Is this a problem? Should the power_sums_to_polynomial take a degree or something? Is it important that the identity in the title of this issue holds?
> 
I'd tend to ban
 - non-monic
 - divisible by x

**Comment by wbhart** [comment]
What about the polynomial 1? The interface won't allow supporting power_sums_to_polynomial with an empty list. Should I ban constant polynomials too?

**Comment by fieker** [comment]
On Wed, May 26, 2021 at 07:43:08AM -0700, wbhart wrote:
> What about the polynomial 1? The interface won't allow supporting power_sums_to_polynomial with an empty list. Should I ban constant polynomials too?
> 
I'd say yes...

**Comment by wbhart** [comment]
Ok, banned for now. We can add the functionality back in if we need it, and are prepared to change the interface.

**Comment by wbhart** [comment]
The second algorithm requires access to E[2] which is not accessible if the input had n = 1. Any suggestions what you want to happen there?

**Comment by wbhart** [comment]
It's ok, I just compute some of the values in special cases.
