### ISSUE TITLE
R([a, b, c]), polynomial, abs_series and rel_series constructors should accept iterators

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#884]
Quite a few functional compositions are possible with pure iterators that could in turn be used to construct polynomials and series without actually constructing the arrays of coefficients that go into them (generic polys and series excepted of course).

The constructors should simply accept iterators, e.g.

```
R, x = PolynomialRing(ZZ, "x")

f = 1 + 2x + 3x^2

g = polynomial(QQ, Base.Iterators.reverse(coefficients(f)))
```

This would save allocations and increase performance.

**Comment by wbhart** [comment]
On the other hand, our iterators don't seem to support Base.iterators.reverse and the like. We may not be implementing the full interface.

**Comment by wbhart** [comment]
In Nemo, where QQ is a FieldElem the leading coefficient problem seems to be different:

```
julia> using AbstractAlgebra
[ Info: Precompiling AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rationals, x)

julia> f = 3//2*x^2 + x + 7//3
3//2*x^2 + x + 7//3

julia> V = polynomial_to_power_sums(f)
2-element Vector{Rational{BigInt}}:
 -2//3
 -8//3

julia> power_sums_to_polynomial(V)
x^2 + 2//3*x + 14//9
```

**Comment by thofma** [comment]
Great idea, I like it! We could also do the same for matrices a la  `matrix(QQ, 2, 2, (i^2 for i in 1:4))`.

**Comment by fieker** [comment]
The only problem (while I relly like this) is the lack of typing for iterators...
I'd also like to do gcd(coefficients(f)) and similar, but even in Base it is kind of random where iterators are supported and where not.
I like the idea

**Comment by fieker** [comment]
Yep. I haven't been able to use anything but any as a type. I'd like
ITER{t} or so

**Comment by wbhart** [comment]
Yeah, seems to be an oversight. I just checked and the reverse iterator for
example has supertype Any. Not very useful.

**Comment by wbhart** [comment]
Hmm, actually, Julia iterators don't work the way I thought they did:

```
collect(Iterators.take(Iterators.reverse(Iterators.take([1, 2, 3, 4, 5], 3)), 2))
ERROR: MethodError: no method matching iterate(::Base.Iterators.Reverse{Base.Iterators.Take{Array{Int64,1}}})
Closest candidates are:
  iterate(::LibGit2.GitRevWalker) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LibGit2/src/walker.jl:29
  iterate(::LibGit2.GitRevWalker, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LibGit2/src/walker.jl:29
  iterate(::Base.EnvDict) at env.jl:119
  ...
Stacktrace:
 [1] iterate at ./iterators.jl:653 [inlined]
 [2] iterate at ./iterators.jl:651 [inlined]
 [3] copyto!(::Array{Int64,1}, ::Base.Iterators.Take{Base.Iterators.Reverse{Base.Iterators.Take{Array{Int64,1}}}}) at ./abstractarray.jl:733
 [4] _collect at ./array.jl:630 [inlined]
 [5] collect(::Base.Iterators.Take{Base.Iterators.Reverse{Base.Iterators.Take{Array{Int64,1}}}}) at ./array.jl:624
 [6] top-level scope at REPL[32]:1
```

They aren't fundamentally designed to be composed.

**Comment by wbhart** [comment]
This turns out to not be worth doing. Iterators in Julia are not particularly useful. For example:

* iterators cannot be arbitrarily composed
* eltype is not propagated through Reverse, Take and friends, leading to a combinatorial explosion of eltype definitions required for every single one of the iterators you define

In short, Julia can't have an Iterable abstract type because objects which are iterable (such as arrays) would already belong to some abstract type and so could not also belong to Iterable, due to the lack of multiple inheritance in Julia.
