### ISSUE TITLE
"base_ring" of multivariate polynomial ring

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#888]
Our definition of `base_ring` is that it is something implementation specific (not related to mathematics), which is fine. (We actually don't have a definition, just some information scattered across various emails/issues). For example `base_ring(::FlintRationalField) = Union{}`. This is all fine. But this is not how it is used for multivariate polynomial rings. There all functions require that `base_ring` is in fact not something implementation specific, but really the coefficient ring.

We are running into problems in Oscar, because we have polynomial rings (type `T`) derived from polynomial rings of type `S` (both subtypes of `MPolyRing`) , so with the AbstractAlgebra philosophy, `base_ring(R::T)` gives something of type `S`. (This is necessary to make the rings play nice with the promotion system). But this choice of `base_ring` makes the generic functions for multivariate polynomials fail.

Maybe we could have `coefficient_ring` for polynomial rings and use it at the places where we really need the coefficient ring?

**Comment by wbhart** [comment]
Yes, I would strongly support having coefficient_ring for multivariates, especially with the way things are done in Singular.jl. This makes much more sense than using base_ring. I have encountered this myself, e.g. the coefficient ring of a rational function field (currently I call it base_ring, but this is not convenient in some cases).

**Comment by thofma** [comment]
Great :)

I will do this once you are finished with #887.

**Comment by tthsqe12** [comment]
> But this choice of base_ring makes the generic functions for multivariate polynomials fail.

example?

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/MPoly.jl#L339

**Comment by thofma** [comment]
Sorry, this example is wrong. Here is a better one:
https://github.com/Nemocas/AbstractAlgebra.jl/blob/97d5e3e92ffd371c4d07c120c49701d17819dc11/src/generic/MPoly.jl#L1412

**Comment by tthsqe12** [comment]
For me, the line
```julia
      return base_ring(x)()
```
means "return an arbitrary element of the base ring of x".
Is this what is inteded here?

**Comment by thofma** [comment]
I don't think this is the question. Here one needs that "base ring" means coefficient ring and not "some" ring that was used in the construction of your polynomial ring.

**Comment by tthsqe12** [comment]
so you have an MPolyElem where base_ring does not return the coefficient ring?

**Comment by thofma** [comment]
Yes, think of graded polynomial rings, where it would make sense to have base ring be the original multivariate ring.
