### ISSUE TITLE
hash for perms

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#90]
Why is [hash](https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/PermGroups.jl#L27) for perms so complicated? In other projects I'd use something like simple `hash(a::perm, h::UInt) = hash(a.d, hash(perm, h))` delegating the hashing to standard routines (note that this does not account for type parametrizing perms, but our equality does without the type as well).

I guess this is a left-over of the flint-based implementation, but can anyone more experienced explain?

**Comment by thofma** [comment]
It is a leftofter. We can switch to `hash(a::perm, h::UInt) = hash(a.d, h)`.

**Comment by wbhart** [comment]
You don't want the hash of a perm to be the same as the hash of whatever
a.d is. The system should be able to distinguish these. Therefore, at least
xor with some fixed, precomputed random UInt so that it is different to the
hash of a.d.

**Comment by kalmarek** [comment]
we could do 
```julia
# hash(perm) = 0x0d9939c64ab650ca
Base.hash(a::perm, h::UInt) = xor(hash(a.d, h), 0x0d9939c64ab650ca)
```
but what are the advantages of it compared to `hash(a.d, hash(perm, h))`?

Related-nonrelated question: do we need to overload `deepcopy_internal`, shouldn't `deepcopy` be enough?

**Comment by thofma** [comment]
No, it must be `deepcopy_internal`, see the docstring of `deepcopy`.

**Comment by kalmarek** [comment]
ok, I misunderstood the docstring; 

but my tests indicate that overloading `deepcopy_internal` is not needed anymore. The without it the default `deepcopy` works fine and even copies cycle decomposition, if available (something we should do as well).

**Comment by thofma** [comment]
Yes, if we don't store the parent on the object, we can just use the default version.

**Comment by kalmarek** [comment]
fixed by https://github.com/Nemocas/AbstractAlgebra.jl/pull/95
