### ISSUE TITLE
deepcopy_internal seems to be used suspiciously

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#906]
There is code like this
https://github.com/Nemocas/AbstractAlgebra.jl/blob/25a88f9a43b2564b2cee1f338be508d52c43ef3e/src/generic/Matrix.jl#L83-L91
all over the place. Why do we define `deepcopy_internal` if we are not going to pass the dictionary along to the children?

**Comment by thofma** [comment]
One "has" to define `deepcopy_internal`. It is our omission that we do not pass it along I think.

**Comment by tthsqe12** [comment]
So the dictionary should be passed along?

**Comment by thofma** [comment]
Yes.

**Comment by tthsqe12** [comment]
And how is this supposed to make an "identical" copy when similar does not even return something of the same type?

**Comment by thofma** [comment]
Is this still happening? Should be a bug.

**Comment by tthsqe12** [comment]
@wbhart is `similar(d)` supposed to return something of the same type as `d`?

**Comment by wbhart** [comment]
I'm unable to find counterexamples, though I am not sure why exactly. Apparently if I do manage to make a generic matrix over Z in Nemo, similar returns another. I don't really know why.

**Comment by wbhart** [comment]
I guess my recent fix took care of that.

**Comment by thofma** [comment]
There is a fallback for similar creating a generic matrix.

**Comment by wbhart** [comment]
Yeah, it's just that the original design of the similar system was that it would create the matrix the user would get in that package if they created it themselves, e.g. if you have a generic matrix over a number field and create a similar one over Z you get an fmpz_mat not another generic one.

Apparently this doesn't hold any more.

**Comment by wbhart** [comment]
Regarding the dict: it is only necessary to pass this along if the object can internally reference itself. This is not the case for most of our types, as we tend to construct things as a tree in mathematics. I'm not sure we actually need to pass it along anywhere, but correct me if I have overlooked an example of a recursive object in the mathematics we are dealing with.

**Comment by rfourquet** [comment]
> Regarding the dict: my understanding is that it is only necessary to pass this along if the object can internally reference itself. 

That sounds right for correctness, but not for efficiency: calling `deepcopy` within the definition of a `deepcopy_internal` method is suboptimal as `deepcopy(x)` will call `deepcopy_internal(x, IdDict())`, so new `IdIDct`s are created unnecessarily. But in many cases it doesn't matter (I wanted to fix some of these instances at one point, but often the creation of `IdDict` was not meaningfully affecting performance; but I first opened a (somewhat controversial) [issue](#560) about the fact that `deepcopy` was probably not the right abstraction for the project).

**Comment by wbhart** [comment]
I see, so you are saying it might be better for us to pass on the IdDict anyway, to save creation of a new one, which is a (minor) performance issue.

Some of the tickets you originally opened are probably worth considering again now. We weren't in a position resource-wise to consider them at the time, as the priority had to be to get everything done in time for the review. As you probably noticed, I'm working on a lot more cleanup nowadays than we were back then.
