### ISSUE TITLE
Kroki needs internet access

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#922]
Unfortunately, Kroki needs internet access (https://github.com/oscar-system/Oscar.jl/issues/529) which we think is unfortunately not acceptable. We want to be able to build the documentation locally without internet access. Since the content of the diagrams are hard coded anyway, I suggest we add the images back to the repository and move the current functions to a script 
`docs/src/update_diagramms.jl`.

CC: @albinahlback @fingolfin @fieker

**Comment by fieker** [comment]
Yep, the way forward!
