### ISSUE TITLE
nrows/ncols is not documented for a MatAlgebra or MatSpace parent object and doesn't apply for an Abstract MatSpace

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#965]
you can only do nrows and ncols of a matrix, but shouldn't you be able call this on the parent objects?

**Comment by wbhart** [comment]
I'm not sure what you mean. It's here:

**Comment by tthsqe12** [comment]
> but shouldn't you be able call this on the parent objects?

**Comment by tthsqe12** [comment]
To be clear, the docs don't say anything about this function, but I think the matrix space / matrix algebra is quite useless without it.
`nrows(MatrixAlgebra(ZZ, 1))`

**Comment by wbhart** [comment]
So the title of the issue is not correct?

**Comment by tthsqe12** [comment]
What do you want it to say? I see no requirement for begin able to call nrows on a MatAlgebra
