### ISSUE TITLE
no method matching isdomain_type(::Type{AbstractAlgebra.Generic.MatAlgElem{BigInt}})

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#966]
From https://nemocas.github.io/AbstractAlgebra.jl/dev/matrix_interface/#Matrix-Interface
> For matrix algebras, all of the ring interface must be implemented.

Then, we have

```julia
julia> using AbstractAlgebra

julia> A = MatrixAlgebra(ZZ, 1)
Matrix Algebra of degree 1 over Integers

julia> isdomain_type(elem_type(A))
ERROR: MethodError: no method matching isdomain_type(::Type{AbstractAlgebra.Generic.MatAlgElem{BigInt}})
```

**Comment by thofma** [comment]
Does it operate on elements? I thought only `isdomain_type(A)` needs to work.

**Comment by tthsqe12** [comment]
It only appears once in the ring interface as:
```
isdomain_type(::Type{MyElem})
```

**Comment by thofma** [comment]
Ah, I see, I guess this is missing.
