### ISSUE TITLE
Compare polynomials belonging to different multivariate polynomial rings

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#97]
I am surprised to obtain `true` as the result of the comparison in the following example. I would either expect an error or `false`. Is `true` supposed to be the correct result? If so, why?

```
julia> using AbstractAlgebra
INFO: Recompiling stale cache file /home/florian/.julia/lib/v0.6/AbstractAlgebra.ji for module AbstractAlgebra.

Welcome to AbstractAlgebra version 0.0.8

AbstractAlgebra comes with absolutely no warranty whatsoever


julia> R,vars_R = PolynomialRing(QQ,["x","y"]; ordering=:deglex); x,y = vars_R;

julia> S,vars_S = PolynomialRing(QQ,["a","b"]; ordering=:deglex); a,b = vars_S;

julia> a==x
true
```

**Comment by thofma** [comment]
We are missing the parent check. It should throw an error.

**Comment by heiderich** [comment]
Thanks. I will prepare a PR.

**Comment by wbhart** [comment]
On 8 June 2018 at 13:45, Florian Heiderich <notifications@github.com> wrote:

> Thanks. I will prepare a PR.
>

Thank you. Agreed, it's a bug.
