### ISSUE TITLE
characteristic should not return -1

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#993]
I was surprised by this:
```
julia> R = ResidueRing(ZZ, 16453889)
Residue ring of Integers modulo 16453889

julia> S, x = PolynomialRing(R, "x")
(Univariate Polynomial Ring in x over Residue ring of Integers modulo 16453889, x)

julia> T = ResidueRing(S, x^3 + 3x + 1)
Residue ring of Univariate Polynomial Ring in x over Residue ring of Integers modulo 16453889 modulo x^3 + 3*x + 1

julia> characteristic(T)
-1
```
For `characteristic(T)` would expect either of the following:
- the actual characteristic, which here is the same as `characteristic(S)` or `characteristic(R)`, i.e., 16453889
- an error "unknown characteristic"

But definitely not -1. 

Moreover, whatever this code does, I'd say the docstring(s) for `characteristic` should document what happens if the characteristic is not (easily) computable.

**Comment by fieker** [comment]
On Tue, Aug 17, 2021 at 01:52:20AM -0700, Max Horn wrote:
> I was surprised by this:
So am I - I though the recent change fixed that: apart from special
cases (Z/nZ) char = char(base_ring)

But aparently not.

I fully second error instead of -1

**Comment by tthsqe12** [comment]
AA's ResidueRing has some well-known issues and only works in a few cases.
