### ISSUE TITLE
Question about conformance test performing `isone(inv(one(R)))`

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#994]
The conformance tests added by @tthsqe12 among other things have a test that does `isone(inv(one(R)))`. But this does not work for all rings. E.g.:
```
julia> S, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> T = ResidueRing(S, x^2 + 1)
Residue ring of Univariate Polynomial Ring in x over Integers modulo x^2 + 1

julia> inv(one(T))
ERROR: MethodError: no method matching gcdinv(::AbstractAlgebra.Generic.Poly{BigInt}, ::AbstractAlgebra.Generic.Poly{BigInt})
Stacktrace:
 [1] inv(a::AbstractAlgebra.Generic.Res{AbstractAlgebra.Generic.Poly{BigInt}})
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/Residue.jl:309
 [2] top-level scope
   @ REPL[78]:1
```

There are two separate questions this raises:

1. Should this particular case be made to work? E.g. one could extend `gcdinv` to work on `ZZ[x]` by letting it compute in `QQ[X]`, and if the result is in `ZZ[x]` then it is the inverse; if not, there is no inverse. (It may not be worth the effort, though. Personally, I am neutral on this, I am mostly raising this out of completeness; it is the next point that is my true concern here).

2. In general of course one can residue rings where we don't have a general algorithm to compute inverses (or it might involve Gröbner bases, or other things that are not easy or sensible to implement in AA). So...
    1. should we stop testing `inv(one(T))` in the conformance tests?
    2. should we keep it, but catch exceptions and if there are any, accept that as well? I.e.: "it may not work, but if it does, it should return something correct" ?

**Comment by tthsqe12** [comment]
Again, more issues with ResidueRing. My 2 cents: instead of putting try catch everywhere, only test the conformance of a ResidueRing R when we know AA knows the Euclidean structure on base_ring(R).

**Comment by fingolfin** [comment]
This now works both in AA and Nemo:
```
julia> S, x = polynomial_ring(ZZ, "x")
(Univariate polynomial ring in x over integers, x)

julia> T, f = residue_ring(S, x^2 + 1)
(Residue ring of S modulo x^2 + 1, Map: S -> T)

julia> inv(one(T))
1
```
